config/localSettings.base.ts
public/scripts/mercury/modules/Trackers/GoogleAnalytics.ts
test/specs/public/scripts/mercury/modules/Trackers/GoogleAnalytics.js

https://wikia-inc.atlassian.net/browse/HG-501
We don't need to send this data here, it's redundant

Remove UA-32132943-5 as this is not used

---

public/scripts/baseline/mercury.d.ts
public/scripts/main/models/ArticleModel.ts
public/scripts/mercury/utils/track.ts
server/routes.ts
views/_helpers/_example.js
views/_partials/tracking-pixels.hbs
views/_partials/tracking.hbs
views/layout.hbs

Merging #493 to `master` branch.

Support for noexternals=1

---

CHANGELOG.md

Backport master to dev

---

package.json

Update bluebird, hapi and newrelic libraries

---

public/scripts/main/router.ts
public/scripts/main/views/ApplicationView.ts

Disable location API for Catchpoint tests.

Catchpoint support

---

server/app.ts

https://wikia-inc.atlassian.net/browse/HG-532

Don't parse cookies

---

front/styles/component/_lightbox.scss

https://wikia-inc.atlassian.net/browse/HG-327

Increase the tap area for lightbox close button by 20px

---

front/scripts/main/controllers/MediaLightboxController.ts
front/scripts/main/routes/ArticleRoute.ts

This would work like this:
open image -> go back - closes lightbox
open image -> go to next/prev image -> go back - prev image -> go back closes lightbox
Is this something that we want?

Close lightbox on back button

---

front/scripts/main/controllers/ArticleController.ts

https://wikia-inc.atlassian.net/browse/HG-539

Fixed problem with handling links when comments are opened

---

front/scripts/main/components/ArticleCommentComponent.ts
front/styles/module/article/_media.scss

https://wikia-inc.atlassian.net/browse/HG-489

Add play icon to video thumbnail in comment

---

front/scripts/main/controllers/ApplicationController.ts
front/scripts/main/routes/ApplicationRoute.ts
front/scripts/main/views/ApplicationView.ts
front/scripts/main/views/LightboxView.ts
front/styles/state/_no-scroll.scss
front/styles/state/index.scss

https://wikia-inc.atlassian.net/browse/HG-457
Nothing new, this code was here before. This causes top bar to hide/show after toggling side nav but it's a lower priority task than menu not being scrollable.

Revert method for setting body unscrollable to the one that was working

---

bower.json

https://github.com/emberjs/ember.js/compare/v1.9.0...v1.9.1

Update Ember 1.9.0 -> 1.9.1

---

bower.json

https://wikia-inc.atlassian.net/browse/HG-550
Don't merge before this is QAed thoroughly.

Update Fastclick 1.0.3-wikia -> 1.0.6

---

tasks/changelog.sh

Accept branch names other than `release-*`.

Fix changelog.sh

---

front/scripts/main/components/GalleryMediaComponent.ts
front/scripts/main/mixins/ArticleContentMixin.ts

https://wikia-inc.atlassian.net/browse/HG-536

Fix loading images in horizontal galleries after window resize

---

front/scripts/main/views/ApplicationView.ts

I know it's duplicated, but logic to deduplicate that seems like an overhead to me know

Call preventdefault only when we do something with a click

---

CHANGELOG.md
front/scripts/main/views/ApplicationView.ts

* CONCF-39: Call preventdefault only when we do something with a click

Merge dev to master for release-40

---

front/scripts/mercury/utils/track.ts

This was missed in https://github.com/Wikia/mercury/pull/558

Use the correct queryParams variable

---

front/styles/component/_lightbox.scss

https://wikia-inc.atlassian.net/browse/CONCF-109

Stop stretching images in lightbox

---

front/scripts/main/models/ArticleModel.ts
server/routes.ts

https://wikia-inc.atlassian.net/browse/CONCF-71

Links to non-existing pages render 404 page

---

gulp/tasks/watch.js
package.json

Everything seems fine, tests are passing.
/cc @hakubo

Update npm dependencies; fix browser-sync

---

front/scripts/main/components/SideNavComponent.ts

SideNavComponent search issue.

Change 'query' to 'search' in search query

---

config/localSettings.base.ts
config/localSettings.d.ts
front/scripts/main/routes/ApplicationRoute.ts
server/routes.ts
server/views/layout.hbs

https://wikia-inc.atlassian.net/browse/HG-559

HG-559 Base implementation for Optimizely

---

front/scripts/main/routes/ApplicationRoute.ts

https://github.com/emberjs/ember.js/blob/v1.9.1/packages/ember-routing/lib/system/route.js#L1748 & https://github.com/emberjs/ember.js/blob/v1.9.1/packages/ember-routing/lib/system/route.js#L1840
/cc @Warkot

openLightbox and closeLightbox don't return anything

---

front/scripts/main/components/WikiaFooterComponent.ts
front/scripts/main/routes/ApplicationRoute.ts

Skin choosing process is controlled by cookie on Varnish. → https://github.com/Wikia/wikia-vcl/blob/master/control-skin.vcl

CONCF-7 | 'Full site' footer link fix (switches skin to the wiki's default skin)

---

bower.json
front/scripts/main/components/ArticleCommentComponent.ts
front/scripts/main/components/GalleryMediaComponent.ts
front/scripts/main/components/ImageMediaComponent.ts
front/scripts/main/components/MediaComponent.ts
front/scripts/main/helpers/thumbnailHelper.ts
front/styles/module/article/_media.scss
front/templates/main/components/image-media.hbs
front/templates/main/components/video-media.hbs
test/specs/front/scripts/main/helpers/thumbnailHelper.js

https://wikia-inc.atlassian.net/browse/CONCF-76
Some images are transparent and it looks silly.

Rework how we load thumbnails

---

front/scripts/main/components/AdSlotComponent.ts
front/styles/module/_ads.scss
test/specs/front/scripts/main/components/AdSlotComponent.js

https://wikia-inc.atlassian.net/browse/CONCF-84
`noAds` as a computed property and class binding.

Fixed top leaderboard ad height

---

tasks/release.sh

Add -e flag to echo commands as Windows Git Bash needs it.

Fix release.sh on Windows

---

front/styles/module/_ads.scss

https://wikia-inc.atlassian.net/browse/CONCF-170
Tested using mobile emulation in Chrome. Looks good with smart banner and without it.

Unfixed top leaderboard ad height

---

front/scripts/main/app.ts
front/scripts/main/views/MediaLightboxView.ts
typings/hammerjs/hammerjs.d.ts
typings/touch-events/touch-events.d.ts

After some rework how we deal with gestures and actually implementing it on my own
I have noticed that actually supporting all the edge cases would make me 'reimplement' hammer.
We might take ownership of hammer as it currently lack a maintainer, but does everything we need currently.
I fixed most annoying issues that we have, but I think we should leave it for now.

Hammer improvements

---

front/scripts/main/controllers/ApplicationController.ts
front/styles/module/_loader.scss

CONCF-78 add delay before showing spinner on page loading

---

config/localSettings.base.ts
config/localSettings.d.ts
front/scripts/mercury/modules/Trackers/Krux.ts

https://wikia-inc.atlassian.net/browse/CONCF-81
Enable Krux on Mercury.
Please note this pull request is only a part of CONCF-81 ticket. Second part can be found in app repo. PR: https://github.com/Wikia/app/pull/6545

Enable Krux on Mercury

---

gulp/utils/environment.js

Before DT gets updated we need to normalise the name for build

We need to normalize it for DT before they get updated

---

README.md

https://wikia-inc.atlassian.net/browse/CONCF-166

CONCF-166 change bower install to bower update

---

front/scripts/main/controllers/ApplicationController.ts
server/views/layout.hbs

https://wikia-inc.atlassian.net/browse/CONCF-296
This is part of the ticket. Second part can be found here: https://github.com/Wikia/app/pull/6697

CONCF-296 add siteMessage to meta tags

---

front/styles/auth/_settings.scss
front/styles/auth/app.scss

We'll upgrade gulp-sass with https://wikia-inc.atlassian.net/browse/HG-573, but this is the workaround until then to make sure tests pass.
@kenkouot @bkoval

Fixing gulp sass error

---

server/facets/showArticle.ts
server/views/layout.hbs

Defers the loading of our vendor and application scripts. Also defers loading the optimizely script as well since Ember fires after optimizely.
Also reorders inlined scripts to be after external resources in the head.

Google pagespeed adjustments

---

front/scripts/main/components/LoginIconComponent.ts

Dynamically resolve href for the login flow

---

server/views/_layouts/ember-main.hbs

There is a ticket in JIRA, it's much better than this comment.
https://wikia-inc.atlassian.net/browse/HG-581

Remove obsolete comment

---

server/routes.ts

This shouldn't be merged to dev anyway, see https://github.com/Wikia/mercury/pull/592#discussion-diff-27467355

Remove /test route

---

config/localSettings.base.ts
front/scripts/mercury/modules/Trackers/GoogleAnalytics.ts
test/specs/front/scripts/mercury/modules/Trackers/GoogleAnalytics.js

https://wikia-inc.atlassian.net/browse/CONCF-410

Remove 100% GA account

---

front/styles/main/module/_ads.scss
front/templates/main/application.hbs

We don't have high impact slot like `INVISIBLE_SKIN` for mobile (Mercury). This is first try to have it :smile_cat:

ADEN-1780: Added new high impact slot

---

front/scripts/main/components/LocalWikiaSearchComponent.ts
front/scripts/main/controllers/ArticleController.ts
front/scripts/main/routes/ArticleRoute.ts
front/scripts/mercury/utils/articleLink.ts
front/scripts/mercury/utils/string.ts
front/templates/main/components/local-wikia-search.hbs
test/specs/front/scripts/mercury/utils/string.js

https://wikia-inc.atlassian.net/browse/CONCF-126
https://wikia-inc.atlassian.net/browse/CONCF-74
We shouldn't try to decode titles which weren't encoded in the first place. This PR cleans it up and fixes search results.

CONCF-126 Support articles with special chars in title

---

bower.json
front/scripts/main/components/ArticleCommentComponent.ts
front/scripts/main/components/GalleryMediaComponent.ts
front/scripts/main/components/ImageMediaComponent.ts
front/scripts/main/components/MediaComponent.ts
front/scripts/main/helpers/thumbnailHelper.ts
test/specs/front/scripts/main/helpers/thumbnailHelper.js

https://wikia-inc.atlassian.net/browse/CONCF-207
Upgrading to vignette-js#2.1.1 was enough to fix the issue where images in gallery were not cropped properly.

CONCF-207 Upgrade to vignette-js#2.1.1

---

front/locales/en/main.json

https://wikia-inc.atlassian.net/browse/CONCF-300

Fix article-top-contributors-label

---

front/styles/auth/layout/_body.scss
front/styles/auth/layout/_content.scss
front/styles/auth/theme/_auth-footer.scss
front/styles/auth/theme/_auth-header.scss

Original pull request is here -> https://github.com/Wikia/mercury/pull/678

Make footer not overlap content for small viewports

---

server/app.ts
server/facets/api/article.ts

temporary logging to help track down the root cause of some low volume errors on prod

add logging for crumb and result undefined errors

---

config/localSettings.base.ts

Revert "temporarily increase logging level on prod"

---

front/locales/en/auth.json
server/facets/auth/login.ts
server/views/login.hbs

Explained here: https://wikia-inc.atlassian.net/browse/SOC-657
@kenkouot or @bkoval Please also have a look.

Remove 'remember me' code

---

front/styles/main/_wikia-variables.scss
front/styles/main/module/_ads-floor.scss
front/styles/main/module/_ads.scss

We want a new ad product on all skins: Oasis (desktop, tablet) and Mercury (mobile). It's already working on Oasis and to make it working on mobile we needed those style changes in Mercury.
Connected to PR: https://github.com/Wikia/app/pull/6949

ADEN-1676 Floor adhesion on Mercury

---

.gitignore

Ticket: https://wikia-inc.atlassian.net/browse/OPS-6210
The idea is to keep md5 sum of a file and based on that sum remove or not node_modules directory (keep modules or rebuild dependencies).
Code below should be a part of "Execute shell" in Jenkins (before (re)?build dependencies step):
```
#!/usr/bin/env bash
set -e
compute_md5() {
local output="$(openssl md5)"
echo "${output##* }"
}
compare_file() {
local file=$1
local md5="$(compute_md5 < ${file} )"
if [ ! -f ".${file}.md5" ];
then
echo "No information about previous version of ${file}. Removing node_modules directory..."
rm -rf node_modules
echo ${md5} > ".${file}.md5"
elif [[ ${md5} != `cat ".${file}.md5"` ]];
then
echo "New version of ${file}. Removing old node_modules directory..."
rm -rf node_modules
echo ${md5} > ".${file}.md5" …
```

OPS-6210: Jenkins - apply updates to dependencies for tests

---

front/styles/main/module/_comments.scss

I couldn't reproduce the issue here https://wikia-inc.atlassian.net/secure/attachment/59887/Screenshot_2015-04-28-18-26-17.png, but was able to fix the comment button alignment. 
@mklucsarits @kenkouot

HG-614 fixing button styles for article comments

---

front/scripts/mercury/modules/Trackers/GoogleAnalytics.ts

HG 604 Set custom var 8 at track page view time and also check if it is a main page or not

---

front/scripts/main/components/LoginIconComponent.ts
front/scripts/main/components/ShareFeatureComponent.ts
front/scripts/main/mixins/LanguagesMixin.ts

Original Pull Request with comments: https://github.com/Wikia/mercury/pull/727

SOC-695 Adding whitelisting for redirects to the new login flow

---

front/scripts/auth/common/Form.ts

This will check for filled inputs and moved the labels up if necessary.
https://wikia-inc.atlassian.net/browse/SOC-696
@mklucsarits

SOC-696 Fixing Floating Labels bug on pressing "back" button in the browser

---

front/scripts/main/components/FeaturedContentComponent.ts
front/scripts/main/models/MainPageModel.ts
front/templates/main/article.hbs
front/templates/main/components/featured-content.hbs
front/templates/main/components/main-page.hbs
server/facets/api/curatedContent.ts
server/lib/MediaWiki.ts

Refactor the structure of Curated Main Page modules

---

front/scripts/auth/common/Form.ts
front/styles/auth/module/_form-icons.scss
server/views/login.hbs
server/views/signup.hbs

@mklucsarits https://wikia-inc.atlassian.net/browse/SOC-750

SOC-750 Password field should be masked by default

---

config/localSettings.base.ts
config/localSettings.d.ts
server/facets/showArticle.ts
server/views/_layouts/ember-main.hbs
server/views/_partials/optimizely.hbs
server/views/_partials/qualaroo.hbs

CONCF-519 | Implement Qualaroo in Mercury

---

front/scripts/main/mixins/ViewportMixin.ts

Mixin to keep track of viewport.
@rogatty @hakubo @dianafa

Resize mixin

---

front/scripts/main/controllers/ApplicationController.ts
front/scripts/main/controllers/ArticleController.ts
front/templates/main/application.hbs
front/templates/main/article.hbs

https://wikia-inc.atlassian.net/browse/CONCF-506
/cc @bognix @vforge

CONCF-506 Change local branding on curated main pages

---

front/scripts/main/components/LoginIconComponent.ts

adding mobileregressiontesting to the list of wikis for testing purposes.  @bkoval please review.

adding mobileregressiontesting to list of loginmvp wikis

---

front/scripts/main/components/FeaturedContentComponent.ts
front/scripts/main/components/FeaturedContentItemComponent.ts
front/scripts/main/helpers/thumbnailHelper.ts
front/styles/main/component/_featured-content.scss
front/styles/main/component/index.scss
front/templates/main/components/featured-content-item.hbs
front/templates/main/components/featured-content.hbs

https://wikia-inc.atlassian.net/browse/CONCF-510
/cc @bognix @dianafa @vforge

CONCF-510 Featured content MVP

---

front/scripts/main/components/CuratedContentItemComponent.ts
front/styles/main/component/_curated-content.scss
front/templates/main/components/curated-content-item.hbs
front/templates/main/components/curated-content.hbs

Curated content polishing

---

front/scripts/main/components/FeaturedContentComponent.ts

Quick fix for FeaturedContent when leaving main page

---

config/localSettings.base.ts
config/localSettings.d.ts
server/facets/showArticle.ts
server/views/_layouts/ember-main.hbs
server/views/_partials/qualaroo.hbs

CONCF-520 | Send optimizely data to qualaroo

---

front/scripts/main/app.ts
front/scripts/main/models/ArticleModel.ts

CONCF-541 | Use Optimizely test to disable CuratedContent

---

front/scripts/main/views/EditView.ts

Resize textarea when window size or orientation is changed.
/cc @inez

(INT-67) Resize textarea when window size is changed

---

server/views/_helpers/decodeQueryParams.ts
server/views/_helpers/escapeQueryParams.ts
server/views/_layouts/ember-main.hbs
typings/hoek/hoek.d.ts

HG-653 escape query params before inserting into document

---

front/scripts/main/mixins/LoadingSpinnerMixin.ts
front/scripts/main/routes/ApplicationRoute.ts

https://wikia-inc.atlassian.net/browse/HG-666
We were adding multiple callbacks but canceling only a single one. It should be fine now.

HG-666 Fix infinite loading spinner

---

front/scripts/main/models/ArticleModel.ts

https://wikia-inc.atlassian.net/browse/HG-649

HG-649 Don't add adsContext if it's an empty array

---

front/scripts/main/views/ApplicationView.ts
front/scripts/main/views/ArticleView.ts
test/specs/front/scripts/main/views/ApplicationView.js

PollDaddy relies on global variables that don't play nicely with single page apps. In lieu of an elegant solution, we've decided to put a bandaid on it to get it working quickly in mercury.

Hg 618 hacking poll daddy back together again

---

front/scripts/main/views/ArticleView.ts

responding to @rogatty's  comments from https://github.com/Wikia/mercury/pull/815

HG-618 adding error checking

---

front/locales/en/main.json
front/templates/main/edit.hbs

(INT-71) Add i18n for edit page heading and publish button

---

server/app.ts
server/facets/operations/verifyMWHash.ts
server/lib/Caching.ts
server/lib/Utils.ts
tslint.json

I'm tired of writing comments like "Add :void". This will enforce correct typing with tslint.
See https://www.npmjs.com/package/tslint#supported-rules
/cc @hakubo @kenkouot

Add check for call-signature to tslint and fix existing signatures

---

front/scripts/main/models/EditModel.ts
front/scripts/main/views/EditView.ts
front/templates/main/edit.hbs

Simple event on text change for the MVP.
/cc @inez

(INT-68) Activate publish button after content change

---

front/scripts/main/components/CuratedContentComponent.ts
front/scripts/main/components/CuratedContentItemComponent.ts
front/scripts/main/models/CuratedContentModel.ts
front/styles/main/component/_curated-content.scss
front/svg/symbols/main/article-thumb-icon.svg
front/templates/main/components/curated-content-item.hbs
front/templates/main/components/curated-content.hbs
front/templates/main/components/main-page.hbs
server/facets/api/category.ts
server/lib/MediaWiki.ts
server/routes.ts

https://wikia-inc.atlassian.net/browse/CONCF-552

CONCF-552 Categories as Curated Content sections

---

front/locales/en/main.json
front/scripts/main/controllers/EditController.ts
front/scripts/main/models/EditModel.ts

Simple error handling on failed attempts at publishing. We handle a couple of common
errors that would not be resolvable by the anon editing with more specific messages
and otherwise fallback to a generic error message.
/cc @inez

(INT-70) Handle errors on publishing an edit

---

front/scripts/main/router.ts
front/scripts/main/routes/MainPageRoute.ts
front/scripts/main/routes/TestRoute.ts
server/app.ts
server/facets/operations/redirectToRoot.ts
server/routes.ts
typings/hapi/hapi.d.ts

Fixes /wiki redirecting to /wiki/wiki

Hg 668 wiki redirect

---

front/scripts/main/mixins/AdsMixin.ts

https://wikia-inc.atlassian.net/browse/CONCF-550
/cc @Warkot @vforge

CONCF-550 Show pre-footer ad when trending articles and/or videos are present

---

front/scripts/main/components/CuratedContentComponent.ts
front/scripts/main/models/CuratedContentModel.ts

https://wikia-inc.atlassian.net/browse/CONCF-551
MW PR: https://github.com/Wikia/app/pull/7303
/cc @vforge @Warkot

CONCF-551 Treat top level of curated content as a regular section

---

front/scripts/main/app.ts
front/scripts/mercury/modules/Trackers/UniversalAnalytics.ts
front/scripts/mercury/utils/variantTesting.ts

https://wikia-inc.atlassian.net/browse/CONCF-582
/cc @rogatty @Warkot @hakubo

CONCF-582 | Tell Optimizely to use UA Dimensions

---

front/locales/de/auth.json
front/locales/en/auth.json
front/locales/es/auth.json
front/locales/fi/auth.json
front/locales/fr/auth.json
front/locales/it/auth.json
front/locales/ja/auth.json
front/locales/ko/auth.json
front/locales/nl/auth.json
front/locales/pl/auth.json
front/locales/pt-br/auth.json
front/locales/pt-pt/auth.json
front/locales/ru/auth.json
front/locales/sv-se/auth.json
front/locales/vi/auth.json
front/locales/zh-hans/auth.json
front/locales/zh-tw/auth.json
front/styles/auth/module/_landing-page.scss
server/facets/auth/join.ts
server/views/auth-landing-page.hbs

https://wikia-inc.atlassian.net/browse/SOC-818

SOC-818 | Auth landing page - Change CTA message + move some items

---

front/styles/main/component/_curated-content.scss

https://wikia-inc.atlassian.net/browse/CONCF-603

CONCF-603 | Fix for text wrapping in curated content on curated main pages

---

front/scripts/main/mixins/AdsMixin.ts

https://wikia-inc.atlassian.net/browse/ADEN-1773

ADEN-1773 Test Loading Incremental Ads on long pages

---

bower.json

https://wikia-inc.atlassian.net/browse/HG-718
https://github.com/emberjs/ember.js/releases/tag/v1.12.1

Update Ember to 1.12.1

---

front/scripts/main/components/LocalWikiaSearchComponent.ts
front/scripts/main/routes/ApplicationRoute.ts
front/scripts/mercury/utils/articleLink.ts
front/scripts/mercury/utils/string.ts
test/specs/front/scripts/mercury/utils/string.js

https://wikia-inc.atlassian.net/browse/HG-677

encode the whole string instead of just the first char

---

config/localSettings.base.ts
package.json
server/lib/Article.ts
server/lib/Logger.ts

problems with undefined url when running on sandbox-mercury

HG-712 mercury_ads_js now pulling from correct wiki domain

---

server/facets/api/article.ts
server/lib/Caching.ts
server/lib/MediaWiki.ts

https://wikia-inc.atlassian.net/browse/HG-686

HG-686 removed namespace specifier from random page query for community wiki

---

tasks/changelog-view.sh

Looking for changes will be now from last release tag instead of origin/master

change default destination

---

front/scripts/main/components/LocalNavMenuComponent.ts

it will show up in GA as 'randomArticle'

HG-750 - added GA tracking to random article link

---

front/scripts/main/models/ArticleModel.ts
server/facets/showArticle.ts
server/views/_layouts/ember-main.hbs

https://wikia-inc.atlassian.net/browse/CONCF-509
ping @hakubo @rogatty 
related PR: https://github.com/Wikia/app/pull/7512

CONCF-509 move description to article details

---

server/facets/api/article.ts
server/facets/showArticle.ts

Set cache control headers to private if session cookie is present

---

front/scripts/main/components/LoginIconComponent.ts
front/templates/main/components/login-icon.hbs

Revert "SOC-805 Create CTA to New Login Flow on Wikiamobile"

---

front/scripts/auth/common/BirthdateInput.ts
front/styles/auth/base/_input.scss

@kvas-damian @rafalkalinski https://wikia-inc.atlassian.net/browse/SOC-878
This ticket was filed to fix the state on a placeholding input type=date, but I added an active state on the new date field, so the PR is targeted at SOC-480.

SOC-878 Adding active state to birthdate field

---

front/scripts/main/views/ApplicationView.ts

https://wikia-inc.atlassian.net/browse/DAT-2897
@rogatty

DAT-2897 handle article references

---

front/scripts/main/models/CuratedContentModel.ts

CONCF-608 encode category and section name before sending to API

---

server/lib/MediaWiki.ts

Tested on devbox with cookies disabled, and it works (unique pages). If you run dev, you get the same page every request.

HG-686 - added cache-buster for internal cache for random page request

---

server/facets/auth/authView.ts
server/facets/auth/join.ts
server/facets/auth/login.ts
server/facets/auth/signup.ts
server/views/_layouts/auth.hbs

https://wikia-inc.atlassian.net/browse/SOC-895

SOC-895 | Introduce AuthView + canonicalUrl for Auth pages

---

gulp/options/prod.js
server/lib/Article.ts

Replace /front string in templates with cdn path

---

server/facets/auth/login.ts

Always obtain LoginViewContext for /login

---

front/scripts/auth/login/Login.ts
server/app.ts
server/facets/auth/logout.ts
server/facets/operations/prepareArticleData.ts
server/lib/HeliosSession.ts
server/routes.ts

https://wikia-inc.atlassian.net/browse/SOC-913
+ small cleanup in routes.ts

SOC-913 | Retire wikicitiesUserID

---

server/facets/auth/signup.ts

@kvas-damian Since Helios team changed it :)

Change helios url for reg

---

front/scripts/main/mixins/RouteActionsMixin.ts
front/scripts/main/router.ts
front/scripts/main/routes/ArticleRoute.ts
front/scripts/main/routes/MainPageRoute.ts

https://wikia-inc.atlassian.net/browse/CONCF-711

CONCF-711 | As a Mercury user I would like to have main page's URLs cut after / so I can access them easily

---

front/scripts/main/views/ArticleView.ts

Now handles links in tables correctly.

HG-772 - fixed table bug

---

front/scripts/main/views/ArticleView.ts

There are so many commits because I had to test on sandbox.

HG-782 - added state check back

---

server/facets/auth/register.ts
server/facets/showArticle.ts
server/lib/AuthUtils.ts
server/lib/DateUtils.ts
server/routes.ts

While running server there was several messages in the console.
@rogatty @bkoval

Fix small typos on dev

---

front/scripts/main/components/FeaturedContentComponent.ts
front/scripts/main/components/FeaturedContentVariation1Component.ts
front/scripts/main/components/FeaturedContentVariation2Component.ts
front/scripts/main/components/FeaturedContentVariation3Component.ts

https://wikia-inc.atlassian.net/browse/CONCF-768

CONCF-768 add optimizely events for featured content

---

server/views/register.hbs

@mklucsarits @lizlux https://wikia-inc.atlassian.net/browse/SOC-1005

SOC-1005 Trigger number keyboard when b-date input focused

---

front/styles/main/module/article/_portable-infobox.scss

https://wikia-inc.atlassian.net/browse/DAT-2978

add minimal height

---

front/scripts/main/components/ImageMediaComponent.ts
front/scripts/main/components/MediaComponent.ts
front/scripts/main/components/VideoMediaComponent.ts
front/templates/main/components/video-media.hbs

https://wikia-inc.atlassian.net/browse/DAT-2973
UWAGA!!!
Has to be pushed together with the app part: https://github.com/Wikia/app/pull/7768

DAT-2973 hide caption for videos in infoboxes

---

front/scripts/main/components/CuratedContentComponent.ts
front/scripts/main/components/TrendingArticlesItemComponent.ts
front/scripts/main/components/TrendingVideosItemComponent.ts
front/scripts/main/mixins/FeaturedContentMixin.ts
front/scripts/main/models/CuratedContentModel.ts
test/specs/front/scripts/main/components/CuratedContentComponent.js
test/specs/front/scripts/main/components/CuratedContentItemComponent.js
test/specs/front/scripts/main/components/FeaturedContentItemComponent.js
test/specs/front/scripts/main/components/MainPageComponent.js
test/specs/front/scripts/main/components/TrendingArticlesItemComponent.js
test/specs/front/scripts/main/components/TrendingVideosComponent.js
test/specs/front/scripts/main/components/TrendingVideosItemComponent.js
test/specs/front/scripts/main/mixins/AdsMixin.js
test/specs/front/scripts/main/mixins/FeaturedContentMixin.js
test/specs/front/scripts/main/mixins/ThirdsClickMixin.js
test/specs/front/scripts/main/models/CuratedContentModel.js
test/specs/front/scripts/main/routes/MainPageCategoryRoute.js
test/specs/front/scripts/main/routes/MainPageRoute.js
test/specs/front/scripts/main/routes/MainPageSectionRoute.js

https://wikia-inc.atlassian.net/browse/CONCF-796
Added 24 unit tests related to Curated Main Pages and fixed some minor issues that I bumped into.
/cc @Warkot @bognix @vforge

CONCF-796 Unit tests for Curated Main Pages

---

front/scripts/main/routes/ArticleRoute.ts

Ticket: https://wikia-inc.atlassian.net/browse/CONCF-735

CONCF-735 | Handle redirections from MercuryApi

---

front/scripts/main/routes/ArticleRoute.ts

After #1046 was merged this comment is outdated.

CONCF-735 Remove obsolete TODO

---

front/styles/main/module/edit/_addphoto.scss
front/styles/main/module/edit/_edit-common.scss
front/styles/main/module/edit/_edit.scss

Edit and photo icon positions were optimized for h2 section header only. Fixed styling so that those icons are positioned correctly in any size of headers.

INT-140: Edit/Photo icons positioning fix for section header.

---

front/scripts/main/mixins/FeaturedContentMixin.ts

https://wikia-inc.atlassian.net/browse/CONCF-852

CONCF-852 Stop failing when FeaturedContentMixin has undefined model

---

front/scripts/auth/login/Login.ts
front/scripts/auth/signup/SignupForm.ts
front/scripts/auth/tracking.ts

@rogatty @jsutterfield https://wikia-inc.atlassian.net/browse/SOC-1017

SOC-1017 Enable /both/ as default trackingMethod setting for New Auth

---

front/scripts/auth/tracking.ts

Addressing CR comment in #1051 that was missed before merge :)

Use M.provide instead of creating new property on Mercury object

---

server/facets/operations/processCuratedContentData.ts

https://wikia-inc.atlassian.net/browse/CONCF-857
This was missed in https://github.com/Wikia/mercury/pull/1040.

CONCF-857 Add asyncArticle to curated content routes

---

gulp/tasks/watch.js

HG-810 | run build-combined when ts file changes

---

front/styles/main/module/article/_portable-infobox.scss

https://wikia-inc.atlassian.net/browse/DAT-3001

DAT-3001 stretch only main infobox image

---

front/scripts/main/models/CuratedContentModel.ts

https://wikia-inc.atlassian.net/browse/CONCF-896

CONCF-896 | handle categories with special characters

---

front/scripts/main/models/CuratedContentModel.ts

https://wikia-inc.atlassian.net/browse/CONCF-896

CONCF-896 | catch when decodeURIComponent throws

---

front/scripts/main/models/CuratedContentModel.ts

https://github.com/Wikia/mercury/pull/1087

[HOTFIX] CONCF-896 | catch when decodeURIComponent throws

---

front/scripts/main/routes/ArticleRoute.ts

Jira: https://wikia-inc.atlassian.net/browse/CONCF-889

CONCF-889 | As a user I would like to be able to go back from the Mercury main page

---

front/scripts/main/models/CuratedContentModel.ts

CONCF-917 fix decoding urls for subcategories

---

server/facets/auth/authView.ts
server/views/_layouts/auth.hbs

https://wikia-inc.atlassian.net/browse/SOC-1091
ping @bkoval @rafalkalinski

SOC-1089 | Add optimizely on auth pages

---

front/scripts/auth/common/BirthdateInput.ts

Add event as explicit method param

---

front/scripts/main/routes/MainPageIndexRoute.ts

https://wikia-inc.atlassian.net/browse/CONCF-951

CONCF-951 | reset visibility state for old main pages

---

front/scripts/auth/tracking.ts

@jsutterfield @mklucsarits https://wikia-inc.atlassian.net/browse/SOC-932

SOC-932 Track clicks on Facebook Connect button

---

front/scripts/mercury/modules/Trackers/Perf.ts
gulp/tasks/build-views.js

Moved the flag to the right object and it works not - `logged_in` data is being sent.

HG-769 moving logged_in flag

---

config/localSettings.base.ts

Removing unused Helios params from localSettings

---

config/localSettings.d.ts

Remove unused Helios params from typings

---

front/styles/auth/module/_forms.scss

@rafalkalinski Let's speed up labels to feel more native :)

Speeding up floating labels to look more native

---

test/helpers/startEmberApp.js

https://wikia-inc.atlassian.net/browse/HG-838
/cc @hakubo @lizlux @mari-mcmurtrie

HG-838 Don't display deprecations when running unit tests

---

front/scripts/main/components/ImageMediaComponent.ts
front/scripts/main/components/InfoboxHeroImageMediaComponent.ts
front/styles/main/module/article/_media.scss
front/templates/main/components/image-media.hbs

https://wikia-inc.atlassian.net/browse/DAT-3048
app part: https://github.com/Wikia/app/pull/8012

DAT-3048 Remove chevrons and captions from linked icons

---

front/scripts/main/helpers/truncate.ts

Truncate helper error handling

---

gulp/tasks/build-views.js
gulp/tasks/combine-svgs.js
server/views/_layouts/ember-main.hbs

Revert "HG-788 - replace inline SVG sprite with requested asset"

---

server/facets/auth/register.ts

Break line in registration controller

---

front/scripts/main/components/CuratedContentEditorItemFormComponent.ts

CONCF-977 Fix thumbnails in Curated Content Tool

---

front/scripts/main/models/CuratedContentEditorModel.ts

Initialize featured and optional sections with correct data

---

front/scripts/main/components/PortableInfoboxComponent.ts
front/styles/main/module/article/_portable-infobox-old.scss
front/styles/main/module/article/_portable-infobox.scss
front/styles/main/module/index.scss
front/templates/main/components/portable-infobox.hbs

Please do not merge!!!!!!!!
Should be released together with https://github.com/Wikia/app/pull/7967

Dat 3006 - Portable Infobox markup and styles cleanup

---

front/scripts/main/components/CuratedContentEditorItemFormComponent.ts
front/templates/main/components/curated-content-editor-item-form.hbs

https://wikia-inc.atlassian.net/browse/CONCF-1032
/cc @bognix @hakubo

CONCF-1032 Fix titleObserver being called when not supposed to

---

CHANGELOG.md
front/scripts/main/components/ArticleContentComponent.ts
front/scripts/main/components/ArticleContributionComponent.ts
front/scripts/main/components/ArticleWrapperComponent.ts
front/scripts/main/components/FileInputComponent.ts
front/styles/main/module/edit/_edit-common.scss
front/styles/main/module/edit/_edit.scss
front/templates/main/components/article-contribution.hbs
front/templates/main/components/article-wrapper.hbs
front/templates/main/components/file-input.hbs

INT-149 was reverted from dev because table of contents was gone. This is for the fix.

INT-149-2: Fix for 'table of contents' disappearing in INT-149 branch.

---

config/localSettings.base.ts
front/scripts/main/models/DiscussionIndexModel.ts
front/scripts/main/models/ForumModel.ts
front/scripts/main/models/PostModel.ts

https://wikia-inc.atlassian.net/browse/SOC-1169

SOC-1169 Update the API URLs to their new location

---

front/scripts/main/routes/ApplicationRoute.ts
front/scripts/mercury/modules/Ads.ts

Created clean up task: [ADEN-2347](https://wikia-inc.atlassian.net/browse/ADEN-2347)

ADEN-2289 Added temporary method to keep working the interstitial

---

front/scripts/auth/common/Cookie.ts
front/scripts/auth/signup/SignupForm.ts

https://wikia-inc.atlassian.net/browse/SOC-601

SOC-601 | Set cookie on successful account registration

---

config/localSettings.base.ts
config/localSettings.d.ts
config/localSettings.dev.ts
config/localSettings.example.ts
server/facets/auth/authView.ts
server/facets/auth/join.ts
server/facets/auth/register.ts
server/facets/auth/signin.ts
server/facets/operations/prepareArticleData.ts
server/facets/operations/prepareMainPageData.ts
server/facets/operations/processCuratedContentData.ts
server/facets/showApplication.ts
server/facets/showArticle.ts
server/lib/AuthUtils.ts
server/lib/HeliosSession.ts
server/views/_layouts/ember-main.hbs
server/views/_partials/open-graph-tags.hbs

It's time to separate ```localSettings``` for dev environment.
**Action required for devs:**
In order to use dev ```localSettings``` you need to update your ```localSettings.ts``` file to target new settings file.
Ping @rogatty @bkoval @rafalkalinski

Separate localSettings file for dev environment

---

server/facets/api/articleComments.ts
server/facets/auth/authView.ts

@rogatty @tomasznapieralski @kvas-damian This was making build step shout at me in the console :)

Adding missing semicolons

---

front/scripts/main/components/CuratedContentEditorImageCropComponent.ts

/cc @hakubo @rogatty 
see https://github.com/fengyuanchen/cropper/issues/421#issuecomment-131293395
and https://github.com/fengyuanchen/cropper/pull/429

CONCF-1047 | Add re-initialization on resize to cropper tool

---

config/localSettings.dev.ts

@rogatty @hakubo @bognix @kvas-damian 
Let's make use of a new config architecture to revert your revert of this change :)

Setting :7000 as a default port on dev env

---

config/localSettings.base.ts
config/localSettings.d.ts
server/facets/auth/authView.ts
server/facets/auth/join.ts

Moving regex patterns to localSettings and tslint-based fixes

---

front/locales/en/main.json
front/templates/main/components/article-wrapper.hbs
front/templates/main/components/main-page.hbs

/cc @vforge @tomasznapieralski

CONCF-1087 show edit main page on wikis without curated content

---

config/localSettings.base.ts

fixing-typo

---

front/scripts/main/components/ForumWrapperComponent.ts
front/scripts/main/models/DiscussionForumModel.ts
front/scripts/main/routes/DiscussionForumRoute.ts
front/scripts/main/routes/DiscussionPostRoute.ts
front/styles/main/module/_discussion.scss
front/templates/main/components/forum-wrapper.hbs
front/templates/main/discussion/forum.hbs

https://wikia-inc.atlassian.net/browse/HG-850

HG-850 Implemented inifinite scroll for post list page

---

front/locales/en/main.json
front/scripts/main/mixins/CuratedContentEditorSortableItemsMixin.ts
front/scripts/main/models/CuratedContentEditorModel.ts
front/scripts/main/routes/CuratedContentEditorRoute.ts

Xw 69 show prompt on back click

---

front/styles/main/module/_ads.scss
front/templates/main/application.hbs
front/templates/main/article.hbs

Revert "Move ads out of application template"

---

front/scripts/main/components/CuratedContentEditorImageSearchComponent.ts
front/scripts/main/components/CuratedContentEditorItemFormComponent.ts
front/scripts/main/mixins/IEIFrameFocusFixMixin.ts

XW-75 set focus on iframe when entering view with inputs

---

server/lib/HeliosSession.ts

Fix helios session

---

front/styles/main/module/article/_portable-infobox.scss

https://github.com/Wikia/app/pull/8341

DAT-3181 add styles for horizontal group

---

front/scripts/main/components/ShareFeatureComponent.ts

@rogatty @mklucsarits @kvas-damian 
https://wikia-inc.atlassian.net/browse/SOC-1251
Should be good enough for a P2 hotfix.

SOC-1251 | Bringing back sharedUrl

---

front/scripts/main/components/MainPageComponent.ts
front/scripts/main/mixins/MainPageRouteMixin.ts
front/scripts/main/routes/MainPageCategoryRoute.ts
front/scripts/main/routes/MainPageRoute.ts
front/scripts/main/routes/MainPageSectionRoute.ts
test/specs/front/scripts/main/components/MainPageComponent.js

https://wikia-inc.atlassian.net/browse/XW-242

XW-242 Fix Curated Main Page navigation

---

front/scripts/main/mixins/MainPageRouteMixin.ts
front/scripts/main/routes/MainPageRoute.ts

XW-242 move scrollTop to mixin

---

front/scripts/main/components/ArticleWrapperComponent.ts
front/scripts/main/components/MainPageComponent.ts

To be released on Thursday: 10th Sept

XW-9 | enable Curated Content Editor site wide

---

front/scripts/main/components/ArticleContentComponent.ts
front/styles/main/module/_wikia-widget.scss
front/styles/main/module/index.scss

https://wikia-inc.atlassian.net/browse/XW-204

XW-204 Unwrap Wikia widgets

---

config/localSettings.base.ts
front/scripts/main/models/DiscussionForumModel.ts
front/scripts/main/models/DiscussionIndexModel.ts
front/scripts/main/models/DiscussionPostModel.ts
server/lib/Utils.ts
server/views/_layouts/ember-main.hbs

/CC @kenkouot @mklucsarits @garthwebb 
https://wikia-inc.atlassian.net/browse/SOC-1279

SOC-1279 Expose servicesDomain to ember and use for discussion api url

---

server/facets/auth/BirthdateInput.ts

... to calm tslint down again, sorry for that.

Maintenance | using dot operator for fallback date config

---

homepage/config/localSettings.base.js
homepage/config/localSettings.example.js
homepage/package.json
homepage/server/index.js
homepage/server/logger.js

Set up bunyan with bunyan-syslog and bunyan-prettystream for hapi.

Add bunyan logger for Japan homepage (console and syslog)

---

homepage/server/facets/logout.js
homepage/server/routes.js
homepage/server/util.js
homepage/server/views/_partials/userinfo.html

Unstate access_token when logging out.
Logging for access_token validation and user name lookup.

INT-136: Fixes for logout for Japan HP

---

front/scripts/mercury/modules/Ads.ts
test/specs/front/scripts/mercury/modules/Ads.js

Added new method pushSlotToQueue to refresh ad without reloading whole AdEngine

ADEN-2435 Added new method pushSlotToQueue

---

homepage/server/auth.js
homepage/server/util.js

Due to an issue with trailing '/' not being handled correctly, user id to user name lookup for logged in users was not working.

Japan Homepage: Fix for user name not showing after logging in

---

front/scripts/main/components/ArticleContentComponent.ts
front/scripts/main/components/WidgetPolldaddyComponent.ts
front/templates/main/components/widget-polldaddy.hbs

https://wikia-inc.atlassian.net/browse/XW-199
https://github.com/Wikia/app/pull/8513/files

XW-199 | Add Polldaddy widget

---

README.md
config/localSettings.base.ts
config/localSettings.d.ts
front/scripts/mercury/utils/variantTesting.ts
gulp/utils/environment.js
homepage/gulp/utils/environment.js
server/facets/api/article.ts
server/facets/api/articleComments.ts
server/facets/api/mainPageCategory.ts
server/facets/api/mainPageSection.ts
server/facets/api/search.ts
server/facets/editorPreview.ts
server/facets/operations/proxyMW.ts
server/facets/showApplication.ts
server/facets/showArticle.ts
server/facets/showMainPageCategory.ts
server/facets/showMainPageSection.ts
server/lib/MainPage.ts
server/lib/Utils.ts
test/specs/server/lib/Utils.js

Some requests on Mercury were hitting production instead of preview.
Root cause of this issue was WIKIA_ENVIRONMENT which was set to prod on staging-s3
Chef change: https://github.com/Wikia/chef-repo/pull/6558

XW-239 Handle preview as one of possible envs in mercury

---

bower.json
front/scripts/main/components/LightboxImageComponent.ts
test/specs/front/scripts/main/components/MainPageComponent.js

https://wikia-inc.atlassian.net/browse/XW-244

XW-244 update ember to 1.13.10

---

front/scripts/main/components/AlertNotificationsComponent.ts
front/scripts/main/mixins/AlertNotificationsMixin.ts
front/scripts/main/routes/ApplicationRoute.ts
front/scripts/main/routes/MainPageCategoryRoute.ts
front/scripts/main/routes/MainPageSectionRoute.ts
server/facets/operations/processCuratedContentData.ts

https://wikia-inc.atlassian.net/browse/XW-251

XW-251 | Show a message when user opened a section/category that does not exist

---

front/locales/en/main.json
front/scripts/main/components/InfoboxBuilderItemDataComponent.ts
front/scripts/main/components/InfoboxBuilderItemImageComponent.ts
front/scripts/main/components/InfoboxBuilderItemTitleComponent.ts
front/scripts/main/components/InfoboxBuilderWrapperComponent.ts
front/scripts/main/components/infoboxBuilderEditItemComponent.ts
front/scripts/main/mixins/InfoboxBuilderItemMixin.ts
front/scripts/main/models/InfoboxBuilderModel.ts
front/scripts/main/routes/InfoboxBuilderRoute.ts
front/styles/main/component/_infobox-builder.scss
front/templates/main/components/infobox-builder-edit-item.hbs
front/templates/main/components/infobox-builder-item-data.hbs
front/templates/main/components/infobox-builder-item-image.hbs
front/templates/main/components/infobox-builder-item-title.hbs
front/templates/main/infobox-builder.hbs

https://wikia-inc.atlassian.net/browse/DAT-2994

Dat 2994 - add remove item functionality to Infobox Builder UI

---

front/templates/main/discussion/post.hbs

SOC-1289 follow-up | Removing discussion hero unit from post-detail page

---

bower.json

Bumping SG version after fixes to top-bar styles

Hg 888 Style guide version

---

tslint.json

as per
https://github.com/Wikia/guidelines/pull/91

allow for trailing comma in ts

---

front/locales/en/main.json
front/scripts/main/components/CuratedContentEditorRowComponent.ts
front/scripts/main/components/CuratedContentEditorSectionComponent.ts
front/scripts/main/mixins/CuratedContentEditorLabelsMixin.ts
front/templates/main/components/curated-content-editor-row.hbs
front/templates/main/components/curated-content-editor-section.hbs

https://wikia-inc.atlassian.net/browse/XW-424

XW-424 | Curated Content Tool section item count singular/plural label fix

---

front/locales/en/main.json
front/scripts/main/components/infoboxBuilderEditItemComponent.ts
front/scripts/main/mixins/InfoboxBuilderItemMixin.ts
front/scripts/main/models/InfoboxBuilderModel.ts
front/scripts/main/routes/InfoboxBuilderRoute.ts
front/templates/main/components/infobox-builder-edit-item.hbs
front/templates/main/infobox-builder.hbs
test/specs/front/scripts/main/models/InfoboxBuilderModel.js

https://wikia-inc.atlassian.net/browse/DAT-2996

Dat 2996 - add item reordering functionality to infobox builder

---

front/scripts/main/components/CuratedContentItemComponent.ts
front/scripts/main/components/FeaturedContentItemComponent.ts
front/scripts/main/components/ImageMediaComponent.ts
front/scripts/main/components/LightboxImageComponent.ts
front/scripts/main/components/LightboxMediaComponent.ts
front/scripts/main/components/SmartBannerComponent.ts
front/scripts/main/components/TrendingArticlesItemComponent.ts
front/scripts/main/components/TrendingVideosItemComponent.ts
front/scripts/main/mixins/HeadroomMixin.ts
front/templates/main/components/curated-content-item.hbs
front/templates/main/components/image-media.hbs
front/templates/main/components/smart-banner.hbs
front/templates/main/components/trending-articles-item.hbs
front/templates/main/components/trending-videos-item.hbs
front/templates/main/components/video-media.hbs
test/specs/front/scripts/main/components/TrendingArticlesItemComponent.js

https://wikia-inc.atlassian.net/browse/XW-347

XW-347 | Don't modify element twice before render

---

server/lib/Utils.ts

Added missing type.
/cc @rogatty @nandy-andy

Add missing type to Utils.ts:clearHost

---

server/facets/editorPreview.ts
server/facets/showApplication.ts
server/facets/showArticle.ts
server/facets/showMainPageCategory.ts
server/facets/showMainPageSection.ts
server/lib/Article.ts
server/lib/MediaWiki.ts
typings/mercury/mercury-server.d.ts

https://wikia-inc.atlassian.net/browse/XW-417

Xw 417 | pass staging to MWRequest

---

bower.json

I had to bump the style guide version again to publish the latest changes to the top-nav width at different screen sizes.

pulling in updated nav styles

---

front/scripts/main/mixins/HeadroomMixin.ts

Fix for P2 https://wikia-inc.atlassian.net/browse/XW-442

XW-442 | Fire smartBannerVisibleObserver on willInsertElement

---

front/scripts/main/components/ArticleContributionComponent.ts
front/scripts/main/components/WikiaMapComponent.ts

https://wikia-inc.atlassian.net/browse/XW-435

XW-435 Use layoutName instead of deprecated templateName

---

.editorconfig

Just because editing language files right now can be improved.

Add **.json to .editorconfig

---

server/facets/editorPreview.ts
server/facets/showApplication.ts
server/facets/showArticle.ts
server/facets/showMainPageCategory.ts
server/facets/showMainPageSection.ts
server/lib/Article.ts
server/lib/MediaWiki.ts
typings/mercury/mercury-server.d.ts

https://wikia-inc.atlassian.net/browse/XW-417
This reverts commit 65c4c8b96d2cfc68adfe2272e37fe48b9c323ed3

XW-417 Revert hotfix as there is a proper fix now on VCL

---

front/styles/main/component/_discussion-contributors.scss
front/styles/main/component/_user-avatar.scss

/CC @bkoval @vforge 
https://wikia-inc.atlassian.net/browse/SOC-1371

SOC-1371 Replace inline styling per flipcss recommendation

---

front/scripts/main/components/ArticleContentComponent.ts
front/scripts/main/components/InfoboxImageMediaComponent.ts
front/scripts/main/components/MediaComponent.ts

https://wikia-inc.atlassian.net/browse/DAT-3294
Do not merge without app part!!! https://github.com/Wikia/app/pull/8614

DAT-3294 add infobox-hero-image context handling

---

front/scripts/main/models/ArticleModel.ts

We would like to have article categories in ads context

ADEN-2476 | Expose article categories to adsContext

---

front/scripts/main/components/CuratedContentEditorItemFormComponent.ts

https://wikia-inc.atlassian.net/browse/XW-472

XW-472 rename AddPhotoModel to ArticleAddPhotoModel

---

front/scripts/main/models/CuratedContentEditorItemModel.ts

https://wikia-inc.atlassian.net/browse/XW-422
PR in app: https://github.com/Wikia/app/pull/8640

XW-422 send data using post method

---

bower.json

PR was merged to https://github.com/chriswessels/ember-hammer, 1.0.2 tag was created. No need to use my fork anymore.

Use ember-hammer upstream

---

bower.json

Bumping after a snafu with the style guide repo release

bumping style guide version

---

README.md
config/localSettings.example.ts

Load dev setting on devboxes at default
https://wikia-inc.atlassian.net/browse/MAIN-5471
Ping @rogatty @gabrys

MAIN-5471 | Load dev config on devboxes at default

---

front/scripts/main/components/SideNavComponent.ts
front/scripts/main/controllers/SearchResultsController.ts
front/scripts/main/routes/ApplicationRoute.ts
front/scripts/main/routes/SearchResultsRoute.ts
front/templates/main/searchResults.hbs

Code to enable showing search results in Mercury via Google Custom Search.
We do this as an A/B test.
Also includes code to make sure the search is limited to the active community.

INT-195: A/B test for Google Custom Search integration

---

homepage/gulp/tasks/sass.js

Options for minimizing css were not set correctly in the sass gulp task.

INT-213: Minify css for production for Japan HP

---

front/locales/de/main.json
front/locales/en/main.json
front/locales/es-es/main.json
front/locales/es/main.json
front/locales/fi/main.json
front/locales/fr/main.json
front/locales/it/main.json
front/locales/ja/main.json
front/locales/ko/main.json
front/locales/nl/main.json
front/locales/pl/main.json
front/locales/pt-br/main.json
front/locales/pt-pt/main.json
front/locales/pt/main.json
front/locales/ru/main.json
front/locales/sv-se/main.json
front/locales/vi/main.json
front/locales/zh-TW/main.json
front/locales/zh-cn/main.json
front/locales/zh-hans/main.json
front/locales/zh/main.json
front/scripts/main/components/LocalWikiaSearchComponent.ts
front/templates/main/components/local-wikia-search.hbs

https://wikia-inc.atlassian.net/browse/XW-289
Related PR: https://github.com/Wikia/selenium-tests/pull/899

XW-289 remove showEmptyMesssage in search suggestions

---

front/scripts/main/components/LocalNavMenuComponent.ts

https://wikia-inc.atlassian.net/browse/XW-432
Related PR: https://github.com/Wikia/app/pull/8713

XW-432 flatten structure of navigation passed from MercuryApiController

---

front/scripts/main/app.ts
server/facets/showArticle.ts
server/lib/Utils.ts
server/views/_layouts/ember-main.hbs
server/views/_partials/optimizely.hbs

https://wikia-inc.atlassian.net/browse/XW-252

XW-252 | load optimizely after ember starts

---

front/scripts/mercury/modules/Ads.ts

We need to know when mercury is fully loaded and has proper ad context set, so here is implementation which starts queue with onLoad callbacks.

ADEN-2468 Add mercury onLoad listener

---

config/localSettings.base.ts

@garthwebb @mklucsarits @rafalkalinski Let's have discussions enabled on staging so we can test there as well.

Maintenance | Enable discussion feature on all non-prod environments

---

front/scripts/main/models/DiscussionPostModel.ts

@armonr @rafalkalinski @kvas-damian https://wikia-inc.atlassian.net/browse/SOC-1469

SOC-1469 | Iterate over replies only if they exist

---

front/scripts/main/components/ArticleContentComponent.ts
front/scripts/main/components/GalleryMediaComponent.ts
front/scripts/main/components/InfoboxImageCollectionComponent.ts
front/styles/main/module/article/_portable-infobox.scss
front/templates/main/components/infobox-image-collection.hbs
test/specs/front/scripts/main/components/InfoboxImageCollectionComponent.js

This is based off of https://github.com/Wikia/app/tree/DAT-3340
Tested here: http://visualeditor.paulo.wikia-dev.com/wiki/1383649460634

VE 1960: Mobile rendering of image collections

---

homepage/front/styles/component/_details.scss
homepage/front/styles/component/_nav.scss

Global nav should be fixed to top of screen in desktop mode.

INT-234: Fixed position for Japan homepage nav on desktop

---

homepage/front/styles/component/_nav.scss
homepage/server/static/strings.json
homepage/server/util.js
homepage/server/views/_partials/nav.hbs
homepage/server/views/_partials/signin.hbs
homepage/server/views/_partials/userinfo.hbs

Add a button to the nav in desktop mode that links to the existing create a wikia flow (http://www.wikia.com/Special:CreateNewWiki?uselang=ja)

INT-230: Add Create a wikia to nav (desktop only) for Japan homepage

---

front/templates/main/components/infobox-image-collection.hbs

Restructure media in collection so the container is the clickable element

VE-1998: Make sure article videos are clickable

---

front/scripts/main/components/ArticleContentComponent.ts
front/scripts/main/components/InfoboxImageCollectionComponent.ts
front/styles/main/module/article/_portable-infobox.scss

This PR also introduces code that fixes VE-2001 due to setting visible=true

VE-1999: Change image crop mode on portrait images

---

front/scripts/main/models/DiscussionPostModel.ts

@bkoval  @kvas-damian  please CR

SOC-1174-fix | Fixed 404 after hitting view older replays button

---

front/scripts/main/components/ArticleWrapperComponent.ts

https://wikia-inc.atlassian.net/browse/XW-618
https://github.com/Wikia/mercury/pull/1558

[HOTFIX] XW-618 Fix page view tracking

---

front/scripts/main/components/ArticleWrapperComponent.ts

https://wikia-inc.atlassian.net/browse/XW-618

XW-618 Fix page view tracking

---

.eslintignore
.eslintrc
front/.eslintrc

Create `.eslintignore` and tweak up `.eslint` so you can run `eslint .` better.
/cc @bognix @hakubo

Create .eslintignore; add more globals

---

front/locales/pl/auth-front.json
front/locales/pl/auth.json
front/locales/zh/auth-front.json

Fresh translations for the auth project.
@Warkot @armonr Please take a look :)

i18n | New translations for auth and auth-front

---

front/scripts/main/components/WikiaFooterComponent.ts
front/scripts/mercury/utils/domain.ts
test/specs/front/scripts/main/components/WikiaFooterComponent.js
test/specs/front/scripts/mercury/utils/domain.js

https://wikia-inc.atlassian.net/browse/XW-547
:email: carbon copy: @hakubo @justnpT @bkoval

XW-547 | 'Full site' option persistent per session

---

front/locales/de/main.json
front/locales/es/main.json
front/locales/fi/main.json
front/locales/fr/main.json
front/locales/it/main.json
front/locales/ja/main.json
front/locales/ko/main.json
front/locales/nl/main.json
front/locales/pl/main.json
front/locales/pt-pt/main.json
front/locales/pt/main.json
front/locales/ru/main.json
front/locales/sv-se/main.json
front/locales/vi/main.json
front/locales/zh-hans/main.json
front/locales/zh/main.json

@rafalkalinski @Warkot 
https://wikia-inc.atlassian.net/browse/SOC-1459
This should also do the trick for
https://wikia-inc.atlassian.net/browse/SOC-1531

SOC-1459 | Translations for new Discussion strings

---

homepage/front/scripts/main/globals.ts

Get front end globals as a json file with ajax call wrapped in promise.

INT-217: Use promise to get globals

---

.eslintignore
.eslintrc

/cc @bognix @hakubo @tomasznapieralski

Tweak ESLint - fix typo, add more to .eslintignore

---

front/scripts/main/routes/CuratedContentEditorRoute.js
front/scripts/main/routes/CuratedContentEditorSectionAddRoute.js
front/scripts/main/routes/CuratedContentEditorSectionIndexRoute.js
front/scripts/main/routes/CuratedContentEditorSectionRoute.js

https://wikia-inc.atlassian.net/browse/XW-651
Auto formatting was broken in WebStorm 10, it's fixed in WebStorm 11.
/cc @vforge

XW-651 Fix formatting in ES6 files

---

front/templates/main/components/post-detail.hbs

SOC-1556 | Discussions - fix author link on details page

---

front/scripts/main/components/DiscussionConnectionErrorComponent.ts
front/scripts/main/components/DiscussionNotFoundErrorComponent.ts
front/styles/main/component/_discussion-error.scss

https://wikia-inc.atlassian.net/browse/SOC-1550

SOC-1550 | Discussions - fix grid on error pages

---

front/styles/main/module/_discussion.scss
front/templates/main/components/discussion-upvote-post.hbs
front/templates/main/components/post-detail.hbs

Fixes for the post action clickable area sizes, according to designer's guides:
https://wikia-inc.atlassian.net/browse/SOC-1546

SOC-1546 | Thread listing confusing clickable area

---

front/templates/main/components/post-reply.hbs

https://wikia-inc.atlassian.net/browse/SOC-1556

SOC-1556 | Discussions - Fix profileUrl for lazy loaded replies

---

front/locales/ja/main.json

https://wikia-inc.atlassian.net/browse/SOC-1573

SOC-1573 | Discussion - new translations for JA

---

front/scripts/main/components/ForumWrapperComponent.ts
front/scripts/main/models/DiscussionForumModel.ts
front/templates/main/discussion/forum.hbs

https://wikia-inc.atlassian.net/browse/SOC-1558
page number for article list is passed from route to the component

SOC-1558 | 404 error when scrolling too quickly on cocktails discussions wiki

---

config/localSettings.base.ts
config/localSettings.dev.ts

@kvas-damian @rafalkalinski Let's do it!
BTW. there's a ticket for removing splash pages whatsoever (https://wikia-inc.atlassian.net/browse/SOC-1575) - we're just leaving them here in case of any possible quick reverts.

Discussions | Enabling discussions on featured Wikias

---

bower.json

@kvas-damian @Bloodmoon24 @rafalkalinski

Style-Guide | Bump version to 1.7.4

---

front/styles/main/component/_discussion-contributors.scss
front/templates/main/components/discussion-contributors.hbs

SOC-1551 | Contributors count will be broken when we reach 1k contributors
https://wikia-inc.atlassian.net/browse/SOC-1551

SOC-1551 | Contributors count will be broken when we reach 1k contributors

---

server/views/_helpers/translations.js

https://github.com/Wikia/mercury/pull/1637

Soc 1476 fix

---

config/discussionsSplashPageConfig.ts
front/scripts/main/components/CommunityBadgeComponent.ts
front/scripts/main/components/DiscussionHeroUnitComponent.ts

Enable discussions on international starwars wikis
http://fr.starwars.wikia.com/d/f/750/latest
http://es.starwars.wikia.com/d/f/916/latest
http://pt.starwars.wikia.com/d/f/1473/latest
http://ru.starwars.wikia.com/d/f/1530/latest
http://pl.starwars.wikia.com/d/f/1707/latest
http://it.starwars.wikia.com/d/f/3786/latest
http://jedipedia.wikia.com/d/f/280741/latest

SOC | Enable discussions on starwars

---

server/views/_partials/qualaroo.hbs

Mercury qualaroo tracker does not send user id (marked as TODO in the code)

INT-254: Send user id to qualaroo

---

config/localSettings.base.ts
config/localSettings.d.ts
server/app.ts
server/lib/AuthUtils.ts
server/lib/WikiaSession.ts

https://wikia-inc.atlassian.net/browse/SOC-1566

SOC-1566 | Use WhoAmI service instead of Helios for access_token validation

---

front/scripts/main/components/LightboxAdsComponent.ts
front/scripts/main/components/LightboxWrapperComponent.ts
front/scripts/main/controllers/ApplicationController.ts
front/scripts/main/routes/ApplicationRoute.ts
front/scripts/mercury/modules/Ads.ts
front/templates/main/application.hbs
front/templates/main/components/application-wrapper.hbs
front/templates/main/components/lightbox-wrapper.hbs

We are giving possibility of delaying the appearance of close button for lighbox ad layer. It is configurable trough DFP and by default set to 0.

Aden 2559 close button delay

---

front/styles/main/component/_context-links.scss
front/styles/main/component/index.scss

https://wikia-inc.atlassian.net/browse/DAT-3463

DAT-3463 Style context-links templates

---

front/scripts/main/components/ArticleContentComponent.ts
front/styles/main/module/article/_table.scss

https://wikia-inc.atlassian.net/browse/XW-745

XW-745 | Non-portable infoboxes no longer show on Mercury in iOS

---

front/scripts/main/mixins/DiscussionErrorMixin.ts
front/scripts/main/models/DiscussionForumModel.ts
front/scripts/main/models/DiscussionPostModel.ts
front/templates/main/discussion/forum.hbs

Usage
```
this.get('model').createReply({
threadId : "2614587795259262672",
body: "test",
creatorId: 5428365,
siteId: 3035
});
```

SOC-952 | Create reply method

---

CHANGELOG.md
front/scripts/main/components/ArticleContentComponent.ts
front/styles/main/module/article/_table.scss
package.json

https://wikia-inc.atlassian.net/browse/XW-745

Release 189 - fix P2

---

front/scripts/mercury/modules/Ads.js

This will be fixed in later versions of JSDoc
See https://github.com/jsdoc3/jsdoc/issues/705

Use Clousure syntax for 2D array

---

package.json

https://wikia-inc.atlassian.net/browse/XW-159

XW-159 | add npm tasks

---

front/scripts/main/components/ArticleContentComponent.ts
front/scripts/main/components/ArticleContributionComponent.ts
front/scripts/main/components/ArticleWrapperComponent.ts
front/templates/main/components/article-contribution.hbs
front/templates/main/components/article-wrapper.hbs
test/specs/front/scripts/main/components/ArticleContributionComponent.js

This PR contains changes for INT-89 and INT-246. Changes for INT-246 build on top of the changes for INT-89, so I am putting everything together in one PR.
These issues are for global rollout of the Mercury section editor:
* INT-89: Login to edit rule implementation
* INT-246: Rollout section editor for selected communities plus all Japanese communities.

INT-246: Mercury section editor rollout phase 1

---

front/scripts/main/helpers/time-ago-helper.js
front/scripts/main/mixins/color-utils.js
front/scripts/main/mixins/link-component.js
front/scripts/main/mixins/theme.js
front/scripts/mercury/modules/Trackers/BaseTracker.js
front/scripts/mercury/modules/VideoLoader.js
front/scripts/mercury/modules/VideoPlayers/Base.js
front/scripts/mercury/modules/VideoPlayers/Ooyala.js
front/scripts/mercury/modules/VideoPlayers/YouTube.js
front/scripts/mercury/utils/dateTime.js
front/templates/main/components/application-wrapper.hbs
server/facets/operations/prepareArticleData.ts

E.g.: fix calling track inside track and stop using arguments in Ooyala

XW-754 fix bugs found while testing ES6

---

bower.json

related to https://github.com/Wikia/app/pull/9124
https://wikia-inc.atlassian.net/browse/DAT-3436

DAT-3436 update wikia style guide version to use new blockquote styles

---

front/scripts/main/components/LightboxAdsComponent.ts
front/scripts/main/components/LightboxWrapperComponent.ts
front/templates/main/components/lightbox-wrapper.hbs

Adding counter in order to show users how long they need to wait until the close button appear.

ADEN-2598 adding counter

---

bower.json
config/discussionsSplashPageConfig.d.ts
config/discussionsSplashPageConfig.ts
front/scripts/main/components/lightbox-ads.js
front/scripts/main/components/lightbox-wrapper.js
front/templates/main/components/lightbox-wrapper.hbs

Files with most conflicts:
- lightbox-ads.js
- lightbox-wrapper.js

Merge dev to es6-front

---

front/scripts/main/mixins/color-utils.js
front/scripts/main/routes/discussion-forum.js
front/scripts/mercury/modules/Ads.js
front/scripts/mercury/modules/Trackers/Internal.js
front/scripts/mercury/utils/track.js

Fix ESLint warnings

---

gulp/tasks/scripts-front.js

https://wikia-inc.atlassian.net/browse/XW-799
/cc @bognix @hakubo @rogatty
Removing browser-sync: https://wikia-inc.atlassian.net/browse/XW-803

XW-799 | Fix error handling for Babel

---

front/scripts/main/app.js

Remove LOG_RESOLVER

---

front/styles/main/module/_ads.scss
front/templates/main/components/main-page.hbs

https://wikia-inc.atlassian.net/browse/XW-728

XW-728 | add PAD slot to main pages

---

homepage/front/styles/component/_nav.scss

https://wikia-inc.atlassian.net/browse/INT-272

INT-272 | Make sure nav is centered on screen

---

front/scripts/main/components/curated-content-editor-image-crop.js
front/scripts/main/components/curated-content-editor-item-form.js

https://wikia-inc.atlassian.net/browse/XW-602

XW-602 | Reset imageProperties before cropping image in Curated Content Editor

---

front/styles/main/component/_share-header.scss
front/styles/main/component/_site-head.scss

https://wikia-inc.atlassian.net/browse/XW-367

XW-367 | Disable animations for share header and site head

---

server/lib/MediaWiki.js

https://wikia-inc.atlassian.net/browse/XW-637
/ping! @macbre

XW-637 | add mercury 'User-Agent' and 'X-Wikia-Internal-Request' headers for all MW requests

---

front/scripts/main/components/article-edit.js
front/styles/main/module/edit/_edit-common.scss
front/templates/main/components/article-add-photo.hbs
front/templates/main/components/article-edit.hbs

Restyling of the header used for edit page and upload photo to use the same style as the main page curated content editor.
https://wikia-inc.atlassian.net/browse/INT-188

INT-188 | Use common style for edit page / upload photo header

---

front/scripts/main/components/article-wrapper.js

XW | eslint fix

---

front/scripts/mercury/modules/VideoPlayers/Base.js
front/scripts/mercury/modules/VideoPlayers/Ooyala.js
front/scripts/mercury/modules/VideoPlayers/YouTube.js
front/scripts/mercury/utils/track.js
test/specs/front/scripts/mercury/modules/VideoPlayers/Base.js

https://wikia-inc.atlassian.net/browse/XW-767
Use standard tracking events for video tracking.

XW-767 Fix tracking for videos

---

.eslintrc
package.json

https://wikia-inc.atlassian.net/browse/XW-671

XW-671 | add babel as parser to eslint

---

config/localSettings.base.js
server/lib/Utils.js
server/views/_layouts/ember-main.hbs
server/views/_partials/dns-prefetch.hbs
server/views/_partials/tracking.hbs

https://wikia-inc.atlassian.net/browse/XW-94

XW-94 use dns-prefetch

---

front/styles/main/theme/_dark.scss

https://wikia-inc.atlassian.net/browse/SOC-1749

SOC-1749 dark theme post color is wrong

---

front/scripts/main/components/article-content.js
front/styles/main/module/article/_portable-table.scss
front/styles/main/module/index.scss

https://wikia-inc.atlassian.net/browse/DAT-3523

Dat 3523 | add styles for portable tables 

---

front/scripts/main/components/discussion-editor.js
front/scripts/main/components/discussion-header.js
front/templates/main/components/discussion-header.hbs

https://wikia-inc.atlassian.net/browse/SOC-1739

SOC-1739 | editor misbehave for anon user

---

front/scripts/main/components/curated-content-editor-item-form.js
front/scripts/main/models/curated-content-editor-item.js
front/templates/main/components/curated-content-editor-item-form.hbs

https://wikia-inc.atlassian.net/browse/XW-657

XW-657 | search only categories in search suggestions

---

front/scripts/main/controllers/discussion-post.js

https://wikia-inc.atlassian.net/browse/SOC-1582

SOC-1582 | Discussion - one more fix for load more replies button

---

server/facets/auth/authView.js

Fix for modified tracking partial introduced in: https://github.com/Wikia/mercury/pull/1728/files#diff-5a7093f1bae8bfb93f7558f722b361b0R22
Ping @bognix

SOC-1762 | Fix GA tracking on AuthPages

---

front/scripts/main/components/discussion-sort.js
front/scripts/main/controllers/discussion-forum.js
front/scripts/main/helpers/equal-helper.js
front/scripts/main/models/discussion-forum.js
front/scripts/main/routes/discussion-forum.js
front/templates/main/components/discussion-sort.hbs

https://wikia-inc.atlassian.net/browse/SOC-1713

SOC-1713 | Discussions - change default posts order

---

front/styles/main/module/article/_portable-table.scss

https://wikia-inc.atlassian.net/browse/DAT-3555

DAT-3555 | set max-width to arbitrary value

---

front/templates/main/components/discussion-sort.hbs

https://wikia-inc.atlassian.net/browse/SOC-1713
ping @rafalkalinski

SOC-1713 | Discussion sort - fix colors

---

front/scripts/main/controllers/article-add-photo.js
front/scripts/main/controllers/article-edit.js
front/scripts/main/routes/article.js

@rogatty @perjg 
Details in the ticket: https://wikia-inc.atlassian.net/browse/INT-282

XW | show notifications when there is space in article title

---

server/lib/Utils.js
test/specs/server/lib/Utils.js

https://wikia-inc.atlassian.net/browse/SOC-1764

SOC-1764 | Fix title when hostname is present

---

front/scripts/main/helpers/duration-helper.js
front/scripts/main/helpers/i18n-helper.js
front/scripts/main/helpers/numeral-helper.js
front/scripts/main/helpers/svg-helper.js
front/scripts/main/helpers/thumbnail-helper.js
front/scripts/main/helpers/time-ago-helper.js
front/scripts/main/helpers/truncate-helper.js
front/templates/main/components/wikia-users.hbs
test/helpers/startEmberApp.js
test/karma.conf.js
test/specs/front/scripts/main/helpers/duration-helper.js
test/specs/front/scripts/main/helpers/i18n-helper.js
test/specs/front/scripts/main/helpers/svg-helper.js
test/specs/front/scripts/main/helpers/thumbnail-helper.js
test/specs/front/scripts/main/helpers/truncate-helper.js

https://wikia-inc.atlassian.net/browse/XW-27

XW-27 | Fix unit tests for Ember helpers and add some more

---

front/scripts/main/components/curated-content-editor-image-crop.js
front/scripts/main/components/curated-content-editor-image-search.js
front/scripts/main/components/curated-content-editor-item-form.js
front/scripts/main/components/curated-content-editor-section.js
front/scripts/main/components/curated-content-editor.js
front/scripts/main/components/curated-content.js
front/scripts/main/components/discussion-editor.js
front/scripts/main/components/lightbox-image.js
front/scripts/main/components/loading-spinner.js
front/scripts/main/components/local-wikia-search.js

https://wikia-inc.atlassian.net/browse/XW-638

XW-638 | loading spinner is not visible by default

---

front/scripts/main/mixins/discussion-upvote-action-send.js

@kvas-damian @rafalkalinski 
https://wikia-inc.atlassian.net/browse/SOC-1726

SOC-1726 | Dont allow anons to upvote

---

homepage/gulp/tasks/build-combined.js
homepage/server/util.js
homepage/server/views/_layouts/default.hbs
homepage/server/views/_partials/optimizely.hbs

Added Optimizely script.
According to the Optimizely docs, the script should be embedded in <head>
It requires jquery to be included first, so I removed jquery from the combined.js script and include it manually before the optimizely script.
https://wikia-inc.atlassian.net/browse/INT-285

INT-285 | Enable optimizely for Japan Homepage

---

front/styles/auth/app.scss

#perfmatters
instead of  ```@import url(../../vendor/wikia-style-guide/dist/css/main.css);``` put ```main.css``` file content into ```app.css```
ping @vforge @rogatty @rafalkalinski

SOC - load CSSes on auth pages in one request

---

homepage/config/localSettings.base.js
homepage/front/styles/theme/_icons.scss
homepage/server/auth.js
homepage/server/util.js

I found that there is an extra "/" in request to check user login status. The URL was "https://services.wikia.com/helios//info?code=..." (notice "//" before "info"). I am not 100% sure if this is a cause of failure because I cannot hit the URL from my development environment: I always got 403 Forbidden no matter what. I talked to service team and they say the given url is now only allowed internally, that I am still investigating what it means "internal". 
@perjg how do we test Japan HP, given that URL to hit helios is production URL (no switch between dev or production). Do you stage this in sandbox?

INT-279: JP homepage - login icon missing

---

front/README.md

This is a minor thing just to test if `Mercury-TESTS-Dev` job is triggered correctly on Jenkins after merge to `dev`.

XW-826 | fix markdown syntax

---

front/scripts/main/mixins/article-content.js
front/scripts/main/models/article-add-photo.js
front/scripts/main/models/curated-content-editor-item.js
front/scripts/main/models/curated-content-editor.js
front/scripts/main/models/discussion-forum.js
front/scripts/main/models/discussion-index.js
front/scripts/main/models/discussion-post.js
front/scripts/main/models/wikia-in-your-lang.js

https://wikia-inc.atlassian.net/browse/XW-866

XW-866 | Remove remaining usage of the App global

---

.gitignore

@rogatty @hakubo @Warkot Seems like this directory is making our life harder :)

gitignore | Adding coverage/ to gitignore

---

front/scripts/main/components/portable-infobox.js

https://wikia-inc.atlassian.net/browse/DAT-3085

DAT-3085 | do not collapse/uncollapse infobox when click target is an img

---

front/scripts/main/components/post-detail.js
server/facets/showDiscussions.js

https://wikia-inc.atlassian.net/browse/SOC-1763
@kvas-damian @bkoval please CR

SOC-1763 | Prevented opening links in discussion posts from forum view

---

front/scripts/main/components/portable-infobox.js

Fix for #1807 
https://wikia-inc.atlassian.net/browse/DAT-3085

DAT-3085 | add shouldHandleClick()

---

front/scripts/main/components/discussion-header.js
front/styles/main/component/_discussion-header.scss
front/templates/main/components/discussion-header.hbs
front/templates/main/discussion/forum.hbs

https://wikia-inc.atlassian.net/browse/SOC-1742

SOC-1742 | Fix Discussion sort overlay

---

package.json

https://github.com/karma-runner/karma/issues/1751

change karma version 0.13.15 -> 0.13.19

---

README.md
config/localSettings.example.js

XW | Make sure default WIKIA_ENVIRONMENT for configuration  is 'dev'

---

CHANGELOG.md

Release 200

---

front/styles/main/base/_anchors.scss
front/styles/main/base/index.scss
front/styles/main/component/_collapsible-menu.scss
front/styles/main/component/_local-nav-menu.scss
front/styles/main/component/_site-head.scss
front/styles/main/component/_user-avatar.scss
front/styles/main/component/_user-menu.scss
front/styles/main/module/_comments.scss
front/styles/main/state/_touch-active.scss
front/styles/main/state/index.scss

https://wikia-inc.atlassian.net/browse/SOC-1576

SOC-1576 | remove active highlighting on all links

---

bower.json

http://emberjs.com/blog/2016/01/14/security-releases-ember-1-11-4-1-12-2-1-13-12-2-0-3-2-1-2-2-2-1.html

Upgrade Ember to v2.0.3

---

bower.json
package.json

https://wikia-inc.atlassian.net/browse/XW-948

XW-984 | clean up after ember-cli

---

crowdin/auth-front.conf
crowdin/auth.conf
crowdin/discussion.conf
crowdin/main.conf

XW | fix crowdin paths

---

server/app/facets/showArticle.js
server/app/lib/MediaWiki.js

https://wikia-inc.atlassian.net/browse/XW-926

XW-926 Fix server error handling

---

tasks/jenkins/mercury-pr-checks.sh

Fix a typo in mercury-pr-checks.sh

---

front/main/app/templates/components/discussion-forum.hbs

Discussions | Use anchor instead of link-to for wiki link

---

package.json

Remove service related scripts

---

front/auth/gulpfile.js
gulp/paths.js

https://wikia-inc.atlassian.net/browse/XW-1020
/cc @kvas-damian

XW-1020 | Watch all auth SCSS files, including partials

---

front/common/modules/InstantGlobals.js
front/common/modules/Trackers/IVW3.js
front/common/utils/track.js
server/app/lib/Tracking.js
server/config/localSettings.base.js

Implementation of new IVW3 tracking provider which will be enabled in DE, AT, CH

ADEN-2812 IVW3 tracker integration

---

front/main/app/components/side-nav-local-wikia-search-2016.js
front/main/app/styles/component/_side-nav.scss
front/main/app/templates/components/side-nav-local-wikia-search-2016.hbs

- focus on input after clear search is clicked    
- click area have 30px on side-nav clear now

Click on clear should not close keyboard

---

front/common/tests/unit/baseline/buildUrl.js
server/app/views/_partials/server-data.hbs

As we discussed with @rogatty imageReviewBaseRoute variable disappeared.
Tests will come a bit later.

PLATFORM-1833 imageReviewBaseRoute fix

---

front/main/app/components/side-nav-local-navigation-root.js
front/main/app/templates/components/side-nav.hbs

https://wikia-inc.atlassian.net/browse/XW-1019
/cc @Wikia/x-wing

XW-1019 | scroll back to top while navigating through local nav

---

tasks/jenkins/mercury-pr-checks.sh
tasks/jenkins/mercury-pr-links.sh

https://wikia-inc.atlassian.net/browse/XW-773

XW-773 | add links to github after jenkins job is done

---

front/common/public/locales/en/discussion.json
front/main/app/templates/components/post-reply.hbs

user posts/replies lists - reply card header text
https://wikia-inc.atlassian.net/browse/SOC-1924

SOC-1924 user posts/replies lists - reply card header text

---

front/common/public/locales/en/discussion.json
front/main/app/templates/components/post-reply.hbs

Revert "SOC-1924 user posts/replies lists - reply card header text"

---

front/main/app/components/discussion-editor.js
front/main/app/components/discussion-post-editor.js
front/main/app/components/forum-wrapper.js

Hey,
While working on something else I did couple of changes to discussion code.
Do they look good to you?
@bkoval @kvas-damian @rogatty

Discussion refactors

---

front/common/modules/VideoLoader.js
front/main/app/components/lightbox-media.js
front/main/app/components/lightbox-video.js
front/main/app/templates/components/lightbox-video.hbs

as this is bad for performance
and is being deprecated

XW-821 | don't set properties in didInsertElement

---

front/main/app/models/image-review.js

Simple if change, makes flagged images appear. 
/cc @rogatty @pchojnacki

PLATFORM-1855 Image review does not show flagged images

---

front/auth/app/styles/theme/_auth-global-nav.scss

@bkoval @kvas-damian 
sorry about that :(

fix blue wikia logo on signin page

---

front/main/app/components/article-content.js
front/main/app/models/article.js
front/main/app/routes/article.js
front/main/app/templates/components/article-wrapper.hbs
front/main/tests/unit/models/article-test.js
front/main/tests/unit/routes/article-test.js
server/app/facets/operations/prepareArticleData.js

https://wikia-inc.atlassian.net/browse/XW-1075

XW-1075 | use display title

---

front/main/app/components/side-nav-local-navigation-menu-2016.js
front/main/app/routes/recent-wiki-activity.js
front/main/app/templates/components/side-nav-local-navigation-menu-2016.hbs
server/app/routes.js

@hakubo @rogatty @kamilkoterba

CE-3317 Enable RWA only on kirkburn.wikia.com

---

front/common/public/locales/en/recent-wiki-activity.json

CE-3326 Add all future translations

---

crowdin/recent-wiki-activity.conf
front/common/public/locales/en/recent-wiki-activity.json

CE-3326 Add strings related to Recent Wiki Activity to start i18n

---

front/common/public/locales/en/recent-wiki-activity.json
front/main/app/components/user-avatar.js
front/main/app/models/article-diff.js
front/main/app/templates/components/recent-change.hbs
front/main/app/templates/components/user-avatar.hbs

@hakubo @rogatty @kamilkoterba

CE-3325 Handle revisions made by Anonymous users

---

front/main/app/components/side-nav-local-navigation-menu.js
front/main/app/routes/recent-wiki-activity.js

We want to test it on pure new wikia as well

CE-3317 Enable on aga.wikia.com for MVP testing

---

front/main/app/index.html
server/app/app.js
server/app/facets/operations/prepareArticleData.js
server/config/localSettings.base.js
server/package.json

https://wikia-inc.atlassian.net/browse/XW-1076
Uses https://github.com/vforge/hapi-prerender (with patches)

XW-1076 | Implement prerender.io on 10 communities

---

front/main/app/components/recent-change.js
front/main/app/models/article-diff.js
front/main/app/models/recent-wiki-activity.js
front/main/app/templates/components/article-diff.hbs
front/main/app/templates/components/recent-change.hbs

CE-3324: Use new revisions diff api

---

front/main/app/models/recent-wiki-activity.js

CE-3336 RWA should include only edits

---

front/common/public/locales/en/recent-wiki-activity.json
front/main/app/components/article-diff.js
front/main/app/components/confirmation-modal.js
front/main/app/controllers/article-diff.js
front/main/app/models/article-diff.js
front/main/app/styles/component/_article_diff.scss
front/main/app/styles/component/_sub-head.scss
front/main/app/templates/article-diff.hbs
front/main/app/templates/components/article-diff.hbs
front/main/app/templates/components/confirmation-modal.hbs

https://wikia-inc.atlassian.net/browse/CE-3321

CE-3321 Confirmation modal for undoing revisions

---

front/main/app/components/post-reply.js
front/main/app/templates/components/discussion-post.hbs

https://wikia-inc.atlassian.net/browse/SOC-1945
@kvas-damian @tomasznapieralski  please CR

SOC-1945 | Links in discussion replies are now clickable

---

front/main/app/controllers/article-diff.js
front/main/app/initializers/link-to.js
front/main/app/routes/article-diff.js
front/main/app/routes/recent-wiki-activity.js
front/main/app/templates/components/article-diff.hbs
front/main/app/templates/components/recent-change.hbs
front/main/app/templates/components/side-nav-local-navigation-menu.hbs

CR and context here: https://github.com/Wikia/mercury/pull/1986

Ce 3351 tracking

---

front/main/app/components/article-media-image.js
front/main/app/templates/components/article-media-image.hbs

https://github.com/Wikia/app/pull/9696

XW-1008 | SVG image placeholders

---

front/main/app/initializers/optimizely.js

XW-808 | Fix missing global variable

---

front/main/app/components/side-nav-local-navigation-menu.js
front/main/app/routes/recent-wiki-activity.js

https://wikia-inc.atlassian.net/browse/CE-3362
@Wikia/community-engineering @hakubo

CE-3362 Enable RWA on all english communities

---

front/main/app/components/recent-change.js
front/main/app/components/recent-wiki-activity.js
front/main/app/controllers/article-diff.js
front/main/app/controllers/recent-wiki-activity.js
front/main/app/models/article-diff.js
front/main/app/models/recent-wiki-activity.js
front/main/app/routes/recent-wiki-activity.js
front/main/app/styles/component/_recent-change.scss
front/main/app/templates/components/article-diff.hbs
front/main/app/templates/components/recent-change.hbs
front/main/app/templates/components/recent-wiki-activity.hbs
front/main/app/templates/recent-wiki-activity.hbs

Preserve scroll position on RWA

CE-3335: Preserve scroll position on RWA

---

front/common/public/locales/en/recent-wiki-activity.json

https://wikia-inc.atlassian.net/browse/CE-3327
Added all options of messages from ticket.
Messages submitted for translation.

CE-3327 Adding messages for feature visibility story

---

front/main/app/components/recent-wiki-activity.js
front/main/app/models/article-diff.js
front/main/app/routes/recent-wiki-activity.js

Fix RWA when preserved diff is not at the list

CE-3368: Fix RWA when preserved diff is not at the list

---

front/main/app/utils/ajax-call.js
front/main/tests/unit/utils/ajax-call-test.js

Utils | Use propert content type name for json

---

front/main/app/components/portable-infobox.js

https://wikia-inc.atlassian.net/browse/XW-1133

XW-1133 | Don't collapse infobox when user clicks on image/video caption

---

server/app/facets/auth/BirthdateInput.js
server/app/facets/auth/register.js
server/app/lib/AuthUtils.js
server/config/authLocaleSettings.js
server/tests/unit/lib/AuthUtils.js

https://wikia-inc.atlassian.net/browse/SOC-1933
@bkoval @katanka  CR please

SOC-1933 | Registration modal broken on pt wikis

---

front/main/app/components/recent-edit-banner.js
front/main/app/models/recent-wiki-activity.js
front/main/app/styles/component/_recent-edit-banner.scss
front/main/app/styles/component/index.scss
front/main/app/templates/components/article-wrapper.hbs
front/main/app/templates/components/recent-edit-banner.hbs

Add banner with recent edit to article page

CE-3377: Add banner with recent edit to article page

---

front/main/app/components/post-detail.js
front/main/app/components/post-reply.js
front/main/app/models/discussion-post.js
front/main/app/styles/_settings.scss
front/main/app/styles/module/_discussion.scss

the reported indicator on posts in the post list and on replies on the post details page
https://wikia-inc.atlassian.net/browse/SOC-1906

SOC-1906 reported indicator on posts

---

front/main/app/components/article-wrapper.js
front/main/app/components/recent-edit-banner.js
front/main/app/styles/component/_recent-edit-banner.scss
front/main/app/templates/components/article-wrapper.hbs
front/main/app/templates/components/recent-edit-banner.hbs

Add mechanism do enable/disable banner, add styling and tracking

CE-3379: Display/dismiss banner, styling and tracking

---

front/main/app/components/infobox-builder-edit-item-title.js
front/main/app/components/infobox-builder-edit-item.js
front/main/app/components/infobox-builder-item-title.js
front/main/app/models/infobox-builder.js
front/main/app/routes/infobox-builder.js
front/main/tests/unit/models/infobox-builder-test.js

https://wikia-inc.atlassian.net/browse/DAT-3744

DAT-3744 Infobox-builder: edit already existing template

---

.github/PULL_REQUEST_TEMPLATE.md

* http://wikia-inc.atlassian.net/browse/XW-1152
* https://github.com/Wikia/app/pull/9763
Use same mechanism as our app repo for Pull Requests. See https://github.com/Wikia/app/pull/9763 for detailed description.
@hakubo

XW-1152 | Add PULL_REQUEST_TEMPLATE

---

front/common/modules/Trackers/Nielsen.js
server/app/lib/Tracking.js
server/config/localSettings.base.js

* http://wikia-inc.atlassian.net/browse/ADEN-3013
Small fixes requested by Nielsen

ADEN-3013 Fix Nielsen typos

---

front/main/app/services/current-user.js

* https://wikia-inc.atlassian.net/browse/MAIN-6507
The check for userId being null was moved out of the load method in
this release, leading to this API call being made for anons as well.
This has caused large performance problems, so putting the check
back in as a quick fix.
@owend @hakubo

(MAIN-6507) Only load user info if the user is not an anon

---

front/main/app/routes/wiki-page.js
front/main/app/utils/mediawiki-handlers/article.js
server/app/facets/mediaWikiPage.js
server/app/facets/operations/prepareMediaWikiData.js

* http://wikia-inc.atlassian.net/browse/XW-1183
* https://github.com/Wikia/app/pull/9822
When API returns 404 error we need to handle this response in Mercury on both fronted and backend
@Wikia/x-wing

XW-1183 fix handling for 404 errors in Mercury

---

front/main/app/router.js
front/main/app/routes/infobox-builder.js

WIP. Do not merge. Needs to be tested before.
Make infoboxbuilder route to fit routing naming conventions proposed here: https://github.com/Wikia/guidelines/pull/106
https://github.com/Wikia/guidelines/pull/106
@RafLeszczynski @bognix @vforge

change route name from camelcase to dasherize

---

front/main/app/routes/wiki-page.js
front/main/app/utils/mediawiki-handlers/article.js
server/app/facets/mediaWikiPage.js
server/app/facets/operations/prepareMediaWikiData.js

**Work in progress. Don't merge!** State it here and use labels.

Release 213 hotfix

---

front/main/app/components/side-nav-local-navigation-menu.js
front/main/app/mixins/side-nav-new-badge.js
front/main/app/templates/components/side-nav-local-navigation-menu.hbs
front/main/app/utils/article-link.js

* http://wikia-inc.atlassian.net/browse/XW-1184
* https://github.com/Wikia/mercury/pull/2057
@bognix

XW-1184 | Fix actions for RWA

---

front/main/app/components/smart-banner-android.js
front/main/app/routes/application.js
front/main/app/utils/local-storage-connector.js

* https://wikia-inc.atlassian.net/browse/XW-1086
* https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js
You can't actually call window.localStorage when cookies are disabled. It'll throw. So you have to do a check in try/catch. 
@Wikia/x-wing

XW-1086 | Mercury should still work even with cookies disabled

---

CHANGELOG.md

Release 214

---

package.json

- bump karma version (fix socket hanging)
- ember test will use existing build
/cc @Wikia/x-wing

Jenkins improve

---

front/main/app/routes/article-preview.js

* http://wikia-inc.atlassian.net/browse/XW-1221
Fix path to wiki-page file in article-preview route
@Wikia/x-wing

XW-1221 fix path to model in article-preview route

---

front/main/app/components/article-edit-highlighted-entrypoint.js
front/main/app/components/article-edit.js
front/main/app/components/article-wrapper.js
front/main/app/controllers/article.js
front/main/app/mixins/text-highlight.js
front/main/app/templates/components/article-wrapper.hbs

* https://wikia-inc.atlassian.net/browse/CE-3442
* https://wikia-inc.atlassian.net/browse/CE-3429
Force login modal before redirect to edit page

CE-3442: Force login modal before edit.

---

front/common/modules/Trackers/Nielsen.js

* https://wikia-inc.atlassian.net/browse/ADEN-3043
Add timestamp to Nielsen request URL for preventing library from browser caching.

ADEN-3043 Add timestamp to Nielsen url

---

front/main/app/components/wikia-users.js
front/main/app/templates/components/article-wrapper.hbs
front/main/app/templates/components/wikia-users.hbs

* http://wikia-inc.atlassian.net/browse/XW-1218
@Wikia/x-wing

XW-1218 track top contributors

---

front/main/app/mixins/text-highlight.js

* https://wikia-inc.atlassian.net/browse/CE-3441
Improve highlighted text position in edit mode

CE-3441: Improve highlighted text position in edit mode

---

front/main/app/models/infobox-builder.js

* https://wikia-inc.atlassian.net/browse/DAT-3894
We need a valid edit token to perform save.
Needs to go together with https://github.com/Wikia/app/pull/9885
@RafLeszczynski @rogatty

Get edit token for save

---

front/main/app/components/curated-content-item.js
front/main/app/components/curated-content.js
front/main/app/components/featured-content.js
front/main/app/components/trending-articles-item.js
front/main/app/components/trending-videos-item.js
front/main/app/templates/components/curated-content.hbs
front/main/app/templates/components/main-page.hbs
front/main/app/templates/components/trending-articles.hbs
front/main/app/templates/components/trending-videos.hbs

* http://wikia-inc.atlassian.net/browse/XW-1212
@Wikia/x-wing

XW-1212 | Review tracking on curated main pages

---

front/main/app/router.js

- subtask: https://wikia-inc.atlassian.net/browse/DAT-3889
- main task: https://wikia-inc.atlassian.net/browse/DAT-3793

DAT-3793 make infobox-builder accept subtemplates

---

front/main/app/components/article-wrapper.js

* https://wikia-inc.atlassian.net/browse/CE-3467
Disable recent edit banner for users in highlighted text experiment

CE-3467: Disable recent edit banner

---

front/main/app/templates/components/content-recommendations.hbs

* http://wikia-inc.atlassian.net/browse/XW-1217
@Wikia/x-wing

XW-1217 | add tracking for related pages

---

front/main/app/components/article-content.js

* http://wikia-inc.atlassian.net/browse/CE-3460
The demo will now be launched when a user scrolls to an article's content.

CE-3460 Initialize the HTE demo when user scrolls to content

---

front/main/app/components/article-comments.js

* http://wikia-inc.atlassian.net/browse/XW-1215
@vforge

XW-1215 | review tracking on comments

---

CHANGELOG.md

Release 218

---

.npmrc
front/main/.npmrc
server/.npmrc

* https://docs.npmjs.com/misc/config#save-exact
* https://gist.github.com/kentcdodds/5352dcce1c62630fe9d0#file-npmrc
We use exact versions in our package.json. I always forget about that - that will do that for us automatically
@Wikia/x-wing

add .npmrc with save-exact=true

---

server/app/lib/WikiaSession.js

* https://wikia-inc.atlassian.net/browse/SOC-2121
Use HTTP response code instead of response text to decide whether user is authorized or not.
@bkoval @rafalkalinski

SOC-2121 | Fix expired session handling

---

front/main/app/components/category-section.js
front/main/app/templates/components/category-section.hbs

* http://wikia-inc.atlassian.net/browse/XW-1213
Review tracking on category pages
@Wikia/x-wing

XW-1213 | review tracking on category pages

---

front/main/app/components/article-content.js
front/main/app/components/article-edit-highlighted-entrypoint.js
front/main/app/components/article-media-thumbnail.js
front/main/app/components/article-wrapper.js
front/main/app/components/curated-content-editor-block.js
front/main/app/components/curated-content-editor-image-crop.js
front/main/app/components/curated-content-editor-image-search.js
front/main/app/components/curated-content-editor-item-form.js
front/main/app/components/curated-content-editor-section.js
front/main/app/components/curated-content-editor.js
front/main/app/components/curated-content.js
front/main/app/components/infobox-builder-edit-item-title.js
front/main/app/components/lightbox-media.js
front/main/app/components/media.js
front/main/app/components/portable-infobox.js
front/main/app/components/recent-edit-banner.js
front/main/app/components/site-head.js
front/main/app/components/wikia-footer.js
front/main/app/components/wikia-in-your-lang.js
front/main/app/components/wikia-map.js
front/main/app/components/wikia-users.js
front/main/app/templates/components/article-media-thumbnail.hbs
front/main/app/templates/components/image-media.hbs
front/main/app/templates/components/linked-gallery-media.hbs

- remove curated content edit events
- remove lightbox events
- remove some random events :D
- use clickTrack mixin when possible
- update tracking for media
* http://wikia-inc.atlassian.net/browse/XW-1219
@Wikia/x-wing

XW-1219 | update tracking

---

front/main/app/components/smart-banner-android.js

* http://wikia-inc.atlassian.net/browse/XW-1112
Smart banner image was loaded as a huge original image. Now it's just a tiny thumbnail.
@Wikia/x-wing

XW-1112 | smart banner image scaling

---

front/main/app/utils/article-link.js

* http://wikia-inc.atlassian.net/browse/XW-1236
Checking if we have Category: in a link should be enough to enable that on EN comunities
@Wikia/x-wing

XW-1236 | remove $wgEnableCategoryPagesInMercury

---

server/app/lib/MediaWiki.js

* https://wikia-inc.atlassian.net/browse/XW-90
After small investigation I can tell that 
* majority of errors are 502
* I can reproduce that constantly when wrong host is sent to icache (e.g. host.wikia.com/ or http://host.wikia.com)
* I need to see if we send correct host to icache
@Wikia/x-wing

add host to logs so we can see if requests are made with correct host

---

front/main/app/components/bottom-banner.js
front/main/app/components/feedback-form.js
front/main/app/styles/component/_bottom-banner.scss
front/main/app/styles/component/index.scss
front/main/app/templates/components/article-wrapper.hbs
front/main/app/templates/components/feedback-form.hbs

* https://wikia-inc.atlassian.net/browse/CE-3484
* https://wikia-inc.atlassian.net/browse/CE-3471
Add and display empty feedback form banner

CE-3484: Add feedback form component

---

front/main/app/components/feedback-form.js
front/main/app/styles/component/_feedback-form.scss

* https://wikia-inc.atlassian.net/browse/CE-3471
Fixes for icon and setting cookie

CE-3471: user satisfaction fixes

---

server/app/views/_partials/tracking-quantserve.hbs

* http://wikia-inc.atlassian.net/browse/XW-1243
@Wikia/x-wing

XW-1243 | fix console error on auth pages

---

front/main/app/components/article-content.js
front/main/app/components/portable-infobox-question.js
front/main/app/components/portable-infobox.js
front/main/app/styles/module/article/_portable-infobox-question.scss
front/main/app/templates/components/portable-infobox-question.hbs
front/main/app/templates/components/portable-infobox.hbs

* https://wikia-inc.atlassian.net/browse/CE-3479
Added variations mentioned in the ticket and submission with showing confirm banner/error.

CE-3479 Infobox test variations

---

front/main/app/components/portable-infobox-question.js
front/main/app/mixins/user-feedback-storage.js
front/main/app/templates/components/portable-infobox-question.hbs

* http://wikia-inc.atlassian.net/browse/CE-3483
Blocked by:
* https://github.com/Wikia/mercury/pull/2169
Save users answers using the same UserFeedbackStorageApi as the user satisfaction feature uses.

CE-3483 Actually save answers provided by users

---

front/common/public/locales/de/main.json
front/common/public/locales/es/main.json
front/common/public/locales/fr/main.json
front/common/public/locales/it/main.json
front/common/public/locales/ja/main.json
front/common/public/locales/pt/main.json
front/common/public/locales/ru/main.json
front/common/public/locales/zh-hans/main.json
front/common/public/locales/zh/main.json

* http://wikia-inc.atlassian.net/browse/XW-1245
New translations downloaded freshly from Crowdin. This batch contains string related to category pages on Mercury and updated `wikia-page-error`.
@Wikia/x-wing

XW-1245 | i18n update — category page and wikia-page-error

---

front/main/app/components/feedback-form.js

* https://wikia-inc.atlassian.net/browse/CE-3518
Fix cookies and banner when user navigate through articles

CE-3518: Fix cookies and banner when user navigate through articles

---

front/main/app/components/portable-infobox-question.js
front/main/app/components/wikia-ui-components/text-field.js
front/main/app/styles/component/wikia-ui-components/_text-field.scss
front/main/app/styles/module/article/_portable-infobox-question.scss
front/main/app/templates/components/portable-infobox-question.hbs
front/main/app/templates/components/wikia-ui-components/text-field.hbs

* https://wikia-inc.atlassian.net/browse/CE-3482 Add tracking
* https://wikia-inc.atlassian.net/browse/CE-3512 Reuse input component
Adding tracking for submit and focus.
Added fix to unmark as invalid on focus out.
Added more functionality to text-field component
@Wikia/community-engineering, @Wikia/x-wing

Ce 3482 tracking

---

front/main/app/components/feedback-form.js

* https://wikia-inc.atlassian.net/browse/CE-3521
* https://wikia-inc.atlassian.net/browse/CE-3471
Limit experiment to EN communities

CE-3521: Limit experiment to EN communities

---

front/main/app/styles/component/wikia-ui-components/_sub-header.scss

Hot fix for broken arrow styles for hardcoded subheader component
@bognix @rogatty

fix broken back arrow styles for hardcoded sub header component

---

front/main/app/components/feedback-form.js
front/main/app/components/recent-edit-banner.js
front/main/app/mixins/bottom-banner.js

* https://wikia-inc.atlassian.net/browse/CE-3471
Change bottom banner component to mixin
@bognix @Grunny

CE-3471: Create Bottom Banner mixin

---

front/common/public/locales/en/recent-wiki-activity.json
front/main/app/components/article-diff.js
front/main/app/controllers/article-diff.js
front/main/app/styles/component/_article_diff.scss
front/main/app/templates/article-diff.hbs
front/main/app/templates/components/article-diff.hbs

CRed here https://github.com/Wikia/mercury/pull/2147

Ce 3265 upvote branch cleanup

---

front/main/app/styles/module/article/_portable-infobox.scss

https://wikia-inc.atlassian.net/browse/DAT-3972

DAT-3972 add overflow:auto to data-values

---

front/main/app/components/article-wrapper.js
front/main/app/components/recent-edit-banner.js
front/main/app/styles/component/_recent-edit-banner.scss
front/main/app/templates/components/recent-edit-banner.hbs

* https://wikia-inc.atlassian.net/browse/CE-3468
Add dismiss button to recent edit banner

CE-3468: Add dismiss button to recent edit banner

---

front/main/app/mixins/infobox-builder-edit-item.js
front/main/app/styles/component/_infobox-builder.scss
front/main/tests/unit/components/infobox-builder-edit-item-row-test.js
front/main/tests/unit/components/infobox-builder-edit-item-section-header-test.js

https://wikia-inc.atlassian.net/browse/DAT-3921
Add focusing on input fields when displaying sidebar.

DAT-3921 add focusing on inputs in Infobox Builder

---

front/main/app/index.html
server/app/app.js
server/app/facets/operations/prepare-article-data.js
server/app/facets/operations/prepare-category-data.js
server/app/facets/operations/prepare-mediawiki-data.js
server/config/localSettings.base.js
server/package.json

* http://wikia-inc.atlassian.net/browse/XW-1224
* https://github.com/Wikia/wikia-vcl/pull/841
* https://github.com/Wikia/chef-repo/pull/9026
Remove the support for Prerender.io
@Wikia/x-wing

XW-1224 remove prerender from codebase

---

front/common/public/locales/en/recent-wiki-activity.json
front/main/app/components/article-diff.js
front/main/app/controllers/article-diff.js
front/main/app/models/article-diff.js
front/main/app/styles/component/_article-diff.scss
front/main/app/styles/component/index.scss
front/main/app/templates/article-diff.hbs
front/main/app/templates/components/article-diff.hbs

* http://wikia-inc.atlassian.net/browse/JIRA-3492
Adding ability to downvote
@Wikia/community-engineering, @Wikia/x-wing

CE-3492 Add ability to downvote

---

front/main/app/components/article-diff.js
front/main/app/components/recent-change.js
front/main/app/styles/component/_article-diff.scss
front/main/app/templates/components/article-diff.hbs
front/main/app/templates/components/recent-change.hbs

* http://wikia-inc.atlassian.net/browse/CE-3535
@Wikia/community-engineering, @Wikia/x-wing

CE-3535 Enable only for EN wikis

---

front/common/public/locales/en/infobox-builder.json
front/main/app/styles/component/_infobox-builder.scss
front/main/app/templates/components/infobox-builder-go-to-source-modal.hbs

https://wikia-inc.atlassian.net/browse/DAT-3971
Change order of YES NO options in modal
myself :D

DAT-3971 Update copy and button positions

---

front/main/app/components/article-diff.js
front/main/app/components/recent-change.js
front/main/app/controllers/article-diff.js
front/main/app/models/article-diff.js

* https://wikia-inc.atlassian.net/browse/CE-3542
Reflect adding and removing upvotes on diff page

CE-3542: Reflect adding and removing upvotes on diff page

---

front/main/app/styles/_settings.scss
front/main/app/styles/component/_article-diff.scss
front/main/app/templates/components/article-diff.hbs

* https://wikia-inc.atlassian.net/browse/CE-3265
* https://wikia-inc.atlassian.net/browse/CE-3295
Fixes for revision upvotes

CE-upvotes-fixes: Change focused button color when user upvoted

---

server/app/facets/article-preview.js

https://github.com/Wikia/mercury/pull/2234

HOTFIX | XW | Fix cache control in article preview

---

server/app/facets/mediawiki-page.js
server/tests/acceptance/wiki-page.js

When user opens /wiki/ on a wiki that doesn't exist we should redirect to community, not display the error page.
@Warkot @bognix

XW | Fix redirects on /wiki/

---

server/app/facets/mediawiki-page.js
server/tests/acceptance/wiki-page.js

https://github.com/Wikia/mercury/pull/2238

HOTFIX | XW | Fix redirects on /wiki/

---

front/main/app/components/article-diff.js
front/main/app/controllers/article-diff.js
front/main/app/models/article-diff.js
front/main/app/templates/article-diff.hbs
front/main/app/templates/components/article-diff.hbs

* https://wikia-inc.atlassian.net/browse/CE-3556
Move most logic from controller to component
@Wikia/community-engineering @Wikia/x-wing @rogatty ;)

CE-3556: Move most logic from controller to component

---

front/main/app/components/infobox-builder-add-items.js

https://wikia-inc.atlassian.net/browse/DAT-4015
Change in Infobox Builder layout - rearrange add buttons to reflect default Infobox state.
@dianafa @RafLeszczynski @SebastianMarzjan @idradm

Rearrange add buttons

---

front/main/app/components/infobox-builder.js
front/main/app/models/infobox-builder.js
front/main/app/templates/components/infobox-builder.hbs
front/main/app/templates/infobox-builder.hbs
front/main/tests/unit/components/infobox-builder-test.js
front/main/tests/unit/models/infobox-builder-test.js

* https://wikia-inc.atlassian.net/browse/DAT-4018
Remove theme logic from Infobox Builder and set europa style to be automatically apply to IB preview if the assets came from backend
@dianafa @SebastianMarzjan

DAT-4018, remove theme logic from IB

---

server/app/views/_partials/tracking-ua-auth.hbs
server/app/views/_partials/tracking-ua.hbs

* http://wikia-inc.atlassian.net/browse/XW-1278
* https://github.com/Wikia/app/pull/10106
Base on the isanon flag we either cache responses from server or not
@Wikia/x-wing

XW-1278 | send flag if user is logged in to cache responses for anon users

---

front/main/app/styles/component/_recent-change.scss
front/main/app/templates/components/recent-change.hbs

CE-3556 Fix recent change layout

---

front/main/app/components/article-content.js

Update the HTE retirement date

---

front/main/app/routes/image-review.js

This small change makes page scroll to the top after reviewing batch of images.
@bognix

Image-review automatic page scroll

---

server/app/views/_partials/server-data.hbs
server/app/views/_partials/tracking-ua-auth.hbs
server/app/views/_partials/tracking-ua.hbs

* http://wikia-inc.atlassian.net/browse/XW-1308
Stop abusing `{{{`
@Wikia/x-wing

XW-1308 escape fragile data on server side

---

server/app/views/_partials/server-data.hbs
server/app/views/_partials/tracking-ua-auth.hbs
server/app/views/_partials/tracking-ua.hbs

* http://wikia-inc.atlassian.net/browse/XW-1308
* https://github.com/Wikia/mercury/pull/2271/files
@Wikia/x-wing

Xw 1308 escape fragile data on server side

---

front/main/app/routes/wiki-page.js

* to be removed via https://wikia-inc.atlassian.net/browse/XW-1321
Work when we have old app version.
@Wikia/x-wing

XW-1249 | Add fallback for old Wikia App

---

front/main/app/controllers/infobox-builder.js
front/main/app/routes/infobox-builder.js
front/main/app/templates/components/infobox-builder.hbs
front/main/app/templates/infobox-builder.hbs
front/main/tests/integration/components/infobox-builder-test.js
front/main/tests/unit/controllers/infobox-builder-test.js

* https://wikia-inc.atlassian.net/browse/CE-3570
Adds support for returning to VE and hiding the go to source button
when InfoboxBuilder is launched from VE.
@RafLeszczynski @Wikia/community-engineering @Wikia/x-wing

(CE-3570) Add support for VE context to InfoboxBuilder

---

front/auth/bower.json
front/common/bower.json
front/main/bower.json

Fixes error:
```
$ bower update
bower                         EINVALID Failed to read /usr/wikia/mercury/front/common/bower.json
Additional error details:
Name must be lowercase string, with dots, dashes, or @
```

Fix names in bower.json

---

front/auth/bower.json
front/common/bower.json
front/main/bower.json

* https://github.com/Wikia/mercury/pull/2286

[HOTFIX] Fix names in bower.json

---

TROUBLESHOOTING.md

Troubleshooting | Adding info about PhantomJS error

---

server/app/views/_partials/tracking-ivw3.hbs

ADEN-3017 Fix IVW3 tracking

---

front/main/app/components/infobox-builder.js
front/main/app/controllers/infobox-builder.js
front/main/app/models/infobox-builder.js
front/main/app/routes/infobox-builder.js
front/main/tests/unit/controllers/infobox-builder-test.js

* https://wikia-inc.atlassian.net/browse/CE-3569
We want to open dialog with infobox builder always in default state
@Wikia/community-engineering @RafLeszczynski @Wikia/x-wing

CE-3569: Set infobox to default state on every dialog open

---

server/app/facets/operations/prepare-article-data.js
server/app/facets/operations/prepare-category-data.js
server/app/facets/operations/prepare-curated-content-data.js
server/app/facets/operations/prepare-mediawiki-data.js

* http://wikia-inc.atlassian.net/browse/XW-1331
* https://github.com/Wikia/mercury/pull/2300
Make document.title proper without JS.
@Wikia/x-wing

XW-1331 | Make document.title proper without JS

---

front/common/public/locales/de/discussion.json
front/common/public/locales/es/discussion.json
front/common/public/locales/fi/discussion.json
front/common/public/locales/fr/discussion.json
front/common/public/locales/it/discussion.json
front/common/public/locales/ja/discussion.json
front/common/public/locales/ko/discussion.json
front/common/public/locales/nl/discussion.json
front/common/public/locales/pl/discussion.json
front/common/public/locales/pt-pt/discussion.json
front/common/public/locales/pt/discussion.json
front/common/public/locales/ru/discussion.json
front/common/public/locales/sv-se/discussion.json
front/common/public/locales/vi/discussion.json
front/common/public/locales/zh-hans/discussion.json
front/common/public/locales/zh/discussion.json

https://wikia-inc.atlassian.net/browse/LOC-338
New translations

LOC-338 | New discussion translations

---

front/main/app/styles/component/_article-media-thumbnail.scss
front/main/app/styles/module/article/_portable-infobox.scss

* http://wikia-inc.atlassian.net/browse/XW-1350
@rogatty

XW-1350 | limit infobox height in scss

---

front/main/app/components/application-wrapper.js
front/main/app/components/site-head.js
front/main/app/templates/components/application-wrapper.hbs

* https://wikia-inc.atlassian.net/browse/DAT-4075
Add CONTROL group to nav AB test experiment A (fab icons
@SebastianMarzjan @idradm

DAT-4075, add extra tracking for CONTROL group

---

front/main/app/components/application-wrapper.js
front/main/app/components/site-head.js
front/main/app/templates/components/application-wrapper.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4075
Hotfix for adding extra tracking for Control group for experiment DAT-4075

Release 230 dat 4075

---

front/main/app/components/application-wrapper.js
front/main/app/components/site-head.js
front/main/app/templates/components/application-wrapper.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4075
Hotfix for adding extra tracking for Control group for experiment DAT-4075

Release 231 dat 4075

---

front/main/app/components/article-media-thumbnail.js
front/main/app/components/content-recommendation-thumbnail.js
front/main/app/mixins/media-thumbnail-utils.js
front/main/app/styles/component/_content-recommendation-thumbnail.scss
front/main/app/styles/component/index.scss
front/main/app/templates/components/content-recommendation-thumbnail.hbs
front/main/app/templates/components/content-recommendations.hbs

XW-1300 | Fix recommendation thumbnails, move common logic to mixin

---

front/main/app/templates/components/discussion-reported-posts-wrapper.hbs
front/main/app/templates/components/discussion-reported-posts.hbs
front/main/app/templates/components/discussion-user.hbs
front/main/app/templates/discussion/reported-posts.hbs

https://wikia-inc.atlassian.net/browse/SOC-2300
@kvas-damian  @rafalkalinski  please CR

SOC-2300 | Removed unused argument from template

---

front/main/app/templates/components/discussion-reported-posts-wrapper.hbs
front/main/app/templates/components/discussion-reported-posts.hbs
front/main/app/templates/components/discussion-user.hbs
front/main/app/templates/discussion/reported-posts.hbs

* http://wikia-inc.atlassian.net/browse/SOC-2300
Fix js errors on discusions. Backporting https://github.com/Wikia/mercury/pull/2319

SOC-2300 | Fix errors on discussions

---

front/main/app/components/application-wrapper.js
front/main/app/components/site-head.js
front/main/app/styles/component/_site-head.scss
front/main/app/templates/components/application-wrapper.hbs
front/main/app/templates/components/site-head.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4062
Hotfix adding second experiments for Mercury nav entry points.

Release 231 dat 4062

---

tasks/deploy.sh

change deploy server

---

front/main/tests/unit/routes/infobox-builder-test.js

* https://wikia-inc.atlassian.net/browse/CE-3552
Unit tests for beforModel method in infobox builder route
@Wikia/spitfires @RafLeszczynski

Ce 3552 route tests

---

front/main/app/components/widget-flite.js
front/main/app/templates/components/widget-flite.hbs

* http://wikia-inc.atlassian.net/browse/XW-1372
We can't have script tags in templates - we need workaround for Flite tags.
@Wikia/x-wing @nandy-andy @jacekjursza @fraszczakszymon

XW-1372 | Fix flite for Ember 2.3

---

front/main/app/components/application-wrapper.js
front/main/app/components/site-head.js
front/main/app/templates/components/site-head.hbs

* https://wikia-inc.atlassian.net/browse/DAT-4086
add additional tracking to wordmark in site header for nav experiment
@SebastianMarzjan @idradm

DAT-4086, add tracking to workdmark

---

server/app/facets/show-application.js
server/app/facets/show-discussions.js

* http://wikia-inc.atlassian.net/browse/XW-1356
@Wikia/x-wing

XW-1356 | add documentTitle on Discussions

---

homepage/package.json

* http://wikia-inc.atlassian.net/browse/JPN-433

JPN-433 | Add babel-preset-es2015 to dev dependency

---

front/main/app/templates/components/discussion-post-details-layout.hbs

https://wikia-inc.atlassian.net/browse/SOC-2343
@kvas-damian, @bkoval

SOC-2343 | contributors broken on post-detais on desktop

---

front/main/app/templates/components/discussion-post-details-layout.hbs

* https://wikia-inc.atlassian.net/browse/SOC-2343
* https://github.com/Wikia/mercury/pull/2367

SOC-2343 | post-details desktop contributors fixed

---

front/main/app/styles/layout/_wiki-container.scss
front/main/app/styles/layout/index.scss
front/main/app/styles/module/_ads.scss

* http://wikia-inc.atlassian.net/browse/XW-1379
Update color for mobile-top-leaderboard
@Wikia/x-wing

XW-1379 | Update background color for mobile-top-leaderbaord

---

front/main/app/styles/module/_site-footer.scss

Fix broken ember build after node-sass dependency upgrade
@Wikia/x-wing @SebastianMarzjan

ramove style referencing to unexisting class

---

front/main/app/components/side-nav-local-wikia-search.js
front/main/app/controllers/main-page.js
front/main/app/mixins/main-page-route.js
front/main/app/models/curated-content.js
front/main/app/routes/application.js

* https://github.com/Wikia/mercury/pull/2389
@tomasznapieralski

XW-1422 release

---

front/main/app/templates/components/side-nav-local-navigation-root.hbs

* https://wikia-inc.atlassian.net/browse/DAT-4114
Remove search from local nav
@SebastianMarzjan @idradm

DAT-4114 remove search from local nav

---

front/main/app/router.js

We stopped using catchpoint - so we do not need that part here
@Wikia/x-wing

remove special treatment for catchpoint

---

front/main/bower.json

* https://github.com/js-cookie/js-cookie/issues/186

Temporary fix for jquery-cookie which is currently broken

---

front/main/app/components/discussion-header.js
front/main/app/components/discussion-post-editor.js
front/main/app/components/recent-wiki-activity.js
front/main/app/components/site-head.js
front/main/app/controllers/application.js
front/main/app/controllers/discussion/base.js
front/main/app/controllers/recent-wiki-activity.js
front/main/app/mixins/theme.js
front/main/app/styles/component/_discussion-editor.scss
front/main/app/styles/component/_discussion-header.scss
front/main/app/styles/component/_site-head.scss
front/main/app/styles/layout/_page-wrapper.scss
front/main/app/styles/module/_discussion.scss
front/main/app/templates/application.hbs
front/main/app/templates/components/application-wrapper.hbs
front/main/app/templates/components/discussion-editor.hbs
front/main/app/templates/components/discussion-forum-wrapper.hbs
front/main/app/templates/components/discussion-reported-posts-wrapper.hbs
front/main/app/templates/discussion/forum.hbs
front/main/app/templates/discussion/reported-posts.hbs
front/main/app/templates/recent-wiki-activity.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4126

Make nav bar always visible and sticky

---

front/main/bower.json

* http://wikia-inc.atlassian.net/browse/XW-1445
For some reasons, bower cannot download headroom.js from original repo. Fork is working fine
@Wikia/x-wing

XW-1445 | Update headroom

---

front/main/app/models/discussion/base.js
front/main/app/models/discussion/forum.js
front/main/app/models/discussion/post.js
front/main/app/models/discussion/reported-posts.js
front/main/app/models/discussion/user.js

* http://wikia-inc.atlassian.net/browse/XW-1446
Hotfix for discussions errors
@Wikia/x-wing, @kvas-damian, @bkoval

XW-1446 | use Promises for discussions models

---

server/app/facets/operations/page-data-helper.js
server/tests/unit/facets/operations/page-data-helper.js

* http://wikia-inc.atlassian.net/browse/XW-1447
I missed one thing

XW-1447 | replace underscore with space

---

front/main/app/styles/module/_ads.scss

This will hide ad slot when there is no ad
@Wikia/x-wing

style only the ad-slot not the wrapper

---

server/app/views/_partials/wiki-page-header.hbs

* http://wikia-inc.atlassian.net/browse/XW-1478
One of refinements to be done to the new header.
@Wikia/x-wing

XW-1478 | server header matching fronted markup and style

---

front/common/styles/placeholder/%headers.scss
front/main/app/components/wikia-ui-components/wiki-page-header-curated-main-page.js
front/main/app/styles/component/wikia-ui-components/_wiki-page-header-curated-main-page.scss
front/main/app/templates/components/main-page.hbs
front/main/app/templates/components/wikia-ui-components/wiki-page-header-curated-main-page.hbs

* http://wikia-inc.atlassian.net/browse/XW-1488
* https://github.com/Wikia/mercury/pull/2446
A regression fix.
@Wikia/x-wing

XW-1488 | added back link to main page on Curataed Main (sub)Pages

---

front/main/app/styles/layout/article/_nav-AB-test.scss

* https://wikia-inc.atlassian.net/browse/DAT-4228
@idradm

DAT-4228 add !important to avoid overriding by other CSS rules

---

front/main/app/styles/component/_potential-member-page-experiment.scss
front/main/app/templates/components/potential-member-page-experiment-banner.hbs

* https://wikia-inc.atlassian.net/browse/XW-1514
Background image is not properly displayed. This is a workaround for now (this is experiment so the code will be removed)
CR done in https://github.com/Wikia/mercury/pull/2473

CE-3701: Fix displaying background image

---

front/main/app/components/discussion-editor.js
front/main/app/components/discussion-open-graph.js
front/main/app/utils/discussion-tracker.js

SOC-2495 | Tracking for OG Cards

---

front/main/app/styles/component/_article-media-thumbnail.scss

* https://wikia-inc.atlassian.net/browse/DAT-4298
// cc @rogatty

DAT-4298 | caption on thumbnail should open lightbox

---

front/main/app/routes/main-page-category.js
front/main/app/routes/main-page-section.js

* https://wikia-inc.atlassian.net/browse/DAT-4292
Fixes failing MercuryCuratedNavigationTest_004.
@tomasznapieralski

DAT-4292 | Fix error message on section 404

---

front/main/app/components/wikia-ui-components/wiki-page-header-curated-main-page.js
front/main/app/components/wikia-ui-components/wiki-page-header.js
front/main/app/templates/components/wikia-ui-components/wiki-page-header-curated-main-page.hbs
front/main/app/templates/components/wikia-ui-components/wiki-page-header.hbs

* http://wikia-inc.atlassian.net/browse/XW-1478
Cleanup after top of the article visual update.
https://github.com/Wikia/mercury/pull/2392#discussion_r60887392
@Wikia/x-wing

XW-1478 | rename mainPageName to siteName

---

front/main/app/components/wikia-search.js
front/main/app/templates/search.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4368

DAT-4368 add a way to disable suggestions, disable them on srp

---

front/main/app/styles/module/_discussion.scss
front/main/app/templates/components/discussion-post-card-detail.hbs

* https://wikia-inc.atlassian.net/browse/SOC-2597
Make QAs live easier with writing Selenium tests
@bkoval

SOC-2597 | Discussions - add span for counts

---

front/common/public/locales/de/search.json
front/common/public/locales/es/search.json
front/common/public/locales/fi/search.json
front/common/public/locales/fr/search.json
front/common/public/locales/it/search.json
front/common/public/locales/ja/search.json
front/common/public/locales/ko/search.json
front/common/public/locales/nl/search.json
front/common/public/locales/pl/search.json
front/common/public/locales/pt-pt/search.json
front/common/public/locales/pt/search.json
front/common/public/locales/ru/search.json
front/common/public/locales/sv-se/search.json
front/common/public/locales/vi/search.json
front/common/public/locales/zh-hans/search.json
front/common/public/locales/zh/search.json

Update translations for Mercury Search

---

front/main/app/models/search.js
front/main/mirage/config.js

* http://wikia-inc.atlassian.net/browse/DAT-4375
@SebastianMarzjan

DAT-4375 use wikia.php API

---

front/main/app/components/wikia-search.js
front/main/app/styles/component/_wikia-search.scss
front/main/app/templates/components/wikia-search.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4333
Make suggestions links redirect to oasis skin when in desktop view.

DAT-4333 suggestions redirect to oasis when in desktop view

---

front/auth/app/styles/_settings.scss
front/auth/app/styles/theme/_auth-global-nav.scss

* https://wikia-inc.atlassian.net/browse/DAT-4267
Adjust values to new svg icon and cleanup a bit
@kvas-damian

DAT-4267 fix stable.www.wikia.com/join wikia icon

---

homepage/server/views/_partials/footer.hbs

* https://wikia-inc.atlassian.net/browse/JPN-548
Changing the name of the link for Japanese Media kit as requested by Japan team.
@d34th4ck3r

JPN-548 | Change link text for Japanese mediakit

---

front/main/app/styles/component/_wikia-nav.scss

* http://wikia-inc.atlassian.net/browse/DAT-4180
@rogatty @tomasznapieralski

DAT-4180 smoother scrolling on ios

---

front/main/app/styles/component/_wikia-search.scss
front/main/app/templates/components/wikia-search.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4459
fixing clear button in wikia-search component

DAT-4459 | fixing clear button

---

tasks/changelog-view.sh

add `-g` option to post changelog on github
add `-u` option to post changelog on #weekly-release-update channel
@Wikia/x-wing

DAT | add option to changlog script to post changelog on github and slack channel

---

front/main/app/components/article-content.js
front/main/app/styles/layout/article/_nav-AB-test.scss
front/main/app/styles/layout/index.scss

* http://wikia-inc.atlassian.net/browse/DAT-4186
Navigation AB test code clean up.

DAT-4186 navigation test clean up

---

front/main/app/components/discussion-standalone-editor.js
front/main/app/styles/_settings.scss
front/main/app/styles/component/_discussion-standalone-editor.scss
front/main/app/styles/component/index.scss
front/main/app/templates/components/discussion-entities-list-layout.hbs
front/main/app/templates/components/discussion-standalone-editor.hbs
front/main/package.json

* https://wikia-inc.atlassian.net/browse/SOC-2599
Styles for standalone editor
@rafalkalinski @bkoval

SOC-2599 | Discussion - standalone editor styles

---

front/main/app/styles/component/_discussion-hero-unit.scss

Discussion | Fixing contributor avatar sizes in hero image

---

front/common/public/locales/de/search.json

* http://wikia-inc.atlassian.net/browse/DAT-4465
adding missing space in de translations for search

DAT-4465 | adding missing space in translation

---

front/main/app/routes/infobox-builder.js

* https://wikia-inc.atlassian.net/browse/CE-3703
* https://wikia-inc.atlassian.net/browse/CE-3829
If you click navigation back button in Infobox Builder and decline this action, you should stay in IB dialog
@Wikia/spitfires

CE-3829: Check if transition was aborted

---

front/main/app/templates/search.hbs

* http://wikia-inc.atlassian.net/browse/DAT-4492
Track clicks on search results

DAT-4492 Add tracking to clicks on Mercury Search results

---

front/common/public/locales/de/auth.json
front/common/public/locales/es/auth.json
front/common/public/locales/fi/auth.json
front/common/public/locales/fr/auth.json
front/common/public/locales/it/auth.json
front/common/public/locales/ja/auth.json
front/common/public/locales/ko/auth.json
front/common/public/locales/nl/auth.json
front/common/public/locales/pl/auth.json
front/common/public/locales/pt-pt/auth.json
front/common/public/locales/pt/auth.json
front/common/public/locales/ru/auth.json
front/common/public/locales/sv-se/auth.json
front/common/public/locales/vi/auth.json
front/common/public/locales/zh-hans/auth.json
front/common/public/locales/zh/auth.json
server/config/authLocaleSettings.js

* http://wikia-inc.atlassian.net/browse/LOC-167
* http://wikia-inc.atlassian.net/browse/SOC-2131
@kvas-damian @rafalkalinski

LOC-167 | Localization for new auth screens before the "100% release"

---

front/main/app/components/community-badge.js
front/main/app/components/discussion-hero-unit.js

https://wikia-inc.atlassian.net/browse/SOC-2631

SOC-2631 Adding badge & hero images

---

front/main/app/components/community-badge.js
front/main/app/components/discussion-hero-unit.js

* http://wikia-inc.atlassian.net/browse/JIRA-2631
We have a special request to enable Discussions on ja.elderscrolls today.
@kvas-damian @rafalkalinski

SOC-2631 | Community badge and hero image for ja.elderscrolls

---

server/app/views/_helpers/translations.js

* http://wikia-inc.atlassian.net/browse/DAT-4573
@Wikia/x-wing

DAT-4573 | send error to Kibana only when translation for default language not found

---

front/common/utils/track-perf.js
server/config/localSettings.base.js

* https://github.com/Wikia/mercury/pull/2598
(cherry picked from commit 0c390fc)

(DAT-4275) Temporarily sample experiment wikis at 100% in weppy

---

front/main/app/mixins/discussion-moderation-controller.js

* http://wikia-inc.atlassian.net/browse/JIRA-2731

SOC-2731 | Delete all posts is using new model scheme

---

front/main/app/styles/app.scss
front/main/bower.json

* http://wikia-inc.atlassian.net/browse/XW-1576
@Wikia/x-wing

XW-1576 | Add Design System to Mercury

---

front/main/app/styles/module/_ads.scss

* http://wikia-inc.atlassian.net/browse/ADEN-3493

ADEN-3493 Fix BFAA on pages with infobox

---

front/common/public/locales/en/discussion.json
front/main/app/components/discussion-categories-edit.js
front/main/app/models/discussion/categories.js
front/main/app/templates/components/discussion-categories-edit.hbs

* http://wikia-inc.atlassian.net/browse/JIRA-1789
This is temporary. I still need to add inline errors assignment (all the styling and logic is done) but I want an early CR on this one before I get an info from UX.
@rafalkalinski @mleczey

SOC-1789 | Adding ability to rename categories

---

front/main/app/components/discussion-post-card-top-note.js
front/main/app/components/discussion-welcome.js
front/main/app/helpers/wrap-me.js
front/main/tests/unit/helpers/wrap-me-test.js

* https://wikia-inc.atlassian.net/browse/XW-1735
Make sure the wrap-me helper escapes the content passed to it by default. See ticket
for details.
/cc @Wikia/x-wing @Wikia/west-wing

(XW-1735) Escape content of wrap-me helper by default

---

front/main/app/controllers/discussion/base.js
front/main/app/templates/discussion/error.hbs
front/main/app/templates/discussion/post-error.hbs
front/main/app/templates/discussion/reported-posts-error.hbs
front/main/app/templates/discussion/user-error.hbs

https://wikia-inc.atlassian.net/browse/SOC-2734
There were some erros back on error pages after reverting the new editor code
@bkoval

SOC-2734-after-editor | error pages fixed

---

server/app/views/_helpers/equal.js
server/app/views/_partials/global-footer/global-footer-image-header.hbs

* http://wikia-inc.atlassian.net/browse/XW-1719
@Wikia/x-wing

XW-1719 Respect API type

---

front/main/config/environment.js
front/main/npm-shrinkwrap.json
front/main/package.json

https://github.com/Wikia/mercury/pull/2620
@Wikia/x-wing

Release 259 new relic

---

front/main/app/index.html
front/main/app/styles/module/_loader.scss
server/app/views/_partials/loading-spinner.hbs

* http://wikia-inc.atlassian.net/browse/XW-1743
Adding spinner svg to markup rendered on server side before content generation.
@Wikia/x-wing

XW-1743 Add loading spinner before content render

---

server/app/facets/operations/page-data-helper.js
server/tests/unit/facets/operations/page-data-helper.js

* http://wikia-inc.atlassian.net/browse/XW-1074
@Wikia/x-wing

XW-1074 | don't show query params in html title

---

front/main/app/routes/discussion.js

Discussions | Removing empty then block

---

server/app/facets/mediawiki-page.js
server/app/facets/show-application.js
server/app/facets/show-curated-content.js
server/app/lib/mediawiki-page.js
server/app/lib/utils.js

content is set on:
- article page
- curated content
- discussions
- RWA

XW-1753 | set content lang

---

front/auth/views/_layouts/auth.hbs

https://wikia-inc.atlassian.net/browse/WW-91

WW-91 Provide entryPointWikiId var only when exists

---

front/main/bower.json
server/app/views/_partials/global-footer/global-footer-image-header.hbs
server/app/views/_partials/global-footer/global-footer-link-branded.hbs
server/app/views/_partials/global-footer/global-footer-link-image.hbs
server/app/views/_partials/global-footer/global-footer-link-text.hbs
server/app/views/_partials/global-footer/global-footer-section.hbs
server/app/views/_partials/global-footer/global-footer.hbs
server/tests/acceptance/global-footer.js
server/tests/fixtures/design-system/global-footer.html
server/tests/fixtures/design-system/global-footer.json

* https://wikia-inc.atlassian.net/browse/XW-1758
* https://github.com/Wikia/design-system/pull/21
@Wikia/x-wing

XW-1758 | Add wds- prefix

---

front/common/baseline/tracker-universal-analytics.js
front/common/utils/track.js
server/app/views/_partials/tracking-ua-auth.hbs
server/app/views/_partials/tracking-ua-init.hbs
server/app/views/_partials/tracking-ua.hbs
server/config/localSettings.base.js

* http://wikia-inc.atlassian.net/browse/XW-1733
* google analytics script is downloaded over https (google recommends)
* google script is loaded in head instead of after body (google recommends)
* events send before GA initializer are stored and resend after initializer
@Wikia/x-wing

XW-1733 | fix sending events to GA

---

npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/XW-1782
@Wikia/x-wing

XW-1782 | update Design System i18n to 0.0.10

---

server/config/localSettings.base.js

https://github.com/Wikia/mercury/pull/2665

XW-1786 | temporary get google script from http instead of https

---

server/config/localSettings.base.js

https://github.com/Wikia/mercury/pull/2665

XW-1786 | get google script from current protocol

---

front/common/public/locales/en/discussion.json
front/main/app/components/discussion-editor.js
front/main/app/components/discussion-inline-editor.js
front/main/app/components/discussion-multiple-inputs-editor.js
front/main/app/components/discussion-standalone-editor.js
front/main/app/components/discussion-textarea-with-counter.js
front/main/app/mixins/discussion-editor-configuration.js
front/main/app/styles/_settings.scss
front/main/app/styles/component/_discussion-inline-editor.scss
front/main/app/styles/component/_discussion-standalone-editor.scss
front/main/app/styles/theme/_dark.scss
front/main/app/templates/components/discussion-inline-editor.hbs
front/main/app/templates/components/discussion-standalone-editor.hbs
front/main/app/templates/components/discussion-textarea-with-counter.hbs
front/main/app/templates/discussion/forum.hbs
front/main/app/templates/discussion/post.hbs
front/main/app/templates/discussion/reported-posts.hbs
front/main/app/templates/discussion/user.hbs
front/main/app/utils/discussion-tracker.js

Revert "Revert "Merge pull request #2617 from Wikia/SOC-1914""

---

npm-shrinkwrap.json
package.json

https://wikia-inc.atlassian.net/browse/XW-1730
@Wikia/x-wing

XW-1730 | bump design-system-i18n to v0.0.11

---

front/main/app/controllers/discussion/base.js
front/main/app/templates/components/discussion-entities-list-layout.hbs
front/main/app/templates/discussion/user-error.hbs
front/main/app/templates/discussion/user.hbs

https://wikia-inc.atlassian.net/browse/SOC-2827
reported pages do not work
@bkoval @mleczey

SOC-2827 | reported pages do not work

---

front/common/utils/track.js
front/main/app/components/article-content.js
front/main/app/components/recirculation/footer.js
front/main/app/components/recirculation/incontent.js
front/main/app/index.html
front/main/app/mixins/recirculation-experiment.js
front/main/app/models/liftigniter.js
front/main/app/models/top-links.js
front/main/app/styles/component/_recirculation-experiment.scss
front/main/app/templates/components/recirculation/footer.hbs
front/main/tests/index.html
server/app/views/_partials/tracking-liftigniter.hbs

* https://wikia-inc.atlassian.net/browse/RECIRC-104
* https://liftigniter.readme.io/docs/introduction
Liftigniter is a content recommendation service that we have been seeing decent results with on desktop so we are extending the test to mobile. The experiment will be run for two weeks.
@Wikia/x-wing

RECIRC 104: Setup Liftigniter for placement test

---

front/common/utils/track.js
front/main/app/components/article-content.js
front/main/app/components/recirculation/footer.js
front/main/app/components/recirculation/incontent.js
front/main/app/index.html
front/main/app/mixins/recirculation-experiment.js
front/main/app/models/liftigniter.js
front/main/app/models/top-links.js
front/main/app/styles/component/_recirculation-experiment.scss
front/main/app/templates/components/recirculation/footer.hbs
front/main/tests/index.html
server/app/views/_partials/tracking-liftigniter.hbs

* https://wikia-inc.atlassian.net/browse/RECIRC-104
* #2659
Liftigniter is a content recommendation service that we have been seeing decent results with on desktop so we are extending the test to mobile. The experiment will be run for ~two weeks.
Reviewed and back-ported from #2659
@Wikia/x-wing

RECIRC-104: Setup Liftigniter placement test

---

front/main/app/components/wikia-footer.js
front/main/app/templates/components/wikia-footer.hbs
front/main/tests/unit/components/wikia-footer-test.js

* http://wikia-inc.atlassian.net/browse/XW-1812
We need to know the amount of clicks on the Full site link, so why not to check all links in current footer?
@Wikia/x-wing

XW-1812 | track footer clicks

---

front/common/baseline/load-dom-resource.js
front/main/bower.json
front/main/ember-cli-build.js

XW-1799 | Update DS version to 0.1.3

---

front/main/app/components/discussion-editor.js
front/main/app/components/discussion-guidelines-editor.js

Fix for guidelines and categories.
@bkoval

SOC fix for categories with guidelines

---

npm-shrinkwrap.json
package.json
server/app/views/_partials/global-footer/global-footer.hbs
server/tests/fixtures/design-system/global-footer.html
server/tests/fixtures/design-system/global-footer.json

* http://wikia-inc.atlassian.net/browse/XW-1741
@Wikia/x-wing

XW-1741 | add sitename and vertical to footer

---

front/main/app/styles/component/_discussion-categories-edit.scss

* http://wikia-inc.atlassian.net/browse/SOC-2800

SOC-2800 | Fixing X button sizing on iPhone

---

front/main/app/mixins/discussion-forum-actions-route.js
front/main/app/routes/discussion/forum.js
front/main/app/routes/discussion/index.js

Fix for previously stored query parameters as "null"
@bkoval

SOC-categories | fix: add object check

---

front/common/public/locales/de/discussion.json
front/common/public/locales/es/discussion.json
front/common/public/locales/it/discussion.json
front/common/public/locales/ja/discussion.json
front/common/public/locales/pl/discussion.json
front/common/public/locales/pt/discussion.json
front/common/public/locales/ru/discussion.json
front/common/public/locales/zh/discussion.json

* http://wikia-inc.atlassian.net/browse/SOC-2841

SOC-2841 | Remove "in" from "In <categoryname> for specific langs

---

front/main/bower.json
front/main/npm-shrinkwrap.json
npm-shrinkwrap.json
package.json

https://wikia-inc.atlassian.net/browse/XW-1859
@Wikia/x-wing

XW-1859 | update DS and DS-i18n

---

front/main/bower.json
npm-shrinkwrap.json
package.json

Revert "XW-1859 | update DS and DS-i18n"

---

front/main/app/styles/component/_global-footer.scss

* https://wikia-inc.atlassian.net/browse/XW-1873
Override mercury styles to make footer looks the same on all environments.
@Wikia/x-wing

XW-1873 | Normalize spacing on DS Global Footer for Mercury

---

npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/XW-1874
Updates strings and adds hyphenation defined for some of these strings as designated in Crowdin https://crowdin.com/translate/design-system.
@Wikia/x-wing

XW-1874 | update Wikia/design-system-i18n to 0.3.3

---

front/main/app/mixins/main-page-route.js
front/main/app/routes/wiki-page.js

* https://github.com/Wikia/app/pull/11150
Change dimension14 (hasAds) from `yes` and `no` to `Yes` and `No`. This way it's consistent with desktop
@Wikia/adeng

ADEN | change yes to Yes

---

front/main/app/controllers/discussion/base.js

add missing method 'uploadDiscussionHeader' in base controller
@bkoval

fix: add missing method 'uploadDiscussionHeader' in base controller

---

front/main/app/controllers/discussion/base.js

add missing method 'uploadDiscussionHeader' in base controller
@bkoval

fix: fix for discussion header

---

front/main/app/initializers/global-footer.js

* http://wikia-inc.atlassian.net/browse/XW-1882
@Wikia/x-wing

XW-1882 | send track event on click only (links in global footer)

---

front/main/app/styles/module/_loader.scss

Fix for the choppy animation in spinner - let's use client's GPU
@Wikia/x-wing

Make use of GPU

---

front/main/config/environment.js

update new relic agent

---

front/main/app/styles/module/_ads.scss
front/main/app/templates/components/ads/invisible-high-impact-2.hbs

* http://wikia-inc.atlassian.net/browse/ADEN-3777
* https://github.com/Wikia/mercury/pull/2734

Aden 3777 interstitial prod ready - release

---

front/main/app/models/discussion/forum.js
front/main/app/routes/discussion/forum.js

* http://wikia-inc.atlassian.net/browse/SOC-3003

SOC-3003 | Preserve categories choice when loading more posts

---

front/main/app/controllers/discussion/forum.js
front/main/app/mixins/discussion-forum-actions-route.js
front/main/app/models/discussion/forum.js
front/main/app/routes/discussion/forum.js

* http://wikia-inc.atlassian.net/browse/SOC-2973

SOC-2973 | Comma notation for categories in the URL

---

front/main/app/styles/component/_discussion-dialog.scss

* https://wikia-inc.atlassian.net/browse/SOC-3027
discussions modal dialog footer now respects buttons height
@bkoval

SOC-3027 | discussions modal dialog footer now respects buttons height

---

front/main/app/controllers/discussion/forum.js
front/main/app/mixins/discussion-forum-actions-route.js
front/main/app/models/discussion/forum.js
front/main/app/routes/discussion/forum.js

* http://wikia-inc.atlassian.net/browse/SOC-2973

Soc 2973 | New Categories urls schema for Discussions

---

front/main/app/routes/discussion/forum.js
front/main/app/routes/discussion/index.js

* https://wikia-inc.atlassian.net/browse/SOC-3038
When deleting categories, deleted category stays in url
@bkoval

SOC-3038 | When deleting categories, deleted category stays in url

---

front/main/app/routes/discussion/forum.js

Discussions | LocalStorage polluted param fix

---

front/main/app/components/site-head-fandom-bar.js

* no links
It should be visible on all languages
@Wikia/x-wing

show fandom bar on all languages

---

front/main/app/styles/_settings.scss
front/main/app/styles/component/_discussion-widget.scss

* https://wikia-inc.atlassian.net/browse/JPN-584
A style to use for showing error messages when the <discussions /> tag can not be rendered due to incorrect parameters (e.g. setting columns=foo, where it should be either 1 or 2)
@rogatty @bkoval

JPN-584 Style for discussions widget error messages

---

front/main/app/styles/module/_ads.scss

* http://wikia-inc.atlassian.net/browse/ADEN-3890
Floor Adhesion wasn't worknig with different sizes. With this change it should look fine with different creatives
@v3rth

ADEN-3890 | make floor adhesion work with different sizes

---

front/main/app/components/design-system/global-navigation.js
front/main/app/components/design-system/wds-dropdown.js
front/main/app/templates/components/design-system/global-navigation-account-navigation.hbs
front/main/app/templates/components/design-system/global-navigation-dropdown.hbs
front/main/app/templates/components/design-system/global-navigation-links.hbs
front/main/app/templates/components/design-system/global-navigation.hbs
front/main/package.json

* https://wikia-inc.atlassian.net/browse/XW-1691
PR to ember-rl-dropdown: https://github.com/RSSchermer/ember-rl-dropdown/pull/17
@Wikia/x-wing

use events from ember-rl-dropdown to activate/deactivate peek-a-boo

---

front/main/bower.json

XW-2018 | updated DS version

---

front/main/app/components/design-system/global-navigation-link-authentication.js
front/main/app/templates/components/design-system/global-navigation-link-authentication.hbs

* http://wikia-inc.atlassian.net/browse/XW-2048
Support the redirect parameter in authentication links. The returnto parameter doesn't currently support
Discussions, so we're leaving it out for now.
/cc @Wikia/x-wing

XW-2048 | Support redirect parameter in authentication links

---

front/main/mirage/config.js
front/main/tests/.eslintrc
front/main/tests/acceptance/search-test.js
front/main/tests/helpers/mock-service.js
front/main/tests/helpers/start-app.js

* https://wikia-inc.atlassian.net/browse/XW-2034
We render the old search only on the mobile breakpoint. Let's make sure that it doesn't break the tests when run in a desktop browser.
@Wikia/x-wing

XW-2034 | Fix the search acceptance test

---

front/main/app/components/design-system/global-navigation-link.js
npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/XW-1965
@Wikia/x-wing

XW-1965 | Update DS version

---

front/common/modules/video-loader.js
front/main/app/components/lightbox-video.js

Fix ooyala no ads parameter
* http://wikia-inc.atlassian.net/browse/ADEN-4008

ADEN-4008 Fix ooyala no ads parameter

---

front/main/app/components/design-system/global-navigation-link-branded.js
front/main/app/components/design-system/global-navigation-link-dropdown.js
front/main/app/components/design-system/global-navigation-link.js
front/main/app/components/design-system/global-navigation-search.js
front/main/app/components/design-system/global-navigation.js
front/main/app/templates/components/design-system/global-navigation-account-navigation.hbs
front/main/app/templates/components/design-system/global-navigation-dropdown.hbs
front/main/app/templates/components/design-system/global-navigation-link-authentication.hbs
front/main/app/templates/components/design-system/global-navigation-links.hbs
front/main/app/templates/components/design-system/global-navigation.hbs

* https://wikia-inc.atlassian.net/browse/XW-1727
@Wikia/x-wing

XW-1727 | Click tracking on Global Navigation

---

server/app/lib/mediawiki.js

* https://wikia-inc.atlassian.net/browse/XW-2083
For better performance use icache for DS API requests
@Wikia/x-wing

XW-2083 | Use icache for DS API

---

front/main/app/components/application-wrapper.js
front/main/app/components/site-head.js
front/main/app/templates/components/application-wrapper.hbs

* https://wikia-inc.atlassian.net/browse/XW-2087
* https://wikia-inc.atlassian.net/browse/XW-2097
Use the DS API to get the homepage URL.
@Wikia/x-wing

XW-2087 Link logo to the URL from DS API

---

front/main/npm-shrinkwrap.json
front/main/package.json

* http://wikia-inc.atlassian.net/browse/XW-2062
* https://github.com/Wikia/app/pull/11418
* https://github.com/Wikia/ember-rl-dropdown/pull/2
@Wikia/x-wing

XW-2062 | fix Firefox bug which was preventing dropdowns in global navigation to close when search input was focused

---

front/main/app/mixins/discussion-contribution-controller.js

* https://wikia-inc.atlassian.net/browse/SOC-3033
As a user, I want my category filters updated if I create a post in a different category
@bkoval

SOC-3033 | feat: select category if category in new post is not selected

---

server/app/lib/logger.js

* https://wikia-inc.atlassian.net/browse/XW-1970
We don't care about name, but this is needed for bunyan
@Wikia/x-wing

add appname to logs

---

front/main/app/components/discussion-inline-post-editor.js
front/main/app/mixins/discussion-sticky-component.js
front/main/app/templates/components/discussion-hero-unit.hbs
front/main/app/templates/components/discussion-inline-editor.hbs

* http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes
Fixes:
```
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.
```
@Wikia/x-wing @Wikia/social-frontend

Fix warnings about binding style attributes

---

server/app/lib/utils.js
server/tests/unit/lib/utils.js

* On Stable Env. Global Navigation and Footer are not working on Mercury
Make Mercury server understand the stable environment, so Discussions can function properly on `stable.wikiname.wikia.com`.
@Wikia/x-wing

XW-2113 | add `stable` environment type to server

---

front/main/bower.json

XW-2108 | updated ds version to 0.14.0

---

npm-shrinkwrap.json
package.json
server/tests/fixtures/design-system/global-footer.html
server/tests/fixtures/design-system/global-footer.json

* http://wikia-inc.atlassian.net/browse/XW-1936
* https://github.com/Wikia/app/pull/11473
@Wikia/x-wing

XW-1936 | remove 'API' link from global footer

---

front/main/bower.json

* https://wikia-inc.atlassian.net/browse/XW-2140
* https://github.com/Wikia/design-system/pull/74
* https://github.com/Wikia/app/pull/11489
@Wikia/x-wing

XW-2140 | button :focus state fix

---

server/app/views/_partials/global-footer/global-footer.hbs

* https://github.com/Wikia/mercury/pull/2835

release-280 | XW-2136 | fixed title in footer logo link

---

front/auth/views/auth/desktop/modal-message.hbs
server/app/facets/auth/auth-view.js

* http://wikia-inc.atlassian.net/browse/SOC-2848

SOC-2848 | Redirect to redirect when already logged in

---

front/main/app/styles/component/_site-head.scss

https://github.com/Wikia/mercury/pull/2838

release-280 | XW-2151 | add width CSS prop to mobile logo

---

front/main/app/styles/component/_site-head.scss

* http://wikia-inc.atlassian.net/browse/XW-2151
@Wikia/x-wing

XW-2151 | add width CSS prop to mobile logo

---

npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/XW-2147
@Wikia/x-wing

XW-2147 | use DS-i18n v0.6.2

---

front/main/bower.json

Ticket: https://wikia-inc.atlassian.net/browse/XW-2158
Incorporates changes from: https://github.com/Wikia/design-system/pull/75
Is a sibling to: https://github.com/Wikia/app/pull/11532
@Wikia/x-wing 
Smooth consistency. 😉 
@Wikia/x-wing

XW-2158 | Unify hover animations in Global Navigation

---

front/common/public/locales/es/auth-front.json
front/common/public/locales/es/auth.json
front/common/public/locales/zh-hans/auth.json
front/common/public/locales/zh/auth.json

Social | Last auth i18n update before rebranding release

---

front/main/app/components/widget-discussions.js

* https://wikia-inc.atlassian.net/browse/JPN-660
Support for filtering by multiple categories. Goes together with this PR for Oasis:
https://github.com/Wikia/app/pull/11559
@Warkot @bkoval @rogatty

JPN-660 Support for filtering by multiple categories in discussions tag

---

front/auth/views/auth/desktop/modal-message.hbs

* http://wikia-inc.atlassian.net/browse/SOC-2744

SOC-2744 | parent -> opener

---

server/app/lib/open-graph.js

* http://wikia-inc.atlassian.net/browse/SOC-3172
Fixes a crash when loading a post page directly.

SOC-3172 - fix open-graph.js

---

front/main/app/templates/components/discussion-post-card-actions.hbs
front/main/app/templates/components/discussion-post-card-detail.hbs
front/main/npm-shrinkwrap.json
front/main/package.json

* https://wikia-inc.atlassian.net/browse/SOC-3188
Replaced link-to with href-to helper. Replacing it increased speed of rendering by over 30%.

SOC-3188 | increasing speed of rendering post component

---

front/main/app/models/discussion/categories.js

* https://wikia-inc.atlassian.net/browse/SOC-3206
Set name property for created category so it should be the same as displayName property

SOC-3206 | fix: prevent unnecessary update calls after create category

---

front/main/app/styles/_settings.scss
front/main/app/styles/module/_discussion.scss
front/main/app/styles/theme/_dark.scss
front/main/app/templates/components/discussion-post-card-actions.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3190
Revert community color for upvote. Once again it is gold.

SOC-3190 | fix: revert community color for upvote

---

front/main/app/mixins/discussion-contribution-controller.js
front/main/app/utils/discussion-tracker.js

* https://wikia-inc.atlassian.net/browse/SOC-3207
Sign in modal for logged out user when clicking on follow.

SOC-3207 | sign in modal for logged out user when clicking on follow

---

front/common/modules/ads.js

Hot fix for tracking mercuryPV key-val in DFP.

ADEN | fix mercury pv

---

front/main/app/styles/component/discussion/_discussion-community-badge.scss

* https://wikia-inc.atlassian.net/browse/WW-455
* https://wikia-inc.atlassian.net/browse/WW-435
Overwrite `cursor: pointer` set for elements with action

WW-455: Move css cursor property

---

front/main/app/templates/components/discussion-reported-posts-wrapper.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3269
Zero state fix.

SOC-3269 | /d/reported zero state fix

---

front/main/app/templates/components/discussion-contributors.hbs
front/main/app/templates/components/discussion-side-button.hbs

* https://wikia-inc.atlassian.net/browse/WW-454
* https://wikia-inc.atlassian.net/browse/WW-435
Fix links to user profile.

WW-454: Fix wrapped links

---

front/common/public/locales/en/discussion.json
front/main/app/mixins/discussion-contribution-model.js
front/main/app/styles/_settings.scss
front/main/app/styles/component/discussion/_discussion-alert-notification.scss
front/main/app/styles/component/discussion/index.scss

- https://wikia-inc.atlassian.net/browse/SOC-3205
Add error message when following not succeeded

SOC-3205 | feat: add error message when following not succeeded

---

front/main/app/styles/_settings.scss
front/main/app/styles/component/discussion/_discussion-introducing-following.scss

* https://wikia-inc.atlassian.net/browse/SOC-3196
Changes after design review

SOC-3196 | changes in css after design review

---

front/main/app/templates/components/design-system/global-navigation-dropdown.hbs
front/main/bower.json

* https://wikia-inc.atlassian.net/browse/XW-2209
Newest version of DS removes square avatars so we're removing this class.
@Wikia/x-wing

XW-2209 | Update to new DS version

---

front/main/app/styles/component/discussion/_discussion-share-dialog.scss
front/main/app/styles/module/_discussion.scss
front/main/app/templates/components/discussion-more-options.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3191
Change more option icons to design system icons

SOC-3191 | refactor: change more option icons to design system icons

---

front/main/app/styles/component/discussion/_discussion-introducing-following.scss

* https://wikia-inc.atlassian.net/browse/SOC-3196
font-size fix

SOC-3196 | headline font-size fix

---

server/app/app.js

* https://wikia-inc.atlassian.net/browse/XW-2228
* http://hapijs.com/api/9.5.1#request-logs
Filter out unactionable items from `Internal error` logs and make the message more unique so Error Reporter can distinguish between them.
Before this clean up we had 577026 errors logged in the last 7 days.
After, there are only 19 errors in the last 30 days, see https://kibana.wikia-inc.com/index.html#dashboard/temp/AVgrDzevAinGJK4D_Zbz.
@hakubo @Wikia/x-wing

XW-2228 | Clean up "internal error" logs

---

front/main/app/components/discussion-entities-list-layout.js
front/main/app/components/discussion-filters.js
front/main/app/components/discussion-header.js
front/main/app/components/discussion-sort.js
front/main/app/mixins/discussion-forum-model-static.js
front/main/app/mixins/discussion-forum-model.js
front/main/app/models/discussion/follow.js
front/main/app/routes/discussion/follow.js
front/main/app/services/discussion-sort.js
front/main/app/styles/_settings.scss
front/main/app/styles/component/discussion/_discussion-categories.scss
front/main/app/styles/component/discussion/_discussion-filters.scss
front/main/app/styles/component/discussion/_discussion-no-followed-posts.scss
front/main/app/styles/component/discussion/_discussion-sort.scss
front/main/app/styles/mixin/discussion/discussion-radio-fancy.scss
front/main/app/styles/theme/_dark.scss
front/main/app/templates/components/discussion-entities-list-layout.hbs
front/main/app/templates/components/discussion-filters.hbs
front/main/app/templates/components/discussion-header.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3193
* https://wikia-inc.atlassian.net/browse/SOC-3194
Fixes and refactor after design review

SOC-3193 | Fixes and refactor after design review

---

front/common/public/locales/en/image-review.json
front/main/app/controllers/image-review/summary.js
front/main/app/models/image-review/index.js
front/main/app/models/image-review/summary.js
front/main/app/routes/image-review/index.js
front/main/app/routes/image-review/summary.js
front/main/app/templates/components/image-review-summary.hbs
front/main/app/templates/image-review/summary.hbs

* http://wikia-inc.atlassian.net/browse/SER-340
Added a download as csv button, which connects to the csv endpoint.
@sqreek

SER-340 added csv download button

---

front/main/app/models/user.js
front/main/app/routes/discussion/forum.js
front/main/app/routes/discussion/index.js
front/main/app/services/discussion-sort.js

* https://wikia-inc.atlassian.net/browse/SOC-3194
change default sorting to latest

SOC-3194 | change default sorting to latest

---

front/main/app/models/image-review/summary.js

* http://wikia-inc.atlassian.net/browse/SER-340
Model properties need to be set by a setter, not directly.
@nikodamn

SER-340 fixed setting start and end dates in model

---

front/main/app/mixins/discussion-moderation-model.js

* https://wikia-inc.atlassian.net/browse/SOC-3353
Using ember getters

SOC-3353 | fixing moderation model, using ember getter

---

front/main/app/styles/module/_ads.scss

* https://wikia-inc.atlassian.net/browse/ADEN-4194
• fix IMA lib styles for video tag in VUAP
• remove redundant styles

ADEN-4156 Fix IMA lib styles for video tag.

---

front/main/app/components/discussion-post-list.js
front/main/app/styles/component/_smoke-and-mirrors.scss
front/main/app/styles/component/index.scss
front/main/app/templates/components/discussion-forum-wrapper.hbs
front/main/app/templates/components/discussion-post-list.hbs
front/main/npm-shrinkwrap.json
front/main/package.json

* https://wikia-inc.atlassian.net/browse/SOC-3168
Implementing smoke and mirrors component for mobile

SOC-3168 | smoke and mirrors component for mobile

---

front/auth/app/styles/app.scss
front/auth/app/styles/layout/_body.scss
front/main/app/styles/base/_body.scss
front/main/app/styles/component/design-system/_wikia-styleguide-overrides.scss
front/main/bower.json
server/app/views/_layouts/error.hbs

* using $wds-font-family for defining body font family
https://wikia-inc.atlassian.net/browse/XW-2203

XW-2203 | using DS variable for body font family

---

front/main/app/styles/component/discussion/_discussion-guidelines.scss
front/main/app/styles/module/_discussion.scss

* http://wikia-inc.atlassian.net/browse/SOC-3237

SOC-3237 | fix: minor upvote arrow fix

---

front/common/public/locales/de/discussion.json
front/common/public/locales/en/discussion.json
front/common/public/locales/es/discussion.json
front/common/public/locales/fi/discussion.json
front/common/public/locales/fr/discussion.json
front/common/public/locales/it/discussion.json
front/common/public/locales/ja/discussion.json
front/common/public/locales/ko/discussion.json
front/common/public/locales/nl/discussion.json
front/common/public/locales/pl/discussion.json
front/common/public/locales/pt-pt/discussion.json
front/common/public/locales/pt/discussion.json
front/common/public/locales/ru/discussion.json
front/common/public/locales/sv-se/discussion.json
front/common/public/locales/vi/discussion.json
front/common/public/locales/zh-hans/discussion.json
front/common/public/locales/zh/discussion.json
front/main/app/components/discussion-post-card-detail.js
front/main/app/models/discussion/domain/contributor.js
front/main/app/models/discussion/domain/post.js
front/main/app/styles/module/_discussion.scss
front/main/app/templates/components/discussion-post-card-detail.hbs
front/main/app/templates/components/discussion-post.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3218
As a user, I want to see an indicator than my post or reply was edited by a admin+

SOC-3218 | As a user, I want to see an indicator than my post or reply was edited by a admin+

---

front/main/app/components/discussion-header.js
front/main/app/templates/components/discussion-header.hbs

* https://wikia-inc.atlassian.net/browse/SOC-2614
Fixing problem with filter button on mobile - dynamic element id

SOC-2614 | Fixing problem with filter button on mobile - dynamic element id

---

front/common/public/locales/en/image-review.json
front/main/app/models/image-review/index.js
front/main/app/routes/image-review/index.js
front/main/app/templates/components/image-review-item.hbs
front/main/app/templates/components/image-review.hbs

* http://wikia-inc.atlassian.net/browse/SER-534
Simple change - we want reviewers to remove images instead of rejecting them.
@sqreek 
@tmszdmsk 
@africazulu

SER-534 changed REJ->DEL for reviewers

---

front/main/app/components/image-review-item.js
front/main/app/models/image-review/index.js

* http://wikia-inc.atlassian.net/browse/SER-604
Changing frontend to add ?status=REJECTED to rejected images, so they can be shown.
@sqreek 
@africazulu 
@tmszdmsk

SER-604 allow to display images in rejected queue after vignette change

---

front/main/app/routes/discussion/user.js

* https://wikia-inc.atlassian.net/browse/SOC-3253

SOC-3253 | set robots meta tag to noindex for posts by user page

---

front/main/app/models/image-review/image-review-item.js

* https://wikia-inc.atlassian.net/browse/SER-605
We changed api inimage-review service.
This PR update those path on frontend side 

SER-605 In image-review use new path for image-review service

---

front/main/app/styles/module/_ads.scss

* http://wikia-inc.atlassian.net/browse/ADEN-4183

ADEN-4183 Animate VUAP on Mercury.

---

front/main/app/routes/discussion/base.js

* http://wikia-inc.atlassian.net/browse/SOC-1975
Follow-up fix: Use declared var.
@igor @Wikia/social-frontend

SOC-1975 | Use a declared var

---

front/main/app/services/modal-dialog.js

* https://wikia-inc.atlassian.net/browse/SOC-3602
Allow anons to see sign in popup.

SOC-3602 | fix: allow anons to see sign in popup

---

front/main/app/routes/discussion/base.js
front/main/app/services/modal-dialog.js

* https://wikia-inc.atlassian.net/browse/SOC-3602
Allow anon to see sing in pop up.

SOC-3602 | fix: allow anon to see sing in popup

---

front/main/app/mixins/discussion-contribution-model.js
front/main/app/mixins/discussion-forum-model-static.js
front/main/app/mixins/discussion-forum-model.js
front/main/app/models/discussion/domain/open-graph.js
front/main/app/models/discussion/domain/post.js
front/main/app/models/discussion/domain/user-data.js
front/main/app/models/discussion/follow.js
front/main/app/models/discussion/forum.js
front/main/app/templates/components/discussion-forum-wrapper.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3195
Integration with backend

SOC-3195 | followed by post list backend integration

---

front/main/app/styles/module/_ads.scss

* https://wikia-inc.atlassian.net/browse/ADEN-4182
Add to BFAB slot video ad

ADEN-4182 Move BFAA video to left

---

server/app/app.js

* https://wikia-inc.atlassian.net/browse/XW-2306
Don't log errors on 404s for static assets
@Wikia/x-wing

XW-2306 | Don't log 404 for static assets

---

front/main/app/components/discussion-wrapper-load-more.js
front/main/app/mixins/discussion-forum-head-tags.js
front/main/app/mixins/head-tags-dynamic.js
front/main/app/routes/discussion/forum.js
front/main/app/services/discussion-seo-url-builder.js
front/main/app/styles/module/_discussion.scss
front/main/app/templates/components/discussion-forum-wrapper.hbs
front/main/app/templates/components/discussion-wrapper-load-more.hbs
front/main/app/templates/head.hbs

* https://wikia-inc.atlassian.net/browse/SOC-1976
Adding link next and prev tags
Replace load more button div with <a> element

SOC-1976 | As a bot, I want to be able to read all pages of posts on the post list

---

front/main/app/routes/discussion/forum.js

* https://wikia-inc.atlassian.net/browse/SOC-3622
Catches error while transitioning form /d/f page, due to error in Ember.
@Wikia/social-frontend 
@rogatty

SOC-3622 | fix: catch excpetion due to error in Ember

---

front/main/app/components/discussion-lightbox.js
front/main/app/components/discussion-post-image.js
front/main/app/components/discussion-post-images.js
front/main/app/components/discussion-standalone-editor.js
front/main/app/models/discussion/domain/content-images.js
front/main/app/models/discussion/domain/post.js
front/main/app/models/discussion/domain/reply.js
front/main/app/styles/component/discussion/_discussion-post-image.scss
front/main/app/styles/component/discussion/_discussion-post-images.scss
front/main/app/styles/component/discussion/_discussion-standalone-editor.scss
front/main/app/styles/component/discussion/index.scss
front/main/app/styles/module/_discussion.scss
front/main/app/templates/components/discussion-lightbox.hbs
front/main/app/templates/components/discussion-post-image.hbs
front/main/app/templates/components/discussion-post-images.hbs
front/main/app/templates/components/discussion-standalone-editor.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3395
As a user, I want to delete an image upload from the bottom of my post or reply.

SOC-3395 | As a user, I want to delete an image upload from the bottom of my post or reply.

---

front/main/app/components/discussion-more-options.js
front/main/app/controllers/discussion/follow.js
front/main/app/controllers/discussion/forum.js
front/main/app/mixins/discussion-contribution-controller.js
front/main/app/templates/components/discussion-post-card-detail.hbs
front/main/app/templates/components/discussion-post.hbs
front/main/app/templates/discussion/post.hbs

* https://wikia-inc.atlassian.net/browse/SOC-3677
As a user I don't want to see the "Add to your following list" message anymore, when I'm already following post by default

SOC-3677 | As a user I don't want to see the "Add to your following list" message anymore, when I'm already following post by default

---

front/main/app/templates/components/infobox-builder-item-section-header.hbs
front/main/npm-shrinkwrap.json
front/main/package.json

* https://wikia-inc.atlassian.net/browse/MAIN-8926
Need to add extra parameter to pop-over
@Wikia/social-frontend 
@Wikia/x-wing

MAIN-8926 | fix pop-over in infobox component

---

front/main/bower.json

* http://wikia-inc.atlassian.net/browse/XW-2290
update Design System
@Wikia/x-wing

XW-2290 | update Design System

---

front/main/app/components/image-review.js
front/main/app/routes/image-review/index.js

* http://wikia-inc.atlassian.net/browse/SER-621
Reset focus on each model load to prevent space button to repeat reviewing images (or any other action)
@sqreek @pwojcik86

SER-621 reset focus on model load

---

server/app/facets/auth/auth-view.js
server/app/lib/auth-utils.js
server/npm-shrinkwrap.json
server/package.json

* https://wikia-inc.atlassian.net/browse/SOC-3750
We need to validate if redirect param is a valid URL

SOC-3750 | fix XSS vulnerability - fixing redirectURL validation

---

server/app/facets/auth/auth-view.js
server/app/lib/auth-utils.js
server/npm-shrinkwrap.json
server/package.json

https://wikia-inc.atlassian.net/browse/SOC-3750

SOC-3750 | Reflected XSS vulnerability in auth pages

---

front/common/public/locales/en/image-review.json

* http://wikia-inc.atlassian.net/browse/SER-623
Changed description text in image-review.

SER-623 changed text in description

---

front/common/public/locales/en/image-review.json
front/main/app/styles/component/_image-review.scss
front/main/app/templates/components/image-review.hbs

* http://wikia-inc.atlassian.net/browse/SER-626
Moving queue switching buttons to the top to keep consistency with old image-review.

SER-626 moved queue buttons to the top

---

front/main/app/styles/module/_ads.scss

* https://wikia-inc.atlassian.net/browse/ADEN-4362
* Example of video Fan Takeover: http://project43.wikia.com/wiki/SyntheticTests/VUAP
* Example of video Fan Takeover with Playwire: http://project43.wikia.com/wiki/SyntheticTests/VUAP/RougeOne
* Follow-up clean-up story: https://wikia-inc.atlassian.net/browse/ADEN-4430
Added usage of Playwire player for video Fan Takeover on mobile.

ADEN-4362 Playwire player in video Fan Takeover

---

front/main/bower.json

* https://wikia-inc.atlassian.net/browse/XW-2453
update design system version; fix svg gradients on firefox
@Wikia/x-wing

XW-2453 | update design system version; fix svg gradients on firefox

---

front/common/public/locales/en/image-review.json
front/main/app/controllers/image-review/index.js
front/main/app/models/image-review/index.js
front/main/app/models/image-review/summary.js
front/main/app/routes/image-review/index.js
front/main/app/styles/component/_image-review.scss
front/main/app/templates/components/image-review-summary.hbs
front/main/app/templates/components/image-review.hbs
front/main/app/templates/image-review/index.hbs

* http://wikia-inc.atlassian.net/browse/SER-669
This PR adds a source selector in `image-review` which will allow to reserve a batch of images that came from the same source service/application (e. g. discussions).

SER-669 source selection in image-review

---

front/main/app/mixins/discussion-parsed-content.js
front/main/bower.json

* http://wikia-inc.atlassian.net/browse/SOC-3392

SOC-3392 | fix links with UTF-8 by upgrading Autolinker

---

front/main/app/mixins/discussion-parsed-content.js

* http://wikia-inc.atlassian.net/browse/SOC-3558

SOC-3558 | decode UTF stuff before displaying it

---

server/config/settings.dev.js

Temporarily revert new dev domains changes until all the other pieces go live.
@garthwebb

Temporarily revert new dev domains changes

---

server/app/facets/auth/auth-view.js

* http://wikia-inc.atlassian.net/browse/SOC-3803
@Wikia/social-frontend @Wikia/social-backend

SOC-3803 | Prevent evil redirects and add new dev domains

---

front/main/app/mixins/discussion-moderation-model.js
front/main/app/routes/discussion/follow.js

* http://wikia-inc.atlassian.net/browse/SOC-3752

SOC-3752 removing obsolete body when reporting and validating a report

---

front/main/app/mixins/discussion-parsed-content.js

Revert "SOC-3558 | decode UTF stuff before displaying it"

---

front/main/app/mixins/discussion-parsed-content.js

* http://wikia-inc.atlassian.net/browse/SOC-3558

SOC-3558 decode only the URL

---

server/config/settings.dev.js

* http://wikia-inc.atlassian.net/browse/PLATFORM-887
Restore new dev domain changes for wikia-dev.us/pl split.
This reverts commit 67a942682d816fd5882b704e0ab1b368b18da90f.
@Wikia/core-platform-team

(PLATFORM-887) Restore new dev domains changes

---

front/main/app/styles/module/article/_portable-infobox.scss

* https://wikia-inc.atlassian.net/browse/XW-2602
fix labels height in PI flex groups
@idradm @rybmat

XW-2602 | fix labels height in PI flex groups

---

front/main/app/components/image-review-item.js
front/main/app/components/image-review.js
front/main/app/controllers/image-review/coppa/index.js
front/main/app/controllers/image-review/coppa/user-images.js
front/main/app/models/image-review/batch-id.js
front/main/app/models/image-review/summary.js
front/main/app/models/image-review/user-images.js
front/main/app/router.js
front/main/app/routes/image-review/coppa/index.js
front/main/app/routes/image-review/coppa/user-images.js
front/main/app/routes/image-review/summary.js
front/main/app/styles/component/_image-review.scss
front/main/app/templates/components/image-review-item.hbs
front/main/app/templates/components/image-review-summary.hbs
front/main/app/templates/components/image-review.hbs
front/main/app/templates/image-review/coppa/index.hbs
front/main/app/templates/image-review/coppa/user-images.hbs
server/app/routes.js

* http://wikia-inc.atlassian.net/browse/SER-731
Added a new view to `image-review`, which shows all images uploaded by a specific user, and allows to remove them.

SER-731 add COPPA image review

---

front/main/app/models/discussion/domain/post.js

* http://wikia-inc.atlassian.net/browse/JIRA-3897
@slayful

SOC-3897 | Bringing back lastEditedBy

---

server/app/lib/mediawiki.js

Hotfix | explicitly pass wikiDomain

---

front/main/app/styles/module/_ads.scss

* http://wikia-inc.atlassian.net/browse/ADEN-4603
Replace porvata player icons to more consistent with other cross-platform players

ADEN-4603 Replace player icons

---

server/app/lib/tracking.js
server/app/views/_partials/tracking-comscore.hbs
server/app/views/_partials/tracking-pixels.hbs

Backporting https://github.com/Wikia/mercury/pull/3063

XW-2750 | Comscore - start using c7Value

---

README.md
front/common/baseline/build-url.js
front/common/tests/unit/baseline/build-url.js
front/main/mirage/config.js
front/main/mirage/fixtures/discussion-user-activity-moderations.js
front/main/mirage/fixtures/discussion-user-activity-posts.js
front/main/mirage/fixtures/discussion-user-activity-reports.js
front/main/tests/unit/utils/domain-test.js
server/app/facets/auth/auth-view.js
server/app/lib/utils.js
server/config/settings.dev.js
server/tests/acceptance/wiki-page.js
server/tests/unit/facets/auth/auth-view.js
server/tests/unit/lib/mediawiki.js
server/tests/unit/lib/prerender.js
server/tests/unit/lib/utils.js

* https://wikia-inc.atlassian.net/browse/XW-2627
Removing all occurencies of wikia-dev.com to remove later confusement.

rename wikia-dev.com to wikia-dev.[us|pl]

---

front/main/app/components/wikia-in-your-lang.js
front/main/app/mixins/alert-notifications.js

* https://wikia-inc.atlassian.net/browse/XW-2644

XW-2644 | use default info alert-box for wikia-in-your-lang

---

front/main/app/mixins/discussion-parsed-content.js

* http://wikia-inc.atlassian.net/browse/IRIS-4002
@slayful

IRIS-4002 | Watch out for content field (guidelines content)

---

server/app/lib/wikia-session.js

* http://wikia-inc.atlassian.net/browse/XW-2828

XW-2828 | Don't log connection and parse errors together

---

front/common/public/locales/de/discussion.json
front/common/public/locales/en/discussion.json
front/common/public/locales/es/discussion.json
front/common/public/locales/fi/discussion.json
front/common/public/locales/fr/discussion.json
front/common/public/locales/it/discussion.json
front/common/public/locales/ja/discussion.json
front/common/public/locales/ko/discussion.json
front/common/public/locales/nl/discussion.json
front/common/public/locales/pl/discussion.json
front/common/public/locales/pt-pt/discussion.json
front/common/public/locales/pt/discussion.json
front/common/public/locales/ru/discussion.json
front/common/public/locales/sv-se/discussion.json
front/common/public/locales/vi/discussion.json
front/common/public/locales/zh-hans/discussion.json
front/common/public/locales/zh/discussion.json
front/main/app/components/notification-card.js
front/main/app/mixins/new-reply-notification.js
front/main/app/mixins/post-upvote-notification.js
front/main/app/mixins/reply-upvote-notification.js
front/main/app/templates/components/design-system/global-navigation-notifications.hbs
front/main/app/templates/components/wikia-user-profile.hbs
front/main/bower.json
npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/IRIS-4104

IRIS-4104 | Remove the translations from Mercury

---

front/main/app/styles/module/_ads.scss

* https://wikia-inc.atlassian.net/browse/ADEN-4832
InvisibleHighImpact Interstitial ad has broken layout on wikia mobile

ADEN-4832 | InvisibleHighImpact Interstitial ad has broken layout on wikia mobile

---

npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/IRIS-4157

IRIS-4157 | Re-pull translations for up vote notifications (for OSN)

---

front/main/app/components/wikia-nav.js
front/main/app/templates/components/wikia-nav.hbs
npm-shrinkwrap.json
package.json

* http://wikia-inc.atlassian.net/browse/IRIS-4169 - this will revert to Username + Logout button in wiki-nav (the drawer) when On Site Notifications are not enabled
* http://wikia-inc.atlassian.net/browse/IRIS-4157 - this will modify the On Site Notification strings (which won't be visible until OSN are enabled)

IRIS-4169 + IRIS-4157 - Feature toggle will not modify wiki-nav + pull i18n for OSN

---

front/main/app/components/wikia-nav.js
front/main/app/templates/components/wikia-nav.hbs

* http://wikia-inc.atlassian.net/browse/IRIS-4169

IRIS-4169 | OSN feature flag does not affect wikia-nav

---

front/main/app/models/discussion/domain/post.js
front/main/app/models/discussion/domain/reply.js

* http://wikia-inc.atlassian.net/browse/IRIS-4171

IRIS-4171 | Fix OpenGraph in Following

---

server/app/views/_partials/tracking-quantserve.hbs

ADEN-4803 Fix Quantcast tracking for consecutive page views
* https://wikia-inc.atlassian.net/browse/ADEN-4803
* https://github.com/Wikia/mobile-wiki/pull/36
* https://github.com/Wikia/mobile-wiki/pull/37
Fixes Quantcast tracking for consecutive page views.
@Wikia/x-wing

ADEN-4803 Fixed Quantcast tracking for consecutive pageviews

---

crowdin/auth-front.conf
crowdin/auth.conf
crowdin/discussion.conf
crowdin/image-review.conf
crowdin/infobox-builder.conf
crowdin/main.conf
crowdin/search.conf

* http://wikia-inc.atlassian.net/browse/SER-795
Added new product person field to i18n crowdin config files
@pwojcik86

SER-795 Added product_person field to i18n configs

---

server/app/facets/auth/auth-view.js
server/tests/unit/facets/auth/auth-view.js

Similarly to  http://wikia-inc.atlassian.net/browse/IRIS-4179 fix XSS vulnerability in params passed in reply.view's context.
* http://wikia-inc.atlassian.net/browse/IRIS-4180

IRIS-4180 | Encode for JS the exitTo and canonical URLs

---

front/main/app/models/discussion/domain/open-graph.js

* http://wikia-inc.atlassian.net/browse/IRIS-4187

IRIS-4187 | If it's not there, don't try to use it

---

server/app/facets/auth/auth-view.js

* http://wikia-inc.atlassian.net/browse/IRIS-4188

IRIS-4188 | Do not encode the parentOrigin

---

front/main/app/styles/component/_site-head.scss
front/main/app/styles/component/_wikia-user-profile.scss
front/main/app/styles/component/design-system/_notifications.scss
front/main/app/templates/components/design-system/global-navigation-notifications.hbs
front/main/app/templates/components/site-head.hbs
front/main/app/templates/components/wikia-nav.hbs
front/main/app/templates/components/wikia-user-profile.hbs

* http://wikia-inc.atlassian.net/browse/IRIS-4202

IRIS-4202 | Zero state for notifications in user profile + CSS refactoring & cleanup

---

front/main/app/styles/component/_site-head.scss
front/main/app/styles/component/_wikia-user-profile.scss
front/main/app/styles/component/design-system/_notifications.scss
front/main/app/templates/components/design-system/global-navigation-notifications.hbs
front/main/app/templates/components/site-head.hbs
front/main/app/templates/components/wikia-nav.hbs
front/main/app/templates/components/wikia-user-profile.hbs

* http://wikia-inc.atlassian.net/browse/IRIS-4081

IRIS-4081 Move Notifications CSS from Mercury to Design System

---

front/main/app/services/notifications.js

* http://wikia-inc.atlassian.net/browse/IRIS-4208

IRIS-4208 | Bugfix: do not call OSN if the user is signed out

---

server/app/facets/auth/auth-view.js

* http://wikia-inc.atlassian.net/browse/IRIS-4243

IRIS-4243 | Escape the redirect URL for context

---

front/main/bower.json

* http://wikia-inc.atlassian.net/browse/IRIS-4210

IRIS-4210 | Bump Design System to 5.8.2

---

front/main/app/components/design-system/global-navigation.js
front/main/app/components/wikia-nav.js
front/main/app/services/notifications.js
front/main/app/templates/components/design-system/global-navigation.hbs
front/main/app/templates/components/wikia-nav.hbs

* http://wikia-inc.atlassian.net/browse/IRIS-4170

IRIS-4170 | Remove wgEnableOnSiteNotifications

---

package.json

https://wikia-inc.atlassian.net/browse/XW-3233
Update DS-i18n to fix problem with languages that aren't fully supported
@rogatty

XW-3233 | Bump design-system-i18n version

---

front/main/bower.json

* https://wikia-inc.atlassian.net/browse/XW-3209
Design system version update to update avatar stack spacing
@Wikia/x-wing

XW-3209 | update design system

---

server/app/facets/auth/piggyback.js
server/app/lib/auth-utils.js
server/app/lib/url-utils.js
server/tests/unit/lib/url-utils.js

* http://wikia-inc.atlassian.net/browse/IRIS-3993

IRIS-3993 | Redirect back to piggyback after signing in

---

front/auth/views/_partials/auth/piggyback.hbs
server/app/app.js
server/app/facets/auth/auth-view.js
server/app/facets/auth/piggyback.js
server/app/lib/sanitizer.js

* http://wikia-inc.atlassian.net/browse/IRIS-3995

IRIS-3995 | Auto-fill target's username in Piggyback form

---

front/main/app/components/design-system/global-navigation-notifications.js
front/main/app/components/wikia-user-profile.js
front/main/app/mixins/responsive.js
front/main/app/services/notifications.js
front/main/app/utils/discussion-tracker.js
front/main/app/utils/notifications-tracker.js
front/main/app/utils/responsive-utils.js

* http://wikia-inc.atlassian.net/browse/IRIS-4264

IRIS-4264 | Track menu being open and differentiate between mobile and desktop

---

front/main/app/index.html
server/app/views/_partials/crowdin-incontext.hbs
server/config/settings.base.js

* http://wikia-inc.atlassian.net/browse/SER-968
Added support for in context translations
@kvas-damian @rogatty

SER-968 Added in context translations

---

server/app/lib/wikia-session.js

* https://wikia-inc.atlassian.net/browse/PLATFORM-3071
* https://github.com/Wikia/helios/pull/281
Add internal request header to Helios info request which will be required
going forward.
@Wikia/core-platform-team @slayful

(PLATFORM-3071) Add internal request header to Helios info request

---

front/main/app/mixins/theme.js
front/main/app/styles/component/discussion/_discussion-block-quote.scss
front/main/app/styles/component/discussion/index.scss

* http://wikia-inc.atlassian.net/browse/IRIS-4366
Adds support for block quotes from migrated discussions sites.

IRIS-4366 - add styles for block quotes

---

front/main/app/components/image-review.js
front/main/app/controllers/image-review/batch-id.js
front/main/app/routes/image-review/batch-id.js
front/main/app/templates/components/image-review.hbs
front/main/app/templates/image-review/batch-id.hbs

* http://wikia-inc.atlassian.net/browse/SER-962
In the new image-review tool, after changing the source or order of images, the batch of images to review will be immediately updated.

SER-962 immediate refresh after changing image order or source

---

front/main/app/components/image-review.js
front/main/app/styles/component/_image-review.scss
front/main/app/templates/components/image-review-image-details.hbs
front/main/app/templates/components/image-review.hbs

* http://wikia-inc.atlassian.net/browse/SER-1000
Added an explicit close button to the modal in image-review

SER-1000 add close button to image-review details modal

---

package.json

* https://wikia-inc.atlassian.net/browse/XW-3555

Update Design System i18n to 0.10.2 (Branding Update)

---

front/main/app/components/design-system/community-header.js
front/main/app/components/user-avatar.js
front/main/app/components/wds-avatar-stack.js
front/main/app/styles/component/design-system/_community-header.scss
front/main/app/templates/components/design-system/community-header.hbs
front/main/app/templates/components/user-avatar.hbs
front/main/app/templates/components/wds-avatar-stack.hbs
server/.eslintrc
server/app/facets/show-discussions.js
server/app/views/_partials/server-data.hbs
server/tests/acceptance/application.js
server/tests/acceptance/global-footer.js

* https://wikia-inc.atlassian.net/browse/XW-3633
Fetch the list of discussions contributors server-side and display as avatar stack in Community Header.
@Wikia/x-wing @slayful

XW-3633 | Add wds-avatar-stack to Community Header

---

front/common/public/locales/en/discussion.json
front/main/app/components/left-rail-user-details.js
front/main/app/styles/component/discussion/_discussion-moderator-tools.scss
front/main/app/styles/component/discussion/_discussion-side-button.scss
front/main/app/styles/component/discussion/_left-rail-user-details.scss
front/main/app/styles/component/discussion/index.scss
front/main/app/styles/layout/_discussion-rail.scss
front/main/app/templates/components/discussion-community-unit.hbs
front/main/app/templates/components/discussion-entities-list-layout.hbs
front/main/app/templates/components/discussion-moderator-tools.hbs
front/main/app/templates/components/discussion-user-entities-list-layout.hbs
front/main/app/templates/components/left-rail-user-details.hbs

* https://wikia-inc.atlassian.net/browse/XW-3747
@Wikia/x-wing

XW-3747 | Handle Post List type

---

front/main/app/styles/component/_image-review.scss
front/main/app/templates/components/image-review-image-details.hbs

* http://wikia-inc.atlassian.net/browse/SER-1051
Redesign image modal.

SER-1051 | image details modal redesing

---

front/main/app/styles/component/discussion/_discussion-header.scss
front/main/app/styles/layout/_discussion-rail.scss
front/main/app/styles/theme/_dark.scss
front/main/app/templates/components/discussion-header.hbs
front/main/app/templates/components/discussion-user-entities-list-layout.hbs

* http://wikia-inc.atlassian.net/browse/IRIS-4724
Adds the `delete-all` class back for testing.

IRIS-4724 - add delete-all class back for tests

---

front/main/app/styles/component/design-system/_community-header.scss
front/main/app/styles/module/_discussion.scss

* https://wikia-inc.atlassian.net/browse/XW-3763

Fix 1063 breakpoint

---

front/main/bower.json

* https://wikia-inc.atlassian.net/browse/XW-3556

XW-3556 | Update design system to 8.2.3

---

front/main/app/styles/component/discussion/_discussion-guidelines.scss

https://wikia-inc.atlassian.net/browse/XW-3814

Release 377 | fix wordbreak

---

front/auth/views/_layouts/auth.hbs
front/auth/views/_layouts/card.hbs
front/common/baseline/cookie.js
front/common/baseline/state-geo.js
front/common/baseline/tracker-internal.js
front/common/tests/unit/baseline/cookie.js
server/app/facets/auth/auth-view.js

* https://wikia-inc.atlassian.net/browse/ADEN-5581
Add pvUID, pvNumber and sessionId to internal tracking
@Wikia/adeng

ADEN-5581 | Add pvUID, pvNumber and sessionId to internal tracking

---

front/main/app/templates/components/discussion-community-unit.hbs
front/main/app/templates/components/discussion-entities-list-layout.hbs
front/main/app/templates/components/discussion-moderator-tools.hbs

Reverts Wikia/mercury#3219 - turns out we want to keep just one section

Revert "IRIS-4786 - show moderation tools header on main page"

---

front/main/app/styles/_settings.scss
front/main/app/styles/theme/_dark.scss

https://wikia-inc.atlassian.net/browse/IRIS-4789
Miscellaneous css fixes for discussions.

IRIS-4789 - post style changes

---

front/main/app/mixins/discussion-contribution-controller.js
front/main/app/routes/discussion.js
front/main/app/routes/discussion/guidelines.js
front/main/app/templates/discussion/guidelines.hbs
front/main/app/utils/discussion-tracker.js

* http://wikia-inc.atlassian.net/browse/IRIS-4869

IRIS-4869 | Move site attribute model to Guidelines page

---

front/main/app/components/discussion-community-unit.js
front/main/app/controllers/discussion/moderator/user-activity.js
front/main/app/templates/components/discussion-community-unit.hbs
front/main/app/templates/discussion/moderator/user-activity.hbs

* http://wikia-inc.atlassian.net/browse/IRIS-4256

IRIS-4256 | Remove layout customizations for Star Trek Discussions

---

front/main/app/components/discussion-post-card-top-note.js

* http://wikia-inc.atlassian.net/browse/IRIS-4771

IRIS-4771 | Fix reporting confirmation

---

front/main/app/mixins/theme.js
front/main/app/routes/discussion/moderator/user-activity.js
server/app/lib/sass-variables.js

* http://wikia-inc.atlassian.net/browse/IRIS-4830

IRIS-4830 | Add a variable which will override color links from theme designer in Discussions

---

front/main/app/components/discussion-standalone-editor.js
front/main/app/models/discussion/domain/content-images.js

* https://wikia-inc.atlassian.net/browse/IRIS-4922
Stop modifying post images before submitting.
@slayful

IRIS-4922 | use content images copy for editor

---

front/main/app/models/notifications/notification.js
front/main/ember-cli-build.js
front/main/mirage/fixtures/curated-content-section.js
front/main/mirage/fixtures/curated-content.js
server/app/lib/utils.js
server/config/settings.base.js

* http://wikia-inc.atlassian.net/browse/PLATFORM-3176
Before switching the articles to https, we want to make sure all the assets are served using https.

PLATFORM-3176: Serve assets over HTTPS

---

server/app/lib/open-graph.js

* https://wikia-inc.atlassian.net/browse/IRIS-4921

IRIS-4921 | Handle content images in ogImage generation for Discussions

---

front/main/app/styles/_discussion-settings.scss
front/main/app/styles/component/discussion/_discussion-post-image.scss

* https://wikia-inc.atlassian.net/browse/IRIS-1622
Add the same border as OpenGraph.
@slayful

IRIS-1622 | Add border to post images

---

front/common/public/locales/ja/discussion.json
front/common/public/locales/pl/discussion.json
front/common/public/locales/ru/discussion.json
front/common/public/locales/zh/discussion.json

* https://wikia-inc.atlassian.net/browse/IRIS-4930
* https://wikia-inc.atlassian.net/browse/LOC-17633
The automatic process seems to have problems nowadays. Let's make sure the translations are there. 
@slayful

IRIS-4930 | Update translations for image upload

---

front/main/app/styles/component/discussion/_discussion-post-image.scss

* https://wikia-inc.atlassian.net/browse/IRIS-5048
It looks better.
@slayful

IRIS-5048 | Move border from wrapper to post image

---

front/common/baseline/build-url.js

Delete protocol override

---

server/app/facets/operations/username.js
server/app/lib/auth-utils.js
server/config/settings.base.js
server/config/settings.dev.js
server/config/settings.prod.js

* http://wikia-inc.atlassian.net/browse/SER-1419
Use the internal k8s domain when communicating with `user-registration`. Remove Consul-based service discovery.
@Wikia/iris @Wikia/services-team

SER-1419 use k8s domain for user-registration, remove consul

---

server/app/facets/auth/forgot-password.js
server/app/facets/auth/register.js
server/app/facets/auth/reset-password.js
server/app/facets/operations/username.js
server/app/lib/auth-utils.js
server/config/settings.base.js
server/config/settings.dev.js
server/config/settings.prod.js

Corrected a typo
@Wikia/services-team @Wikia/iris

corrected typo in configuration

---

server/config/settings.base.js

Fix merged to `release-427` branch - https://github.com/Wikia/mercury/pull/3275, but this time to `dev`.
@pwojcik86 @rogatty @tortila

Default helios url to dev

---

server/app/facets/auth/forgot-password.js
server/app/facets/operations/username.js

* http://wikia-inc.atlassian.net/browse/MAIN-12070
Same as: https://github.com/Wikia/mercury/pull/3277 but to the `dev` branch
@pwojcik86 @rogatty

MAIN-12070 fix user-registration url

---

Dockerfile

* https://wikia-inc.atlassian.net/browse/OPS-11215
* https://wikia-inc.atlassian.net/browse/IRIS-5224
Let's upgrade production to node 8.9.1 -- dev was upgraded a few days ago

Upgrade to node 8.9.1

---

front/main/app/routes/infobox-builder.js

* http://wikia-inc.atlassian.net/browse/XW-4436

XW-4436 | Custom canUnload logic and ponto endpoint for refreshing route

---

front/main/app/components/infobox-builder.js
front/main/app/controllers/infobox-builder.js
front/main/app/routes/infobox-builder.js
front/main/app/templates/infobox-builder.hbs

* https://wikia-inc.atlassian.net/browse/XW-4355
* https://github.com/Wikia/app/pull/14439
@Wikia/x-wing

XW-4356 | Support for CKE in InfoboxBuilder

---

front/main/app/components/infobox-builder.js
front/main/app/controllers/infobox-builder.js
front/main/app/routes/infobox-builder.js
front/main/app/templates/infobox-builder.hbs

This corresponds to #3279 (already merged to dev) so that we can release it today to prod.
@Wikia/x-wing

XW-4356 | 

---

front/common/baseline/build-url.js
front/common/tests/unit/baseline/build-url.js

* http://wikia-inc.atlassian.net/browse/SUS-4207

SUS-4207 Respect scriptPath in build-url method

---

front/auth/views/_layouts/auth.hbs
front/auth/views/_layouts/card.hbs

Bring back $script
