Wikia/mercury

- public/styles/base/_anchors.scss
- public/styles/component/_collapsible-menu.scss
- public/styles/component/_local-wikia-search.scss
- public/styles/module/_comments.scss
- public/styles/module/wiki/_login.scss
https://wikia-inc.atlassian.net/browse/HG-373
Added .touch-active to all anchors, collapsible menus and comments-related buttons.
> Add tap states where missing

- config/localSettings.base.ts
NewRelic was throwing errors because of timeouts caused by long parses. Mercury's timeouts were capped at 30s while MW's are capped at 5m. This pull request raises our timeout to match that.
> Set API timeout to match MediaWiki app's timeout

- server/app.ts
- server/lib/Caching.ts
- server/lib/Logger.ts
- server/lib/Tracking.ts
- server/lib/Utils.ts
- server/server.ts
Remember to check for style in your code reviews.
Two main whitespace errors here are the:
* space after function name
* no whitespace surrounding arguments/conditions in parens
Remember, our TS guidelines fall back to JS guidelines where applicable. Developers should familiarize themselves with the TS and JS guidelines [here](https://github.com/Wikia/guidelines).
> Reminder about whitespace

- server/routes.ts
Get rid of error:
```
Possibly unhandled TypeError: Cannot call method 'replace' of undefined
at beforeArticleRender (/home/igor/workspace/mercury/www/server/routes.js:77:82)
at onArticleResponse (/home/igor/workspace/mercury/www/server/routes.js:104:9)
at /home/igor/workspace/mercury/www/server/routes.js:150:33
at /home/igor/workspace/mercury/www/server/controllers/article/index.js:105:9
at /home/igor/workspace/mercury/www/server/controllers/article/index.js:61:9
at tryCatch1 (/home/igor/workspace/mercury/www/node_modules/bluebird/js/main/util.js:21:21)
at Promise._settlePromiseFromHandler (/home/igor/workspace/mercury/www/node_modules/bluebird/js/main/promise.js:591:13)
at Promise._settlePromiseAt (/home/igor/workspace/mercury/www/node_modules/bluebird/js/main/promise.js:755:18)
at …
```
> Fixed unhandled TypeError when no title is given

- front/scripts/main/helpers/i18nHelper.ts
https://wikia-inc.atlassian.net/browse/HG-540
This code was trying to access `this['comment.comments.length']` instead of `this.comment.comments.length`
> Fix label on comment replies

- front/styles/module/article/_media.scss
https://wikia-inc.atlassian.net/browse/HG-523
This fixes a previous change to captions that affected media not in linked galleries.
> Fix multi-line captions only for linked galleries

- front/scripts/main/views/ApplicationView.ts
This change removes some outdated and unnecessary code, which was
introduced with
https://github.com/Wikia/mercury/commit/53d14ee7c0fa9f37527734230244a02c
7ea471b4
The ```setScrollable``` and ```setUnscrollable``` actions no longer
exist, so this work-around for ```event.preventDefault()``` is not
needed.
> Call event.preventDefault directly

- server/routes.ts
Fix the `(one-line) routes.ts[18, 6]: misplaced opening brace` TSLint warning.
> Fix TSLint warning

- front/styles/module/article/_media.scss
Single linked image with caption generates following element:
`<figure class="ember-view media-component article-image has-caption visible" data-ref="4">`.
I've created `MercuryLinkedImagesNew` article on mediawiki119@devbox to test it (http://mediawiki119.wikia.com/wiki/MercuryLinkedImages on production). During QA, please check if all possible cases are there.
/cc @vforge
> Fix for chevron position on single linked image with caption

- front/templates/main/components/video-media.hbs
https://wikia-inc.atlassian.net/browse/CONCF-111
We don't escape captions in `image-media.hbs` and shouldn't do it in `video-media.hbs`. They're escaped in MW already.
> Stop escaping already escaped captions

- bower.json
Fix for error that was happening for people with misconfigured ssh keys (like me):
```
bower install
bower scroll-depth#0.8.3    not-cached git@github.com:nandy-andy/jquery-scrolldepth.git#0.8.3
bower scroll-depth#0.8.3       resolve git@github.com:nandy-andy/jquery-scrolldepth.git#0.8.3
bower scroll-depth#0.8.3       ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:nandy-andy/jquery-scrolldepth.git", exit code of #128
Additional error details:
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```
> Use https instead of ssh to get jquery-scrolldepth

- server/app.ts
- typings/hapi/hapi.d.ts
https://wikia-inc.atlassian.net/browse/CONCF-70
`onPreResponse` event is the earliest place where we can detect that the request URI was malformed (`decodeURIComponent` failed in hapijs/call lib and `badrequest` method was set as a special route handler).
When MediaWiki gets request like that it redirects to the main page with code 301.
For now we don't want to send additional request to get title of the main page and are redirecting to / which causes user to get the main page eventually.
> Redirect to / when URI is malformed

- front/scripts/main/routes/ApplicationRoute.ts
- front/scripts/mercury/utils/variantTesting.ts
- test/specs/front/scripts/mercury/utils/variantTesting.js
https://wikia-inc.atlassian.net/browse/HG-566
This change improves the Optimizely implementation by somewhat
decoupling the A/B testing code and allowing tracking of custom events.
> HG-566 Extended Optimizely integration

- server/lib/MediaWiki.ts
Server was throwing exception when there was no payload in response (for example 503 from Varnish).
> Fix for crashing after empty response

- bower.json
- front/scripts/main/components/ArticleCommentComponent.ts
- front/scripts/main/components/GalleryMediaComponent.ts
- front/scripts/main/components/ImageMediaComponent.ts
- front/scripts/main/components/MediaComponent.ts
- front/scripts/main/helpers/thumbnailHelper.ts
- front/styles/module/article/_media.scss
- front/templates/main/components/image-media.hbs
- front/templates/main/components/video-media.hbs
- test/specs/front/scripts/main/helpers/thumbnailHelper.js
Reverts Wikia/mercury#563
Branch `Remove-backround-on-image` introduces some regression and needs more work. Reverting so we can deploy a new release.
> Revert "Rework how we load thumbnails"

- server/lib/MediaWiki.ts
This fixes `TypeError: Cannot read property 'statusCode' of undefined` reported by New Relic.
> Check for error before trying to access response which can be undefined

- server/views/_helpers/translations.js
The variable name is changed because we want to reserve 'response' only for server responses.
It's the fix for this PR https://github.com/Wikia/mercury/pull/587/files
> variable name change

- front/scripts/mercury/modules/Trackers/Krux.ts
Small fix necessary after deprecating Mercury.__state.
> CONCF-81 fix M.prop instead of Mercury.__state

- front/scripts/mercury/modules/Ads.ts
- front/scripts/mercury/modules/Trackers/ScrollDepthTracker.ts
- front/scripts/mercury/utils/track.ts
Hello all, this PR fixes a few TS errors introduced with Krux integration. In addition, this PR removes all dependencies on Ember in `scripts/mercury`. Scripts in `scripts/mercury` are meant to be able to be used in contexts beyond the Ember application. I initially created this separation between the Ember scripts and the Mercury scripts because I noticed that certain modules didn't require coupling or wrapping into Ember's ecosystem and would better serve us to write them generically. So I created `scripts/mercury` with a `modules` and `utils` folder. The goal of this folder is to remain loosely coupled. So in this PR, I've removed unnecessary coupling in the `scripts/mercury` directory, specifically instances of `Em.get` and `Em.Logger.*`.
Additionally, both of those functions are …
> Cleanup: scripts/mercury

- front/scripts/main/app.ts
- server/views/layout.hbs
Without a specified root element, Ember defaults it's root element to render into to the `body` tag. This is confusing to the [Google PageSpeed](https://developers.google.com/speed/pagespeed/insights/) which sees that we have page content after scripts in the body even though we in fact loaded the scripts after the content.
This fixes that issue by explicitly setting rootElement to a node that is inserted before those scripts and should increase our PageSpeed score.
New mobile algorithms from Google take into effect 4/21.
@tedgill  @hobbs
> Add a rootElement for Ember to render into

- package.json
In [this PR](https://github.com/Wikia/mercury/pull/621/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R54) I upgraded `gulp-sass` to fix an issue where running `gulp sass` on it's own would work fine, but running it as part of `gulp build` would return an error. 
Another person ran into the same issue described [here](http://www.expertland.net/question/t82o1l24mby3x9o6q5nb6524mrxa83o5/detail.html) and upgrading fixed their problem too. 
I just want to merge this change into `dev` so it doesn't diverge from the `hapi-auth` branch too much.
> upgrading gulp-sass to fix issues with gulp-build

- config/localSettings.base.ts
We don't yet have a hot-swappable configuration tool in place, and we need to enable Optimizely this week for an experiment that was expected to run two weeks ago, so this seems like the only thing to do. Alternative suggestions to enable this on production are welcome.
This change will result in the Optimizely JS snippet being loaded for every Mercury user.
> Enable Optimizely

- config/localSettings.base.ts
This is temporary, to enable Optimizely experiments for the next few weeks in Mercury. This has been changed back from an environment variable, because I thought a feature-level switch does not belong in configuration at the environment deployment level. Either way, this config value would have been hard-coded in either place. We should change this to go through Consul soon though.
@hakubo FYI
> Enable Optimizely in localSettings

- package.json
Having this script
we can teach DTools to run
`npm run build`
instead of
`gulp build --type prod`
so it does not have to know the 'internals' of the service
It is mostly 1:1 mapping to what DT used to do
having it here will free us to tweak what build do, without having to deploy DT
> add build task to package.json

- config/localSettings.base.ts
- config/localSettings.d.ts
- front/scripts/main/controllers/ApplicationController.ts
- front/styles/main/layout/_page-wrapper.scss
- front/templates/main/application.hbs
- server/facets/editorPreview.ts
- server/facets/operations/prepareArticleData.ts
- server/facets/operations/verifyMWHash.ts
- server/facets/showArticle.ts
- server/lib/Article.ts
- server/routes.ts
- typings/hapi/hapi.d.ts
This pull requests adds capability to preview an HTML in a Mercury skin.
The API is: POST /editor_preview/ the POST params are:
* parserOutput: JSON as returned by ArticleApi (article as JSON)
* title: article title
* mwHash: sha1 hash with salt to prove the parserOutput was indeed generated by MediaWiki
This commit reveals an issue of not properly encoding article title passed by MediaWiki API in https://github.com/Wikia/mercury/pull/618/files#diff-5a151be511cd8e3c3d6a4e795aad8d46R120 . We chose to fix this issue on the MediaWiki side https://wikia-inc.atlassian.net/browse/HG-564, but I would like us to revisit this issue and move the fix to Mercury, so everything works as expected.
The salt for recomputing mwHash is expected to appear as an environmental variable MW_PREVIEW_SALT.
At one …
> CE-1431 Added /editorPreview/ route to preview given HTML in Mercury skin

- server/facets/editorPreview.ts
- typings/boom/boom.d.ts
This fixes a tslint warning that was introduced with merging #618. This fixes the variable clobbering and handles the error from the getWikiVariables request.
> Fixed variable clobbering and use Boom to create error object

- front/styles/main/module/_site-footer.scss
https://wikia-inc.atlassian.net/browse/CONCF-369
Styles removed in this PR caused the footer to be too wide (horizontal scrollbar was visible).
> Remove Foundation's .row styles from footer

- front/styles/common/placeholder/%padding-on-sides.scss
- front/styles/common/placeholder/index.scss
- front/styles/main/layout/_page-wrapper.scss
- front/styles/main/module/_comments.scss
- front/styles/main/module/_site-footer.scss
- package.json
Reverts:
- https://github.com/Wikia/mercury/pull/603 - partially, Foundation 5.5.1 is fine
- https://github.com/Wikia/mercury/pull/625
- https://github.com/Wikia/mercury/pull/639
gulp-sass 1.3.x causes our CSS to break. This is blocking release-51 so I'm downgrading and reverting all the related changes.
> Downgrade gulp-sass to 1.1.x and revert related changes

- front/scripts/main/models/ArticleModel.ts
Response from /api/v1/article?random&titleOnly was cached for 60s on Varnish even though max-age and s-maxage are set to 0.
I decided to use $.ajax({cache:false}) which appends timestamp to URL.
ping @Warkot @rogatty
> CONCF-374 disable cache on random article inside jquery.ajax

- front/scripts/main/controllers/AdsLightboxController.ts
- front/scripts/main/mixins/LightboxMixin.ts
- front/scripts/main/routes/ApplicationRoute.ts
- front/scripts/main/views/AdsLightboxView.ts
- front/scripts/main/views/MapLightboxView.ts
- front/scripts/main/views/MediaLightboxView.ts
- front/scripts/mercury/modules/Ads.ts
- front/styles/main/module/_ads.scss
- front/templates/main/ads-lightbox.hbs
We implemented interstitial ads on Oasis and we're using there `UiFactory` and its regular modals. We also wanted to have the interstitial product on Mercury and changes below allows us to have it.
The changes includes:
* new simple ads lightbox,
* exposed `openMercuryAdLightbox()` function which opens *only* the ads lightbox.
This pull request is connected to https://github.com/Wikia/app/pull/6758.
To test if it's work open a mercury page in your browser and execute in JavaScript console following code:
```js
window.loadCustomAd && window.loadCustomAd({
type: 'modal',
width: 300,
height: 250,
code: 'An ad placeholder'
});
```
> ADEN-1834 Interstitial ads on mercury

- front/styles/main/module/_comments.scss
- front/styles/main/module/_site-footer.scss
- package.json
After merging the hapi-auth branch, we noticed that something odd was happening with the sass compilation. The settings file for `styles/main/app.scss` was getting overwritten by another settings file from `styles/auth/`.
To make a long story short, the version of libsass used by the gulp-sass plugin was getting confused when imports with two separate files in different directions with the same name. This was fixed in a later version of libsass so I upgraded our gulp-sass and also fixed all the regressions that resulted from the last time we tried to upgrade. Likely, they weren't regressions in the way we thought, but rather, the libsass version we were using was actually failing to correctly compile the mixins from Foundation. Upgrading gulp-sass revealed our mistakes and this PR fixes …
> Upgrade gulp-sass (for real this time)

- server/routes.ts
Simply turns auth mode to false for unauthenticated routes, squelching errors from Kibana.
> Set auth mode to false for unauthenticated routes

- front/scripts/main/components/ArticleCommentComponent.ts
@mklucsarits found a bug where if you opened up comments on a page with comments, and tried to transition using a `{{link-to}}` helper, like in the content recommendation area at the foot of an article, you would fail the transition because of trying to access a value on a null object. This adds a check that prevents that and allows the transition to proceed safely.
> Do not try to access value on null

- front/styles/main/module/article/_media.scss
https://wikia-inc.atlassian.net/browse/CONCF-208
Only small CSS change adding margin between images also when no caption present.
> CONCF-208 Spaces in gallery when no caption

- bower.json
Discovered a bug today that was revealed (but not necessarily caused) by the recent Ember upgrade. It was fixed here: https://github.com/Wikia/ember-performance-sender/pull/3 and this updates our packages to reflect it. It was never on production because we haven't pushed the chef changes to run EPS/Weppy yet.
> Update ember-performance-sender version

- front/scripts/main/components/ShareFeatureComponent.ts
- front/scripts/main/controllers/ApplicationController.ts
- front/templates/main/application.hbs
- front/templates/main/components/share-feature.hbs
There is still special handling for Japanese language - LINE and Google+ providers are displayed.
This change also addresses INT-51 - determine language based on navigator/browser instead of just content language.
> INT-55: Enable ShareFeature for all languages

- server/views/_helpers/i18n.ts
Previously, `{{i18n 'my-key' foo='bar'}}` wouldn't work b/c `options.hasOwnProperty(key)` was always evaluating to `false`. One fix would have been to change it to `options.hash.hasOwnProperty(key)`, but `Objects.keys` already filters out inherited properties so I removed that check altogether. 
I also added a comment and tried to make the code a bit easier to read for someone new to handlebars helpers.
> Allowing i18n helper to accept inline params

- server/facets/auth/login.ts
https://wikia-inc.atlassian.net/browse/SOC-657
Even though the UI option for "remember me" was removed, we still need to set the cookie expiration.
> Set the auth cookie TTL

- front/scripts/mercury/modules/Ads.ts
**DO NOT MERGE TILL MONDAY AFTER MERCURY RELEASE!!!**
While cleaning done in [ADEN-1785](https://wikia-inc.atlassian.net/browse/ADEN-1785) we renamed `ext.wikia.adEngine.adConfigMobile` module to `ext.wikia.adEngine.config.mobile`. Unfortunately, Mercury uses `ext.wikia.adEngine.adConfigMobile` and we didn't change it while cleaning up. The result was no ads in Mercury and JavaScript error in a browser console:
`Uncaught Module ext.wikia.adEngine.adConfigMobile is not defined.`
The small change below fix the issues.
**RELEASE NOTES:**
The idea is to release Mercury on Monday and it'd be safe release because `Wikia/app` release-286 won't be live yet. On Monday after release I'll merge it and it should be released on Tuesday after `Wikia/app` release-286 has been released.
> ADEN-1918 change the name of module to correct one

- server/facets/auth/login.ts
Only set the access_token from helios
> HG-595 don't set refresh token as cookie

- front/templates/main/article.hbs
Adding another ad slot to Mercury, just under the article title.
The purpose of the slot is to serve Paid Asset Drops in it. PADs are highly polished per wiki campaigns running with knowledge and acceptance of the communities.
> ADEN-1946 Paid Asset Drops for Mercury

- front/scripts/main/models/ArticleModel.ts
- front/templates/main/article.hbs
https://wikia-inc.atlassian.net/browse/CONCF-466
1. Fix for displaying not-found template after transition to non-existent article
2. Fix for a regression created when upgrading to Ember 1.11
> Render not-found template when we have 404

- server/app.ts
- server/facets/auth/login.ts
The `access_token` cookie wasn't actually being set upon login. Now it is.
> HG-595 fixing access_token cookie setting and removing unused cookie

- crowdin-auth.conf
- crowdin-main.conf
https://wikia-inc.atlassian.net/browse/HG-589
The Mercury codebase is changing to use multiple JSON files for localization strings, separated by need and/or feature. However, multiple source files are not supported by the i18n CrowdIn API scripts. Therefore, until that happens, we need to use separate config files, one for each JSON file.
> Move crowdin config to multiple files, for now

- bower.json
This implements a patched version of the style guide package temporarily removing icon backgrounds using url() paths which caused 404 errors in Mercury. See https://github.com/Wikia/style-guide/commit/86c398a324aa0e6177b44c7acd75307824801e99 for the change to wikia/style-guide for the 1.0.1 release.
https://wikia-inc.atlassian.net/browse/HG-616
@rogatty
> HG-616 Use style guide package with icons removed

- config/localSettings.base.ts
Sources`mediawikiDomain` in config from environment variables.
> enables internal varnish for mercury

- front/scripts/main/views/ArticleView.ts
https://wikia-inc.atlassian.net/browse/CONCF-480
This fixes context menu on iOS 8.3. No idea why it was working in the previous versions, probably some bug in Safari?
> Set hammerOptions.cssProps.touchCallout to 'default'

- front/templates/main/ads-lightbox.hbs
After recent lightbox refactoring the ads lightbox styling got broken.
As a quick fix and workaround I've added a new wrapper in ads lightbox so the styling is not broken.
> ADEN-1993 Fixed ads lightbox styling in Mercury

- config/localSettings.base.ts
We need the private helios config values to be available to mercury settings. Previously, we were overriding these vars in our local settings, but that solution doesn't work for production environments. 
Corresponding chef PR to make these vars available to the mercury environment: https://github.com/Wikia/chef-repo/pull/5065.
@kenkouot
> HG-625 setting helios config vars

- config/localSettings.base.ts
- server/views/_layouts/ember-main.hbs
My previous attempts to enable performance monitoring failed do to use of a custom environment variable that wasn't available at **build time**. I've simplified this by simply binding to the environment instead.
> Hg 624 Enable performance monitoring

- front/scripts/main/components/ArticleCommentsComponent.ts
- front/scripts/main/components/LocalNavMenuComponent.ts
- front/scripts/main/views/ApplicationView.ts
- front/templates/main/article.hbs
- front/templates/main/components/content-recommendations.hbs
- front/templates/main/components/local-nav-menu.hbs
- front/templates/main/components/local-wikia-search.hbs
- test/specs/front/scripts/main/views/ApplicationView.js
This PR designates which content we need to apply special click logic to and which content we can let Ember handle on it's own. This should help simplify click handler logic by isolating it to only UGC. 
To do:
> Hg 612 fixing jump-to links in TOC with cb param in query string

- front/templates/main/components/wikia-footer.hbs
This is a temporary fix to include footer links in the list of content areas that should be given special link handling. I'm going to keep this ticket open (or maybe open a new one) so we can find a better solution. For now we just need to unblock the release.
> HG-648 temporary fix for footer links

- front/scripts/main/models/EditModel.ts
Not sure if we'll also want to make the MW API path as a reusable property.
/cc @inez
> (INT-72) Fix hardcoded wikia URL in API requests

- front/scripts/main/components/ShareFeatureComponent.ts
This is quick and dirty solution to a problem introduced as a regression of https://github.com/Wikia/mercury/commit/3885edc49508aa5868e7b9e0a736f45037939ae2
@rogatty and @lizlux recommended this as a good temporary solution - temporary cause Mercury team is going to work on a proper solution as a part of https://wikia-inc.atlassian.net/browse/HG-654
> INT-73: Apply 'mw-content' class to share feature component so it goes through proper click handler

- front/templates/main/article.hbs
https://wikia-inc.atlassian.net/browse/HG-658
Category links were not calling to correct context, this makes them clickable for now
> HG-658 Fix category links

- front/scripts/main/views/ArticleView.ts
In article HTML H2s (and other header tags) can comeout from various of wikitext - not only wikitext sections - as a part of INT-58 I modified ArticleAsJson to add section attrbiute to all header tags which are actually wikitext sections. More info: https://wikia-inc.atlassian.net/browse/HG-600
> DAT-2788: For TOC creation only select H2s that have section attribute specified

- front/templates/main/application.hbs
- front/templates/main/article.hbs
This is no longer needed and actually breaks footer links.
> Remove obsolete trackClick='trackClick'

- front/scripts/main/models/ArticleModel.ts
Reverted condition since it broke ads on consecutive pageviews.
The condition wasn't good enough since when Ad Engine was enabled the `adsContext` instance didn't have `length` property (because it was an object).
Related pull request: Wikia/app#7236
> ADEN-2030 Fix ads on Mercury

- package.json
`gulp-develop-server` version that we use has a problem with multiple restarts, see https://github.com/narirou/gulp-develop-server/issues/14
This causes frequent crashes of server. Reverting the upgrade seems to fix the issue (haven't yet crashed for me).
/cc @lizlux
> Downgrade gulp-develop-server

- server/facets/api/article.ts
- server/facets/api/articleComments.ts
- server/facets/api/curatedContent.ts
- server/facets/api/search.ts
Using `wrapResult` without using the value it returns caused exceptions when there was no `result`. For me it happened when MW returned 503 error.
This is the fix and a naming clean up.
> Use the returned value from wrapResult method

- server/lib/AuthUtils.ts
Turns out Mercury supports only wikias with /wiki/ in the article path. This should be safe this way, tested on sandbox.
@mklucsarits
> Fixing forgot-password link

- config/localSettings.base.ts
- front/scripts/mercury/modules/Trackers/UniversalAnalytics.ts
- front/scripts/mercury/utils/track.ts
Adds a check for `isGASpecialWiki`. This can be defined in two places, `Mercury.wiki.isGASpecialWiki` or `M.prop('isGASpecialWiki')`. The preferred place to declare values as these is in `M.prop`, but the Mercury app currently still has legacy coupling with the globals, `Mercury.wiki`.
> Add check for GA special wiki

- server/facets/api/article.ts
- server/facets/showArticle.ts
Caching HTML in browser has 2 downsides:
- If a user visited Mercury page and then logs in, he'll get Mercury after clicking a link toa previously visited article
- If a user visited a page on Mercury and then this page got edited by someone else, he'll not be able to see the new contents for 24 hours.
This also breaks new login behavior as we don't handle logged-in state in Mercury yet.
@rogatty @kvas-damian @lizlux @kenkouot
> SOC-826 Disable browser caching for HTML documents

- front/scripts/main/mixins/LanguagesMixin.ts
- front/scripts/main/models/ArticleModel.ts
- front/scripts/main/views/ArticleView.ts
- front/templates/main/article.hbs
- front/templates/main/components/share-feature.hbs
For the MVP, we don't want the edit buttons to show on main pages, and to
only display them on Japanese-language wikias.
/cc @inez
> (INT-82) Don't display edit buttons on main pages or non-Japanese wikias

- front/scripts/main/components/CuratedContentComponent.ts
- front/scripts/main/models/CuratedContentModel.ts
`isTopSection` property was missing from the `CuratedContentSection` type.
https://github.com/Wikia/mercury/blob/dev/front/scripts/main/components/CuratedContentComponent.ts#L56 and https://github.com/Wikia/mercury/blob/dev/front/scripts/main/components/CuratedContentComponent.ts#L92 were highligthed by WebStorm because of invalid type.
/cc @Warkot @vforge
> Fix curated content invalid typing

- front/scripts/auth/common/Form.ts
- front/scripts/auth/login/SubmitValidator.ts
Both Android and iOS have different autofill mechanisms. We need to gear up as much as we can to let them do their work, not affecting our validation. 
- iOS has a "Password autofill" feature on login input that will autofill the password and login for the user, not "input" or "focus/blur" events on the way. We only have the "change" event on the whole form )with capturing flag switched on) to intercept that
- Android's Chrome will autofill the fields after DOMContentLoaded handlers finish executing and it will spontaneously trigger "change" event for either one or more fields (not deterministically)
- Both autofill mechanisms can be used "on the fly" as the user types in and selects username from a dropdown / clicks "password autofill" above the keyboard
- Password in Android's Chrome …
> SOC-850 & SOC-845 New Login Fixes to cooperate with autofill

- front/styles/main/module/_ads-floor.scss
When an ad in Floor Adhesion unit uses image with transparency with `height` bigger than the unit's background the close button of the unit is displayed wrongly. This is because of incorrect styling and using `height: 100%` for the close button.
Changes below fixes the issue and address some issues found by scss-lint tool.
> ADEN-2065 Fix styling for Floor Adhesion unit with transparency image

- gulp/options/dev.js
- gulp/options/prod.js
This change would enable the ```—suppressImplicitAnyIndexErrors``` flag for ```tsc```. This Github issue provides some background about how that option came to be: https://github.com/Microsoft/TypeScript/issues/1232
I’m encouraging this change because I think in many cases, the types for string indices are obvious to us as developers and are not necessary. And in some cases, providing typing for these can require
rearranging and adding code, making it tedious at least and at worst a waste of time. In other words, a benefit that Typescript provides is actually working against us.
Here’s a real-world example where this would apply.
```
private getCredentials (): LoginCredentials {
return {
username: this.form.elements['username'].value,
password: this.form.elements['password'].value
};
} …
```
> Enable suppressImplicitAnyIndexErrors flag

- front/scripts/main/components/ShareFeatureComponent.ts
- front/scripts/main/mixins/TrackClickMixin.ts
- front/templates/main/components/share-feature.hbs
- front/templates/main/components/wikia-footer.hbs
This undoes a hack we were using to make sure links that were not processed by the `ApplicationRoute` `handleLink` action were still followed. Turns out, by default, ember action helpers will prevent the default action of an event, such as click. Adding `preventDefault=false` to the action helper fixes this.  
This PR also ensures the tracking call is still sent properly before navigating to external links, and I updated the hbs to match [new guidelines](https://github.com/Wikia/guidelines/tree/master/Handlebars) re: quotes. 
@inez @rogatty 
I think there's still more work to do to clean up the `handleLink` function, but that can be done in a separate PR.
> Hg 654 remove 'mw-content' from non-mediawiki content wrappers

- server/facets/api/article.ts
- server/lib/Caching.ts
This fixes this issue where the random page request returned the same page repeatedly. Varnish caches by URL, and the random page request url is the same for every call, so it was just returning one response for all requests. By disabling caching for random page responses, it now returns random pages.
> HG-686 disabled caching for random page querys

- server/facets/api/article.ts
- server/facets/api/articleComments.ts
- server/facets/api/category.ts
- server/facets/api/curatedContent.ts
- server/facets/editorPreview.ts
- server/facets/showArticle.ts
- server/lib/Article.ts
- server/lib/MediaWiki.ts
- server/lib/Utils.ts
- typings/mercury/mercury-server.d.ts
This PR is part of a fix for HG-736. At a high level, there is a race between our purges in Celery, the MW edit API and refreshing/viewing an article in Mercury. In order to prevent a user who has just edited from getting stale content (and also for logged in users), we're going to use the same mechanism MW does and simply ignore cache for requests in which the `wikicities_session` cookie is present.
Previously, calls to the internal Varnish were not setting any cookies. This sets the user session cookie if it is available.
> HG-736 Add in support for forwarding headers

- .gitignore
- gulp/tasks/build-views.js
- gulp/tasks/copy-ts-source.js
- gulp/tasks/scripts-front.js
- gulp/tasks/watch.js
- package.json
These changes add generation of TypeScript sourcemaps and copying of neccesary support files to allow direct debugging of TypeScript from inside Chrome devtools. Generated for dev config only.
> Generate TS sourcemaps to allow direct TS debugging in Chrome devtools

- front/scripts/main/views/ApplicationView.ts
- front/scripts/main/views/ArticleView.ts
- front/styles/main/module/_loader.scss
- server/views/_layouts/ember-main.hbs
This is the basis for an A/B test to see if engagement increases when we provide visual feedback to users via a loading graphic, instead of showing a blank page, while ember is bootstrapping. 
The JS to include via optimizely for users in the test is: 
```javascript
// with jQuery
$('.ab-test-loading-overlay').show();
// without jQuery
document.querySelector('.ab-test-loading-overlay').style.display='block';
```
@kenkouot @katanka
> HG-727 adding loading graphic for A/B test

- front/scripts/main/models/ArticleModel.ts
- front/scripts/main/routes/ArticleRoute.ts
- server/views/_layouts/ember-main.hbs
https://wikia-inc.atlassian.net/browse/CONCF-669
https://github.com/Wikia/mercury/pull/916 would break page descriptions on Mercury until https://github.com/Wikia/app/pull/7512 is pushed to production. This is a temporary solution to avoid errors.
/cc @bognix @tomasznapieralski
> CONCF-669 Add temporary check to not break descriptions on production

- .gitignore
- gulp/tasks/copy-ts-source.js
Added comment in .gitignore.
Fixed coding standard issue in copy-ts-source.js
> Coding standard fixes for TS sourcemaps

- server/app.ts
This is required by Fastly's varnishes, specifically it tells them that particular object should be cached separately (varied) based on cookie presence - however fastly has additonal logic to whitelist which cookies matter (for instance wikicities_session does matter, but some ad related cookie does not).
More info:
https://wikia-inc.atlassian.net/browse/HG-764
https://wikia-inc.atlassian.net/browse/OPS-6571
https://wikia-inc.atlassian.net/browse/HG-736
> HG-764: Add "cookie" to "vary" header

- bower.json
- front/scripts/main/views/ApplicationView.ts
- front/scripts/mercury/modules/Trackers/Perf.ts
- server/views/_layouts/ember-main.hbs
One of the HG team performance goals is to decrease the time it takes to show the user content. In order to measure this, I set up this performance tracking call. 
The data sent with the request will look like `"data":{"mercury::firstContent":[[10193]]}`
I also removed the conditional to only load weppy code in a production environment. The tracking calls include `env: "dev"`, which is consistent with how MW sends dev calls, so I'm assuming it will be fine to send calls from dev environment to ease development. @wladekb can you confirm?
> HG-761 adding first content perf tracking and sending weppy in dev env

- server/facets/operations/prepareArticleData.ts
This is a convenience for QA and troubleshooting. 
I'm not entirely sure it's in the right place though, b/c that function is called `prepareArticleData`. I'm open to suggestions on where to put it.
> HG-768 adding query string param for bucky sampling

- gulp/options/prod.js
https://github.com/Wikia/mercury/pull/962 caused issue where auth pages didn't have assets loaded (tried to load from https://www.wikia.com/mercury-static/styles/auth/app-2bd62818.css). We had to rollback release-94 because of that.
This is a quick fix to unblock release, I've tested it on sandbox-qa04.
@kenkouot please take a look at the root of this issue, thanks.
/cc @kvas-damian @hakubo
> HG-734 Replace assets path for ember-main.hbs only

- server/facets/auth/authView.ts
- server/facets/auth/login.ts
- test/specs/server/facets/auth/authView.js
https://wikia-inc.atlassian.net/browse/SOC-896
* allow localUrls
* allow subdomains of ```wikia.com```
* allow subdomains of current domain
> SOC-896 | Auth pages - Don't allow redirects to external domains

- front/scripts/main/models/EditModel.ts
Make use of buildUrl when constructing API calls now that it is available so we
support all environments including running it locally.
/cc @rogatty
> Make use of buildUrl when constructing API calls

- front/scripts/main/components/PortableInfoboxComponent.ts
Fix portable infobox logic to be prepared to handle the 'view more' button for linked gallery images. The goal is not to collapse/uncollapse the infobox when user clicked on link or on button (eg. view more button).
> Infoboxes- don't handle infobox collapsing when clicked on button

- test/specs/front/scripts/auth/common/Cookie.js
For some reason, setting cookies in the global test scope caused seemingly unrelated tests to fail. There were 9 failures, each along the lines of: 
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) Article Comments Model reset, resets model properties FAILED
afterEach failed on reset, resets model properties: Attempting to change value of a readonly property.
TypeError: Attempting to change value of a readonly property.
Expected 2 assertions, but 3 were run
at /Users/liz_lux/WebstormProjects/mercury/node_modules/qunitjs/qunit/qunit.js:263
at /Users/liz_lux/WebstormProjects/mercury/www/front/vendor/sinon-qunit/lib/sinon-qunit.js:27
at test (/Users/liz_lux/WebstormProjects/mercury/front/vendor/ember-qunit/ember-qunit.js:252)
at /Users/liz_lux/WebstormProjects/mercury/test/specs/front/scripts/main/models …
```
> Fixing unit tests

- server/facets/operations/prepareMainPageData.ts
https://github.com/Wikia/mercury/pull/999 broke main pages because it didn't add `asyncArticle` property to them. This is a quick, copy paste fix. We're going to refactor this in CONCF-761.
/cc @bognix @lizlux
> HG-753 Add asyncArticle to the main page response

- front/scripts/main/app.ts
- front/scripts/mercury/modules/Trackers/Perf.ts
We want to measure performance of traffic from Japan. Adding country info read by users geo cookie enables filtering per geo for performance data in grafana.
> INT-130: Adding country parameter in context for performance data.

- server/facets/operations/prepareArticleData.ts
The casing didn't match that of the [line above](https://github.com/Wikia/mercury/blob/dev/server/facets/operations/prepareArticleData.ts#L17)
@mari-mcmurtrie
> fixing bucky sampling query param

- front/scripts/main/views/ArticleView.ts
- front/styles/main/module/edit/_addphoto.scss
- front/styles/main/module/edit/_edit-common.scss
- front/styles/main/module/edit/_edit.scss
- front/templates/main/article.hbs
When the section title takes up the whole width of the screen on a mobile device, the edit and photo icons are displaced and moved to a second line. We want these icons aligned in 1 line with section header to avoid displacement. When we show the icons, we shorten section header to make room for icons and display them vertical-top alignment.
> INT-117: Photo/Edit icons style change for Japanese Wikia

- server/app.ts
Fixing issue with country codes that have dashes in them not working well in the auth pages server-side translation code. Setting the `lowerCaseLng` option. 
Here's where that option is referenced: https://github.com/i18next/i18next/blob/master/i18next.js#L1851-L1853
> HG-691 setting option to get locale folders names as all lower case

- front/scripts/mercury/modules/Trackers/Internal.ts
@lizlux @rogatty @mklucsarits @garthwebb @rafalkalinski 
https://wikia-inc.atlassian.net/browse/SOC-1043
We're changing tracker URL as we discovered http:// call is getting blocked on https pages.
It follows https://github.com/Wikia/wikia-vcl/pull/526
> SOC-1043 Use https url for tracking events internally

- front/scripts/main/controllers/ApplicationController.ts
- front/scripts/main/controllers/ArticleController.ts
- front/scripts/main/routes/ApplicationRoute.ts
- front/scripts/main/routes/ArticleRoute.ts
- gulp/tasks/watch.js
This is a bit of a hacky way to get the article comments query param working again. It really seems to belong on the article controller, not the application controller. 
I'm submitting this PR in the interest of time and getting it done within our sprint. I'll continue to look for a better solution though. 
@rogatty @kenkouot @katanka
> Hg 669 Fixing article comments query param regression

- front/scripts/main/router.ts
This adds support for subpages and fixes a bug where redirects from 404 subpages were created malformed redirects.
> Use wild card path for article route

- front/scripts/main/views/ArticleView.ts
- front/templates/main/article.hbs
George in Tokyo office reported on Android app (device and browser info is unknown).
When a user uses native browser for his/her Android phone and tap "add photo" icon, it takes a user straight to capture photo (camera) instead of presenting showing choices of actions (gallery, camera, etc).
> INT-147 Add photo bug on Android/Chrome

- config/localSettings.base.ts
Sample rate for Weppy used to be 1%, now it's 10%. 
https://github.com/Wikia/weppy#sample
> HG-816 upping sampling rate

- gulp/tasks/watch.js
This rebuilds templates properly. The browser sync task still fires too early sometime. Any ideas on that? @rogatty @hakubo
> rebuild templates on watch task

- gulp/tasks/scripts-front.js
- package.json
This implementation is buggy and tends to break the `debugger` statement functionality. My hope is that we're moving to ES6 so we'll no longer need TS source maps. (We may want ES6 source maps but we can handle that later.)
> Disable source maps

- front/scripts/mercury/modules/Trackers/Perf.ts
This sends the `logged_in` flag to weppy.
Related: https://github.com/Wikia/cheetah/pull/156
> HG-769 - sending logged_in flag to weppy

- front/scripts/main/app.ts
- front/scripts/mercury/utils/trackPerf.ts
See https://github.com/Wikia/mercury/pull/1137 for a description of the problem. 
This will fix the spikiness of the graphs as well as the apparent decrease in performance. After loading scripts asynchronously, it became possible for the code that binds the onload event to run after the event already fired. This will check if onload has fired before binding the event, and will send page performance stats if it has.
> HG-816 checking if window is loaded before binding event

- gulp/tasks/build-views.js
- gulp/tasks/watch.js
This should fix the error in `build-views` when a server template is changed.
> HG-810 - only build old way in prod

- front/scripts/main/mixins/EditMixin.ts
- front/scripts/main/models/AddPhotoModel.ts
- front/scripts/main/models/ArticleCommentsModel.ts
- front/scripts/main/models/ArticleModel.ts
- front/scripts/main/models/CuratedContentEditorItemModel.ts
- front/scripts/main/models/CuratedContentEditorModel.ts
- front/scripts/main/models/CuratedContentModel.ts
- front/scripts/main/models/EditModel.ts
- front/scripts/main/models/UserModel.ts
Add assert for all jQuery AJAX call (as described in `jquery.d.ts`) do webStorm's TSLINT is not showing errors.
/cc @rogatty @kenkouot @hakubo
> Add assert with type to all jQuery AJAX calls

- config/localSettings.base.ts
Devboxes are looking for mercury on port 7000. Let's add it as a default so when we start mercury on devbox it doesn't need any additional localSettings to be able to work out of the box.
@rogatty @bognix @rafalkalinski
> Changing default port to work better on devboxes

- config/localSettings.base.ts
Reverts Wikia/mercury#1199
This brakes sandbox environment.
We don't have time to fix this right now, has to be done more holistically
> Revert "Changing default port to work better on devboxes"

- front/scripts/main/controllers/CategoryListItemController.ts
- front/templates/main/components/article-wrapper.hbs
https://wikia-inc.atlassian.net/browse/HG-825
It's a simple fix. There is no need to normalize category title as it's coming from the API without underscores already.
/cc @lizlux @hakubo
> HG-825 Fix itemController deprecation

- README.md
- package.json
This change allows dev box users to remove the sync script.  When working on a devbox it can take over 20s for the call requesting the nonexistent (on the devbox) sync JS resource to timeout, blocking all other JS.
Tagging those active in the ```discuss``` branch pull request, plus the Hg team:
@rogatty, @kenkouot, @nandy-andy, @mklucsarits, @lizlux
> Small change to use --nosync in dev environments

- package.json
This update provides support for parsing JSON from application/hal+json response types, which is needed for requests to new Wikia services API.
/cc @tomasznapieralski @rogatty
> Update Wreck from 5.4.0 to 6.1.0

- server/facets/operations/prepareArticleData.ts
- server/facets/operations/prepareMainPageData.ts
- server/facets/operations/processCuratedContentData.ts
- server/views/_partials/open-graph-tags.hbs
These changes were originally included as part of the Discussions code (https://github.com/Wikia/mercury/pull/1066), so that non-article pages could assign Open Graph tag attributes.
@rogatty @lizlux
> Abstract out Open Graph attributes

- server/facets/auth/authView.ts
- server/views/_layouts/auth.hbs
@rafalkalinski @garthwebb 
https://wikia-inc.atlassian.net/browse/SOC-904
If a URL contains "modal=1" let's get rid of a corporate header and gray background and siplay the raw auth view.
> SOC-904 Do not show header on Auth Pages in modal

- front/scripts/main/components/WikiaInYourLangComponent.ts
Ticket: https://wikia-inc.atlassian.net/browse/INT-163 
Changed condition for not showing wikia-in-your-lang alert from 1 day to 30 days.
> INT-163. Condition is changed from 1 day to 30 days

- front/templates/main/discussion/index.hbs
- server/views/_layouts/ember-main.hbs
I noticed that polymer is loading a few different scripts, causing multiple requests. Since we're not going to release the top-bar component just yet, I moved asset loading to within the discussions pages to we don't pollute production. 
@kenkouot
> movnig polymer asset loading outside of main app for now

- front/scripts/main/router.ts
This PR changes the curated mobile main pages static route from `/` to the legacy MW style route `/wiki/{articleName}`. This is a temporary change intended to fix a P2 (MAIN-5225) until a longer term solution is available.
> Change mainPage route to the MW main page article route

- front/styles/main/module/_ads.scss
- front/templates/main/application.hbs
- front/templates/main/article.hbs
This change moves ad slots out of the main application template. The purpose of this change is to allow content on pages using ```application.hbs``` to easily present content that is flush at the top of the page with the site header, allowing them to instead place ads underneath or wherever they need to go, depending on each page. This was primarily motivated by development of Discussions, which has its own forum header that goes directly underneath the site header. A positive side effect of this change is that the margin above the ad slots no longer depends on the height of site header.
I've added the ad slots for articles into ```article.hbs```. I wasn't sure if ad slots are needed in any of the other main templates. If they are, please say so.
@nandy-andy @hakubo You'll both want to …
> Move ads out of application template

- server/app.ts
@kvas-damian @garthwebb @mklucsarits @rafalkalinski It seems like the discussion namespace is not reachable by the app and we should fix it ASAP since it seems like open-graph needs a label form the translation file.
> Registering discussion i18n namespace to make it visible to the app

- package.json
- server/lib/MediaWiki.ts
https://wikia-inc.atlassian.net/browse/XW-230
Trying to access www.starwars.wikia.com with Mercury was failing because Wreck was sending all requests with the original host, even when redirect location had a different one.
I'll update `package.json` when https://github.com/hapijs/wreck/compare/master...rogatty:before-redirect is merged. I still need to write tests and docs, no need to block P2 fix by that.
/cc @hakubo @Warkot @bognix
> XW-230 Update Host header when there is a redirect

- config/localSettings.dev.ts
For now we show the splash page when discussion link is accessed on production, but we don't need to manually switch the flag enabling discussions on our localSettings since we can use localSettings.dev once to do that.
@kvas-damian
> Discussions | Enable discussions by default on dev env

- server/lib/MainPage.ts
- server/lib/Utils.ts
All these things were causing tslint to show:
(no-trailing-comma) lib/MainPage.ts[176, 49]: trailing comma
(no-string-literal) lib/Utils.ts[213, 62]: object access via string literals is disallowed
(semicolon) lib/Utils.ts[198, 85]: missing semicolon
(semicolon) lib/Utils.ts[218, 54]: missing semicolon
on dev branch.
> Maintenance | Fixing tslint warnings

- front/templates/main/components/lightbox-wrapper.hbs
The mobile lightbox (Mercury lightbox) is hard to be closed since taping on "X" icon doesn't make it disappear. The fix below was cherry-picked from existing pull request https://github.com/Wikia/mercury/pull/1402 as a fix for P3.
> ADEN-2466 Fix close button in mobile lightbox

- server/lib/Utils.ts
- test/specs/server/lib/Utils.js
Recently changes with using `x-original-host` probably broke `externaltest.*` and `showcase.*` domain aliases. Since those are quite edge cases and aren't separated machines we decided to treat it as edge case in Mercury server code.
This is the only idea we came up with as a quick fix. We can try it out tomorrow.
// cc @bognix @vforge @rogatty @hakubo
> ADEN-2464 Fix externaltest on mobile

- front/scripts/main/components/DiscussionHeaderComponent.ts
- front/scripts/main/components/TopBarComponent.ts
- front/scripts/main/components/UserStatusComponent.ts
- front/scripts/main/controllers/DiscussionForumController.ts
- front/styles/main/component/_top-bar.scss
- front/templates/main/application.hbs
- front/templates/main/components/top-bar.hbs
- front/templates/main/discussion/forum.hbs
There were a few styling issues outlined in this ticket https://wikia-inc.atlassian.net/browse/HG-892. Turns out there was weirdness the `userLoggedIn` logic as well as some issues with the headroom JS interaction. I've fixed the headroom JS interaction for the top-bar but the discussions header still needs a bit of work. We can handle that in a separate ticket.
> HG-892 fixing top-nav headroom interaction

- server/views/_layouts/ember-main.hbs
I've added robots meta-tag in order to be consistent with the desktop application and hide staging versions from search engines. The wiki `specialRobotPolicy` variable comes from mediawiki API (see: `MercuryApiController::getWikiVariables()`). 
https://github.com/Wikia/app/pull/8560
> ADEN-2393 adding robots metatag

- front/scripts/main/controllers/ApplicationController.ts
- front/scripts/main/routes/ApplicationRoute.ts
- front/templates/main/application.hbs
- front/templates/main/components/application-wrapper.hbs
Add new action "search" to enable transition into SearchResultsRoute.
This will be activated in a separate PR from enter() in SideNavComponent like so:
if (<optimizely ab test for google search is set>) {
this.sendAction('toggleVisibility', false);
this.send('searchCancel');
this.sendAction('search', value);
} else {
window.location.assign('%@Special:Searchsearch=%@&fulltext=Search'.fmt(Mercury.wiki.articlePath, value));
}
> INT-195: Add search action

- front/scripts/main/components/UserStatusComponent.ts
The alt attribute for the logged in user avatar will be the user's name now, rather than the avatar URL.
> fixing user name in top bar

- front/scripts/main/components/CuratedContentComponent.ts
- front/scripts/main/components/MainPageComponent.ts
- front/scripts/main/components/TrendingArticlesComponent.ts
- front/scripts/main/components/TrendingVideosComponent.ts
- front/scripts/main/components/WikiaStatsComponent.ts
- front/scripts/main/mixins/FeaturedContentMixin.ts
add mw-content class to all modules on main page not main page itself so handleLink function won't handle link to main page on section and category view
JIRA ticket: https://wikia-inc.atlassian.net/browse/XW-461
> XW-461 add mw-content class to all modules on main page

- homepage/server/auth.js
- server/lib/HeliosSession.ts
We are introducing user blocking mechanism to `/info` resource to prevent blocked users from taking any actions on services level. This will be a default  behavior and we don't want it to force it in external clients like Mercury or MW. That's way an additional `noblockcheck` parameter will disable that feature and is introduced here.
More details in SERVICES-851 and in subtasks. Reference PR for MW : https://github.com/Wikia/app/pull/8665
/cc @Wikia/services-team @kvas-damian @bkoval @perjg @lizlux
> [SERVICES-860] Don't check if user is blocked when validating token

- homepage/server/static/popular.json
The UN global banner period is over, so the banner should no longer show on the homepage.
> INT-204: Remove UN global goals banner from Japan HP

- front/styles/main/component/_search.scss
- front/styles/main/component/index.scss
Google Custom Search renders google search results directly into the DOM.
This is just a simple style override to hide one of the elements on the results page.
> INT-195: Styling for google custom search

- front/styles/main/module/article/_table.scss
The original css was causing problems for google custom search rendering. Added .article-content to scope as suggested by @rogatty
> Fixed scoping for table:not for article rendering

- front/scripts/mercury/modules/Ads.ts
- test/specs/front/scripts/mercury/modules/Ads.js
We want to track blocking page views on Mercury, so we add existing module to dependencies and track status with existing GA methods (both profiles: ads and regular).
**Please don't merge it before ADEN-2406 app part is released.**
App PR: https://github.com/Wikia/app/pull/8627
> ADEN-2406 Added detection script and event listeners to track blocking

- front/scripts/main/components/ArticleContentComponent.ts
- front/scripts/main/components/WidgetFliteComponent.ts
- front/templates/main/components/widget-flite.hbs
Make it possible to use `<flite>` tag in articles' content on mercury.
Related PR: https://github.com/Wikia/app/pull/8806
> ADEN-2486 | Add Flite tag support for mercury

- front/scripts/mercury/modules/Ads.ts
- front/scripts/mercury/modules/Trackers/Krux.ts
Those changes should prevent occurring error in console `Krux is not a function` - issue connected with SP detection on mobile.
Details:
Previously `window.Krux` object was used only to load krux module from `Mercury.Modules.Trackers.Krux` (kind of temporary variable?). But `window.Kurx` is a queue-function ([in app code](https://github.com/Wikia/app/blob/dev/resources/wikia/modules/krux.js#L2)) and previous implementation causes an issue when response from krux is relatively slow.
> ADEN-2569 Fix krux implementation

- homepage/bower.json
- homepage/front/scripts/main/globals.ts
- homepage/front/scripts/main/main.ts
- homepage/gulp/tasks/build-combined.js
- homepage/server/facets/globals.js
- homepage/server/routes.js
- homepage/server/views/_layouts/default.hbs
- typings/rsvp/rsvp.d.ts
Refactoring of how globals are sent from backend to frontend.
Previously, this was done by generating a .js file with the globals embedded as variables.
With this change, the globals are returned as json retrieved via a promise and wrapped in a front end class.
> INT-217: Return front end globals for Japan HP via json file

- homepage/front/styles/component/_footer.scss
- homepage/server/views/_partials/footer.hbs
Some of the links in Japan HP footer do not work on mobile, and should only show in desktop mode.
> INT-231: Remove some links from Japan HP footer in mobile view

- front/scripts/main/routes/SearchResultsRoute.ts
- front/scripts/mercury/modules/Trackers/UniversalAnalytics.ts
- front/scripts/mercury/utils/track.ts
We are doing an A/B test for Google Custom Search on Japanese wikias.
We want to track this using the Site Search panel in GA, and this requires that we send an extra pageview impression to GA, which I add in the PR.
Documentation here: 
https://support.google.com/analytics/answer/1012264?hl=en
> GA tracking for google custom search

- front/scripts/main/components/ApplicationWrapperComponent.ts
Track the first `didRender` instead of `didInsertElement` to get more reliable results.
Change `firstContent` to `appRendered` because the former is misleading.
> Track the first didRender instead of didInsertElement

- server/facets/showApplication.ts
Seems like this code was triggering tslint's "no-object-literal" rule to be broken.
> Maintenance | Removing console warnings trigger from discussion code

- front/scripts/main/components/ShareFeatureComponent.ts
Since the functionality was not broken, it was just throwing after opening a social network share url, this should be enough to prevent it.
@hakubo @rogatty @Warkot
> Share Feature | Trigger this.attrs handlers only if they exist

- homepage/front/styles/app.scss
This is a workaround for what appears to be a bug in Safari related to z-order.
See screenshot here:
https://wikia-inc.atlassian.net/browse/INT-245
> INT-245: Workaround for broken z-index in Safari

- front/scripts/main/models/DiscussionForumModel.ts
- front/scripts/main/models/DiscussionPostModel.ts
After scrolling down, older posts are loaded. When trying to upvote loaded posts, nothing happen.
https://wikia-inc.atlassian.net/browse/SOC-1552
Fix is simple: I've added credentials to the loadPage request - after that server sends us all needed data for the upvoting.
> SOC-1552 | Can't upvote post that are lazy-loader

- front/scripts/main/routes/SearchResultsRoute.ts
The extra pageview impression when performing google custom search to track search should only include the path and not the domain.
> Don't include domain name for google search tracking

- README.md
mediawikiDomain was outdated, changed to icache.service.sjc.consul
> mediawikiDomain change

- gulp/tasks/scripts-test-modules.js
Compile to ES6 modules only scripts from `auth`, `main` and `mercury` directories. The rest is handled in `scripts-front` task.
The secret here was the `base: './front/scripts/'` option which I found in `scripts-server` task.
> Fix scripts-test-module task to compile only the files we want it to

- front/scripts/mercury/modules/Trackers/UniversalAnalytics.js
https://wikia-inc.atlassian.net/browse/XW-716
We create new tracker instance every time `mercury/utils/track`'s `track()` or `trackPageView()` is called.
Google wants us to call some methods just once per account.
We should rethink this whole concept but it's out of this ticket's scope.
> XW-716 | Setup UA account only once

- front/scripts/mercury/modules/Trackers/UniversalAnalytics.js
It works when Ember is loaded (it extends array prototype, see http://guides.emberjs.com/v1.10.0/configuring-ember/disabling-prototype-extensions/) but it doesn't on auth pages. Let's drop the fanciness for now.
> XW-812 Use indexOf instead of contains

- front/scripts/main/components/article-wrapper.js
- test/specs/front/scripts/main/components/article-wrapper.js
This PR enables the Mercury section editor globally.
It simply removes the whitelist check in place now: All communities will have section editor enabled unless wiki.disableMobileSectionEditor is set to true.
No other rule changes.
> INT-248: Global rollout of section editor

- server/views/_layouts/ember-main.hbs
- server/views/_partials/nirvana.hbs
In order to make `ext.wikia.adEngine.adTracker` work properly we need to add `window.wgNow` with date when page was initialised (like it's on oasis).
https://wikia-inc.atlassian.net/browse/ADEN-2707
> ADEN-2707 | Added window.wgNow - adTracker dependency

- server/lib/Utils.js
Correct environment value returned on sandbox
```
>>> M.prop('environment');
>>> "sandbox"
```
@rogatty @vforge
> XW | Environment Fix

- front/templates/main/components/wikia-in-your-lang.hbs
Current Wikia-in-your-lang is not working on Mercury because of this missing template file. We want to release the fix asap. The fix was originally implemented as a part of https://github.com/Wikia/mercury/pull/1730 (INT-183) but I separate a release so this alone can go out asap.
> INT-286 | Adding a missing template file so that wikia-in-your-lang pop up works

- package.json
Fixing this issue - https://github.com/systemjs/builder/issues/386 - broke our code.
It changed order of loading our dependencies (app was loaded after model/user.js and CurrentUser, instead being loaded before them)
> XW | change systemjs/builder version to 0.14.11

- package.json
- server/app.js
- server/facets/operations/generateCSRFView.js
- server/routes.js
- server/views/breadcrumb.hbs
For better caching let's remove crumb CSRF protection.
We shouldn't pass CSRF tokens in cookies because:
* we break caching assets - ```Vary: cookie```
* users can't use application in many tabs at once
To solve that we should use hidden input in forms.
> SOC- remove crumb

- homepage/server/facets/signout.js
- homepage/server/routes.js
- homepage/server/views/_partials/userinfo.hbs
To work around the fact that the /logout route has special handling globally, change the logout for Japan HP to /signout instead.
Note that INT-299 depends on this fix, so right now if you log out it will redirect to / but will still show your status as logged in.
> INT-277 | Rename logout handler to signout

- front/scripts/main/mixins/languages.js
@rogatty @kvas-damian 
To avoid confusion, let's delete this method (since it's not used anywhere)
> Maintenance | Removing unused getLanguage method

- homepage/server/facets/signout.js
- homepage/server/index.js
When logging out from the Japan HP, the logged in UI state would remain for a few minutes due to caching. This fixes the issue by forcefully refreshing the cookie when logging out.
> INT-299 | Invalidate cache when signing out

- front/styles/main/module/_loader.scss
- front/templates/main/components/loading-spinner.hbs
`transform-origin` is buggy in firefox currently, so I removed it and wrapped the circle in a svg group that is translated, so there is no need for `transform-origin` on the circle.
https://wikia-inc.atlassian.net/browse/SOC-1549
> SOC-1549 - fixed loading spinner in firefox

- front/styles/main/module/_discussion.scss
After removing the correction of `$theme-bar-height`, the entire first post is now in view on mobile.
https://wikia-inc.atlassian.net/browse/SOC-1863
> SOC-1863 - corrected top margin of forum

- front/common/modules/Ads.js
Prevent throwing JS error (`Uncaught TypeError: Cannot read property 'opts' of null`) on pages without adsContext (i.e. discussions) for logged in users
> ADEN-2846 Prevent throwing JS error on pages without adsContext

- front/common/modules/Ads.js
Mark SP events as non-interaction in order to fix bounce rate calculations
> ADEN-2864 Mark SP events with nonInteraction flag

- front/main/app/models/article.js
https://wikia-inc.atlassian.net/browse/XW-840
It turns out to be very expensive in some cases, e.g. on http://zh.inuyasha.wikia.com/wiki/%E7%8A%AC%E5%A4%9C%E5%8F%89%EF%BC%9A%E5%9C%A8%E5%9C%B0%E7%8B%B1%E9%87%8C%E7%AD%89%E5%BE%85%E7%9A%84%E4%B8%83%E4%BA%BA%E5%B8%AE it blocked rendering for 7 seconds.
Now it's done on server side, see https://github.com/Wikia/app/commit/2b1ec86ffd0b661c0ff2419efd60d03baa9aec84
> XW-840 | Don't use $.trim

- front/main/tests/index.html
Those styles are not needed for tests and they break some colors.
> Fix styles when running Ember tests in a browser

- homepage/front/scripts/main/main.js
- homepage/front/styles/app.scss
- homepage/front/styles/component/_hero.scss
I cannot find a way to fix the padding between slides when using responsive slides for the slider component (http://kenwheeler.github.io/slick/).
To avoid having to change to a different component, or hacking the current component, I've created a workaround for this in software. It is not an ideal solution, but should be good enough for now.
> INT-319 | Fix center alignment for category sliders on Japan HP

- front/common/public/locales/en/discussion.json
- front/main/app/templates/components/post-reply.hbs
Lost commit from here:
https://github.com/Wikia/mercury/pull/1915
> SOC-1924 | new text for the top of reply card

- front/main/app/models/discussion-user.js
This reverts commit f43b51ee3e7f7e1bea1d4e96b010e17e9a94d7b0.
It is a part of the fix for this P2: https://wikia-inc.atlassian.net/browse/SOC-1966
It removes a temporarily hidden "delete-all" button.
> Revert "SOC-1966 | Hiding delete all button"

- front/common/modules/Ads.js
- front/common/tests/unit/modules/Ads.js
Delay AdEngine run using new AdEngineRunner module which is waiting for bidder responses or hardcoded timeout.
**Please, don't merge it before 2/3/2016 (https://github.com/Wikia/app/pull/9553)**
> ADEN-2820 Use AdEngineRunner and move onLoad callback

- front/common/modules/Ads.js
Call `kruxTracker.trackPageView()` earlier - before AdEngine and after bidders.
**Please merge it after/with https://github.com/Wikia/mercury/pull/1902**
> ADEN-2862 Call krux before Ad Engine

- front/common/public/locales/en/recent-wiki-activity.json
- front/main/app/components/article-diff.js
- front/main/app/controllers/article-diff.js
- front/main/app/models/article-diff.js
- front/main/app/templates/article-diff.hbs
- front/main/app/templates/components/article-diff.hbs
Add the ability to undo an edit from a diff page. This also moves the diff page
to a proper component, and limits displaying the undo button to logged-in users.
/cc @Wikia/community-engineering
> (CE-3266) Add the ability to undo an edit from a diff page

- server/app/routes.js
Add a backend handler for /d so it doesn't flash article first before redirecting to discussion on the front-end side.
@rogatty @bognix @rafalkalinski @kvas-damian 
https://wikia-inc.atlassian.net/browse/SOC-1981
> SOC-1981 | Redirect to discussions right away on /d

- front/main/app/index.html
Unfortunatelly when browser get 500 it retries to get the favicon
and on devboxes this url is broken...
and on sandboxes too
since this is low impact I guess we'll have to test it on production
> XW-439 | add favicon to index.html

- front/main/app/initializers/performance-monitoring.js
- front/main/bower.json
- front/main/ember-cli-build.js
We do not use this data at all right now
and it's a hit on performance on our users
~8KB gzipped code less 
We don't hook into every View on every page load
> XW-816 | Disable Ember performance sender

- front/main/app/components/article-diff.js
- front/main/app/services/current-user.js
- front/main/app/templates/components/article-diff.hbs
Add blocked status to current user service and make use of it when
deciding whether or not to show the undo button.
Requires https://github.com/Wikia/app/pull/9674
/cc @Wikia/community-engineering
> (CE-3331) Do not show undo button to blocked users

- front/main/package.json
Yes it's that simple
Why we haven't enabled that before? ...
on June_Dolloway on glee
not gzipped
148050 vs 97052
it almost 60kB less - https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=148050b%20-%2097052b%20in%20kb&es_th=1
gzipped
24186 vs 19381
it 4.8kB less - https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=24186b+-+19381b+in+kb
Same ration is visible on other pages
> enable ember-cli-html-minifier

- front/main/package.json
Reverts Wikia/mercury#1972
After enabling this lib, Ember doesn't finish the building process. When I tried to deploy the latest dev it got stucked for 30 minutes.
@hakubo we need to investigate before merging again.
> Revert "enable ember-cli-html-minifier"

- front/main/app/components/ad-slot.js
- front/main/app/components/article-content.js
- front/main/app/components/article-wrapper.js
- front/main/app/components/featured-content.js
- front/main/app/components/gallery-media.js
- front/main/app/components/infobox-image-collection.js
- front/main/app/components/lightbox-image.js
- front/main/app/mixins/curated-content-editor-sortable-items.js
- front/main/app/mixins/discussion-upvote-component.js
- front/main/app/mixins/languages.js
- front/main/config/environment.js
https://wikia-inc.atlassian.net/browse/XW-802
I did disable prototype extensions for Functions and Strings
As in this case being explicit is easier to reason about what is happening
A left Array extensions - as this does make it easier to write code
disabling that would mean we'd have to wrap any [] in Ember.A()
I tried it and it did not look good - and I think it would lead us to more bugs than it's worth it
> XW-802 | Disable prototype extensions

- front/main/app/services/current-user.js
Reviewed in https://github.com/Wikia/mercury/pull/2044.
* https://wikia-inc.atlassian.net/browse/MAIN-6507
The check for userId being null was moved out of the load method in
this release, leading to this API call being made for anons as well.
This has caused large performance problems, so putting the check
back in as a quick fix.
@owend @hakubo
> (MAIN-6507) Only load user info if the user is not an anon

- front/main/app/index.html
- server/app/views/_partials/tracking-experiment.hbs
* https://wikia-inc.atlassian.net/browse/XW-1173
We want to verify how many page views are we missing in analytics because of the fact that we track them only after Ember is fully loaded. This experiment will send
```
category: 'mercury-app',
action: 'impression',
label: 'analytics-loaded'
```
event to UA as soon as possible. Then we'll compare its number with the one that we already send as soon as Ember is loaded.
@Wikia/x-wing
> XW-1173 | ASAP send an event to UA that user opened a page

- package.json
* https://github.com/embersherpa/ember-cli-app-version
By removing version from package.json I enabled ember-cli-app-version to do that for us
It already uses git latest commit hash and that is enough for us.
@Wikia/x-wing 
PS. We actually talked with the team about that recently - when I found out what it takes to make that work - I lol'ed...
> Add version to Ember inspector

- .github/PULL_REQUEST_TEMPLATE.md
We already have PR labels "in progress" and "don't merge". It makes this line redundant.
Also, I see a lot of PRs merged with description "don't merge". What's the point, then?
@Wikia/x-wing
> Remove "work in progress" from PR template

- front/auth/views/_layouts/auth.hbs
Quantserve was called twice on auth pages because the initialPageView was not set
@Wikia/x-wing
> XW | stop calling quantserve twice on auth

- front/main/app/components/article-content.js
- front/main/app/styles/component/_article-wrapper.scss
- front/main/app/styles/component/index.scss
- front/main/app/templates/components/article-wrapper.hbs
**This is for ~two week experiment**
* https://wikia-inc.atlassian.net/browse/CE-3446 Popover
* https://wikia-inc.atlassian.net/browse/CE-3448 Tracking
* This is ugly! But we don't aim for quality here ;)
* Text is hard coded as it's not going to be translated - test is only on EN wikis.
* Popover is reused from discussions (ember-pop-over) necessary custom styles added. Full width is forced. Properly done it should introduce new flow in flows.js, but for this purpose it's probably enough.
* As we're pinning popover to element within article - again we can't do it ember way and jquery is used to force pop-over opening and `run.later` to wait for pop-over to get aware of element to track click to open
@Wikia/community-engineering  @Wikia/x-wing
> CE-3446 Add popover

- front/main/app/components/collapsible-menu.js
- front/main/app/templates/category.hbs
- front/main/app/templates/components/article-wrapper.hbs
* http://wikia-inc.atlassian.net/browse/XW-1216
* https://wikia-inc.atlassian.net/browse/XW-1232
Unify labels for events related with categories menu under the article. I spotted some not reachable code and I decided to remove it (more details here - https://wikia-inc.atlassian.net/browse/XW-1232)
@Wikia/x-wing
> XW-1216 | Unify labels for events related with categories menu under the article

- front/main/app/components/article-content.js
- front/main/app/styles/component/_article-wrapper.scss
* https://wikia-inc.atlassian.net/browse/CE-3445
Highlight text by setting background (we cannot highlight text in ios from javascript)
> CE-3445: Highlight text on ios

- front/auth/bower.json
- front/main/bower.json
https://github.com/Wikia/style-guide/releases/tag/v1.8.3
Let's update the dependency to use the newest style-guide version
@vforge @Warkot  @rafalkalinski
> StyleGuide | Update to 1.8.3

- front/main/app/components/article-content.js
- front/main/app/components/article-wrapper.js
* https://wikia-inc.atlassian.net/browse/CE-3429
* https://wikia-inc.atlassian.net/browse/CE-3430
Destroy event bindings after transition to different page
CR done in https://github.com/Wikia/mercury/pull/2129
> Highlighted text: Destroy event bindings

- server/app/routes.js
* https://wikia-inc.atlassian.net/browse/DAT-3907
https://github.com/Wikia/mercury/commit/68b0b74afcfdb28e6f2137d857aeb2051f796050 introduced a regression which causes situation where we don't load adsContext properly on pages like http://starwars.wikia.com/main/category/Saga_films.
> DAT-3907 | Fix ads on CMP categories

- front/main/app/components/article-wrapper.js
- https://wikia-inc.atlassian.net/browse/CE-3494
Since the Optimizely experiment had to be stopped - we want the users we already enabled it for to see the editor when they want to edit. Assuming that the editor is hard to find (low percentage of people selecting text on websites) - we want to enable it for EN communities.
@Wikia/community-engineering .
> CE-3494 Enable the HTE on all EN communities without surfacing it

- front/common/public/locales/en/infobox-builder.json
- front/main/app/components/infobox-builder-item-image.js
- front/main/app/templates/components/infobox-builder-item-image.hbs
* https://wikia-inc.atlassian.net/browse/DAT-3924
Remove image captions from infobox builder preview in order not to confuse users.
@dianafa, @SebastianMarzjan, @idradm, @rybmat, @nikodamn
> DAT-3924, remove captions from infobox builder preview

- front/main/app/styles/component/_curated-content-editor.scss
Found an issue with overflow/ellipsis on http://cocktails.wikia.com/main/edit and fixed it, because for long titles it prevented moving the items up/down.
@rogatty @hakubo @bognix @vforge
> Fix overflow in item rows in Curated Content Edit Tool

- front/main/app/components/feedback-form.js
JS console was throwing this error:
```
Uncaught Error: Could not find module `common/modules/AbTest` imported from `main/components/feedback-form`
```
All filenames, paths and the imports have to be lowercase. Linux machines, on which our app works, are case sensitive.
@Wikia/x-wing @adamkarminski @lukaszkonieczny @kamilkoterba
> fix abtest module import by lowercasing its path

- front/main/app/components/feedback-form.js
* http://wikia-inc.atlassian.net/browse/CE-3527
The fix for banner not being reset on iOS when a user went to another route.
> CE-3527 Reset iOS related properties also

- front/main/app/components/feedback-form.js
- front/main/app/templates/components/feedback-form.hbs
* http://wikia-inc.atlassian.net/browse/CE-3531
We realised that for some initial questions a follow-up questions and a placeholder make no sense. This PR fixes it.
@Grunny
> CE-3531 Use accurate messages and placeholders for different feedback questions

- .npmrc
- package.json
* https://github.com/Medium/phantomjs/issues/501
* https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs
* https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/CHANGELOG.md#100-2016-01-28
I've bumped into an error preventing me from installing node dependencies. It's described in the linked PhantomJS issue and the suggested fix is to use a mirror instead of BitBucket to download the binary.
I've also upgraded `karma-phantomjs-launcher` which has some bug fixes including:
>use phantomjs-prebuilt instead of deprecated phantomjs
@Wikia/x-wing
> Fix PhantomJS issues

- server/app/facets/article-preview.js
Fixes https://kibana.wikia-inc.com/#dashboard/temp/AVOo4zfEtlVOnUfDkxgN
```
TypeError: undefined is not a function
at /usr/wikia/mercury/3246/server/app/facets/article-preview.js:107:32
at bound (domain.js:291:14)
at runBound (domain.js:304:12)
at tryCatcher (/usr/wikia/mercury/3246/server/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/usr/wikia/mercury/3246/server/node_modules/bluebird/js/main/promise.js:507:31)
at Promise._settlePromiseAt (/usr/wikia/mercury/3246/server/node_modules/bluebird/js/main/promise.js:581:18)
at Promise._settlePromises (/usr/wikia/mercury/3246/server/node_modules/bluebird/js/main/promise.js:697:14)
at Async._drainQueue (/usr/wikia/mercury/3246/server/node_modules/bluebird/js/main/async.js:123:16)
at Async._drainQueues …
```
> XW | Fix cache control in article preview

- front/main/app/components/fandom-posts.js
- front/main/app/templates/components/fandom-posts.hbs
https://wikia-inc.atlassian.net/browse/RECIRC-86
We want to add UTM tracking information to Fandom links so we can better track from the Fandom side which traffic is coming from our Recirculation efforts
> RECIRC-86: Add utm tracking code to Fandom links in footer

- front/main/app/symbols/main/chevron-linked.svg
When fixing the visibility and refactoring of the chevron-linked.svg last time, the svg became unnecessarily and unintentionally bolder.
@vforge
> XW-update-chevron | bring back the thinner style of chevron-linked.svg

- front/main/app/styles/module/article/_portable-infobox.scss
Increased z-index to cover media component chevrons.
It was a bug and it was causing selenium tests to fail.
@Wikia/x-wing
> XW-fix-pi-expand-button | increased z-index

- front/common/utils/track-perf.js
- front/main/app/index.html
- front/main/app/initializers/performance-monitoring.js
- server/app/views/_partials/first-render-time.hbs
* https://wikia-inc.atlassian.net/browse/XW-1302
* https://davidwalsh.name/css-animation-callback
We want to know when users actually see the content and it turns out that `domContentLoaded` isn't the correct event to measure that.
Instead, let's use an empty element with CSS transition applied and measure when the transition is finished. I've run some tests on http://webpagetest.org and it seems that this time is the correct one to measure.
@Wikia/x-wing
> XW-1302 | Add firstRenderTime measurement

- front/main/app/templates/components/article-wrapper.hbs
* https://github.com/Wikia/mercury/pull/2360
Remove leftover which prevents Ember from starting.
@Wikia/x-wing @adamkarminski
> Remove article-edit-highlighted-entrypoint from article-wrapper

- front/main/app/controllers/main-page.js
- front/main/app/mixins/main-page-route.js
- front/main/app/models/curated-content.js
- front/main/app/routes/application.js
- front/main/app/utils/wiki-handlers/wiki-page.js
Hapi was doing some special encoding/decoding when passing data to client. Because of that we had a lot of encoding/decoding on the client side. Without Hapi we can remove this logic.
All encoding is handled by:
* `M.buildUrl` when it comes to creating URLs
* Ember when it comes to transitions to different routes
* Handlebars when it comes to displaying data to user
@Wikia/x-wing
> XW | clean up encoding

- front/main/app/styles/module/_site-footer.scss
Fix broken ember build after node-sass dependency upgrade. The removed line probably was always causing error but before last node-sass upgrade it was silent.
https://github.com/sass/libsass/issues/1670
@Wikia/x-wing
> ramove style referencing to unexisting class - to release

- front/main/bower.json
* https://github.com/Wikia/mercury/pull/2404
https://github.com/carhartl/jquery-cookie repo is now working correctly. Let's use it again.
> XW | Revert temporary fix for jquery-cookie

- front/main/bower.json
Reverts Wikia/mercury#2414 which is no longer required.
> Revert "XW-1445 | Update headroom"

- front/main/app/models/wiki/article.js
- front/main/app/models/wiki/category.js
* http://wikia-inc.atlassian.net/browse/XW-1449
* https://github.com/Wikia/mercury/pull/2423
We are calling `indexOf` on `displayTitle` and `title` when they are not set.
This case happens when category page has no article and on main pages
@Wikia/x-wing
> XW-1449 call displayTitle only when it's set

- front/main/app/models/wiki/article.js
- front/main/app/models/wiki/category.js
* http://wikia-inc.atlassian.net/browse/XW-1449
* https://github.com/Wikia/mercury/pull/2424
We are calling `indexOf` on `displayTitle` and `title` when they are not set.
This case happens when category page has no article and on main pages
@Wikia/x-wing
> XW-1449 check if displayTitle exists before calling it	

- .eslintrc
* https://github.com/Wikia/guidelines/pull/110
As per discussion in guidelines https://github.com/Wikia/guidelines/pull/110, we're relaxing `.eslintrc` rules to allow multiple `let` and `consts`. Developers should still produce sane code with provided examples.
/cc @Wikia/x-wing @hakubo
> XW | Relax .eslintrc on-var rule

- front/main/app/components/article-content.js
- front/main/app/components/article-wrapper.js
- front/main/app/controllers/article-preview.js
- front/main/app/mixins/hero-image.js
- front/main/app/mixins/portable-infobox-hero-image.js
- front/main/app/styles/component/wikia-ui-components/_wiki-page-header.scss
- front/main/app/styles/layout/_article-preview.scss
- front/main/app/templates/article-preview.hbs
- front/main/app/templates/components/wikia-ui-components/wiki-page-header.hbs
* http://wikia-inc.atlassian.net/browse/XW-1480
Redesign of the top of the article implementation, header to be more precise, changes how the header + infobox is handled. This fixes the issue when no hero image and title was shown.
@Wikia/x-wing @Wikia/west-wing
> XW-1480 | Add new header to mobile article preview

- front/main/app/styles/component/wikia-ui-components/_wiki-page-header.scss
* http://wikia-inc.atlassian.net/browse/DAT-4206
* PR to `dev` https://github.com/Wikia/mercury/pull/2449
P2 fix for broken Special:InfoboxBuilder.
@Wikia/x-wing @Wikia/west-wing
> DAT-4206 | hide first title/hero image of the first portable infobox only in article context

- front/main/app/styles/component/wikia-ui-components/_wiki-page-header.scss
* http://wikia-inc.atlassian.net/browse/DAT-4206
Using old app code (without moving portable infobox to top of the article) revealed a flaw, that stuff that should be hidden is not in such case. This updated selector fixes that. Still true fix for hiding it is on the way with the cleanup.
@Wikia/x-wing @nikodamn
> DAT-4206 | hide hero image/title even if first infobox fails to be moved to top

- homepage/.eslintrc
- homepage/front/.eslintrc
* https://wikia-inc.atlassian.net/browse/XW-1490
Automatic Mercury's deployment to stable fails because it's coupled with homepage which fails with:
```
/data/deploytools/build/homepage.jenkins.3bdaa440-1b7a-11e6-bd09-0cc47abb551a/homepage/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-validator.js:102
throw new Error(message.join(""));
^
Error: /data/deploytools/build/homepage.jenkins.3bdaa440-1b7a-11e6-bd09-0cc47abb551a/.eslintrc:
Configuration for rule "quotes" is invalid:
Value "[object Object]" must be an enum value.
```
This PR fixes eslint configuration and therefore should fix the stable's deploy.
@Wikia/x-wing @kvas-damian
> XW-1490 | Fix eslint configuration for homepage

- front/main/app/styles/module/edit/_edit-common.scss
* http://wikia-inc.atlassian.net/browse/DAT-4289
Setting flex properties to default ones (by removing the declaration) should make the icons show in the viewport.
@Wikia/x-wing @Wikia/west-wing
> DAT-4289 | header upload/edit icons fixed on Safari

- front/main/app/components/article-media-thumbnail.js
- front/main/app/components/content-recommendation-thumbnail.js
- front/main/app/styles/component/_article-media-thumbnail.scss
- front/main/app/styles/component/wikia-ui-components/_wiki-page-header.scss
- front/main/app/styles/mixin/index.scss
- front/main/app/styles/mixin/is-loading.scss
- front/main/app/templates/components/article-media-thumbnail.hbs
- front/main/app/templates/components/content-recommendation-thumbnail.hbs
- server/app/views/_partials/wiki-page-header.hbs
* https://wikia-inc.atlassian.net/browse/DAT-4277
Instead of displaying loading spinner on images let's use the same pulsating background which we use on hero image.
@Warkot @vforge
> DAT-4277 | Replace loading spinner with pulsating background on images

- front/main/app/index.html
- front/main/app/templates/components/site-head.hbs
- server/app/views/_layouts/error.hbs
- server/app/views/_partials/site-head.hbs
- server/app/views/article.hbs
* https://wikia-inc.atlassian.net/browse/DAT-4236
Unify pre-ember site head markup with the final one. Fixes the issue with article header's position.
Also removes the empty ad-slot placeholder because page jumps anyway and it looked bad.
@Wikia/x-wing
> DAT-4236 | Fix site head markup

- front/main/app/routes/curated-content-editor.js
* http://wikia-inc.atlassian.net/browse/DAT-4334
isForbiddenError expects an error as an argument, not error.status which is undefined.
@Wikia/x-wing @hakubo
> DAT-4334 | pass error to isForbiddenError not error.status which is undefined

- front/main/app/templates/components/article-contribution.hbs
* https://wikia-inc.atlassian.net/browse/JPN-565
Add photo on mercury does not work when the user is logged out.
{{action 'addPhoto'}} was missing for when the user is logged out (addPhotoAllowed set to false).
When user is logged in, the same action needs to be on the input tag, so I changed the nesting to render differently based on the state of addPhotoAllowed. The event handler addPhoto handles both cases correctly.
@hakubo
> JPN-565 | Fix for add photo button broken when logged out

- front/main/app/components/portable-infobox.js
- front/main/app/mixins/ads.js
- front/main/app/styles/module/_ads.scss
* https://wikia-inc.atlassian.net/browse/DAT-4486
place mobile_top_leaderboard between first and second viewport
@Wikia/west-wing  @vforge @bognix
> DAT-4486 experiment: place mobile_top_leaderboard between first and second viewport

- front/main/package.json
* https://github.com/rogatty/broccoli-asset-rev/commit/93dcaf10a730d886333db1c3a6cdc61fedd687bc
* https://github.com/rickharrison/broccoli-asset-rewrite/pull/35
Fix the issue with assets fingerprinting by using a fork of broccoli-asset-rev which locks the version of broccoli-asset-rewrite.
@hakubo @kvas-damian
> Use a fork of broccoli-asset-rev to lock broccoli-asset-rewrite@1.0.9

- .npmrc
* https://github.com/Wikia/mercury/pull/2227
Mirror that we use is sometimes very slow and it takes few minutes to download PhantomJS. It doesn't make much sense to use it.
@tomasznapieralski
> Stop using mirror for PhantomJS

- front/main/app/routes/application.js
- front/main/app/utils/article-link.js
- front/main/tests/unit/utils/article-link-test.js
* https://wikia-inc.atlassian.net/browse/DAT-4579
* https://github.com/Wikia/app/pull/10787
If a local article URL has a query param, we should treat it as a full external
URL if it is not handled elsewhere. Manual local URLs with query params created by
users are already handled as the MediaWiki parser adds the external class which
is already checked in Mercury.
This is an extra safety check in case any extensions add URLs with query params
(as TabView did) so that they don't result in a broken page when clicked.
action=render is removed from the TabView links in https://github.com/Wikia/app/pull/10787.
@Wikia/x-wing
> (DAT-4579) Treat local URLs with query parameters as external URLs

- front/main/app/components/article-content.js
- front/main/app/mixins/recirculation-experiment.js
- front/main/app/models/top-links.js
- front/main/app/styles/component/_recirculation-experiment.scss
- front/main/app/templates/components/recirculation/footer.hbs
* https://wikia-inc.atlassian.net/browse/RECIRC-168
Placement test components were not getting properly torn down in-between article transitions causing duplication to occur. We fix this by adding that component to article-contents `renderedComponents` array.
@Wikia/x-wing
> RECIRC-168: Add placement test to renderedComponents for proper teardown

- front/main/app/components/discussion-post-card-top-note.js
- front/main/app/components/discussion-welcome.js
- front/main/app/helpers/wrap-me.js
- front/main/tests/unit/helpers/wrap-me-test.js
* https://wikia-inc.atlassian.net/browse/XW-1735
* https://github.com/Wikia/mercury/pull/2625
Make sure the wrap-me helper escapes the content passed to it by default. See ticket
for details.
Reviewed in and backported from https://github.com/Wikia/mercury/pull/2625
/cc @Wikia/x-wing
> (XW-1735) Escape content of wrap-me helper by default

- front/common/modules/ads.js
- front/main/app/components/ad-slot.js
- front/main/app/mixins/ads.js
- front/main/app/templates/article.hbs
- front/main/app/templates/category.hbs
- front/main/app/templates/components/article-wrapper.hbs
- front/main/app/templates/components/main-page.hbs
- front/main/app/templates/main-page.hbs
- front/main/tests/unit/components/ad-slot-test.js
* https://wikia-inc.atlassian.net/browse/ADEN-3584
The new slot: BOTTOM_LEADERBOARD is going to be filled only when there is Fan Takeover product visible.
Merge pull request #2645 from Wikia/ADEN-3584-blb-for-uap-only
ADEN-3584 Remove BLB from non-UAP scenarios
> ADEN-3584 Ported tested changes from dev branch

- server/config/localSettings.base.js
* http://wikia-inc.atlassian.net/browse/XW-1786
Our selenium tests are using library which intercepts all browser requests, but because we are using also some kind of proxy, this library is not catching https requests but just http.
@Wikia/x-wing
> XW-1786 | get google script from http instead of https (temporary)

- front/main/app/components/discussion-standalone-editor.js
- front/main/app/mixins/discussion-editor-category-picker.js
- front/main/app/styles/component/_discussion-category-picker.scss
- front/main/app/templates/components/discussion-inline-editor.hbs
- front/main/app/templates/components/discussion-standalone-editor.hbs
http://wikia-inc.atlassian.net/browse/SOC-2421
We are supposed to hide category picker from a user when there's just one category on a community
> SOC-2421 | Hide category picker when a community has only 1 category

- front/main/app/mixins/recirculation-experiment.js
* https://wikia-inc.atlassian.net/browse/RECIRC-197
UTM tracking is causing an issue with our session information within GA. Removing to see if it helps the issue
> RECIRC-197: Remove UTM tracking from recirc experiments

- front/main/app/components/discussion-entities-list-layout.js
- front/main/app/components/discussion-filters.js
- front/main/app/components/discussion-post-card-detail.js
- front/main/app/controllers/discussion/base.js
- front/main/app/mixins/discussion-categories-visibility.js
- front/main/app/templates/components/discussion-entities-list-layout.hbs
- front/main/app/templates/components/discussion-filters.hbs
- front/main/app/templates/components/discussion-forum-wrapper.hbs
- front/main/app/templates/components/discussion-header.hbs
- front/main/app/templates/components/discussion-post-card-detail.hbs
- front/main/app/templates/components/discussion-post-details-layout.hbs
- front/main/app/templates/components/discussion-post.hbs
- front/main/app/templates/components/discussion-reported-posts-wrapper.hbs
- front/main/app/templates/components/discussion-standalone-layout.hbs
- front/main/app/templates/components/discussion-user-list-wrapper.hbs
- front/main/app/templates/discussion/forum.hbs
- front/main/app/templates/discussion/post.hbs
- front/main/app/templates/discussion/reported-posts.hbs
- front/main/app/templates/discussion/user.hbs
* http://wikia-inc.atlassian.net/browse/SOC-2838
We want discussions to look exactly like before if admins don't add any more categories. This code is hiding category UI in desktop rail / mobile filters menu and category names from post cards if there's only one category.
> SOC-2838 | Hide categories UI for communities with 1 category

- front/main/app/templates/discussion/user.hbs
* https://wikia-inc.atlassian.net/browse/SOC-2926
enable to edit title on posts by user page
@bkoval
> SOC-2926 | fix: enable to edit title on posts by user page

- front/main/app/components/discussion-guidelines-editor.js
* https://wikia-inc.atlassian.net/browse/SOC-2946
Staff, Helper, Admin, Discussions Moderator can not edit Discussions Guidelines
@bkoval
> SOC-2946 | fix: add check for permission in guidelines editor

- front/main/app/styles/component/_discussion-community-badge.scss
* https://wikia-inc.atlassian.net/browse/SOC-2974
Discussions: community avatars are stretched on preview
@bkoval
> SOC-2974 | fix: change discussions community badge dimensions

- front/main/app/styles/component/design-system/_global-navigation.scss
* https://wikia-inc.atlassian.net/browse/XW-2028
Override color set in https://github.com/Wikia/mercury/blob/dev/front/main/app/styles/theme/_dark.scss#L75
@Wikia/x-wing
> XW-2028 Fix label color on dark theme

- front/main/app/models/wikia-nav.js
- front/main/tests/unit/models/wikia-nav-test.js
* https://wikia-inc.atlassian.net/browse/XW-2013
Instead of using the old Global Navigation API (data from it comes to Mercury together with the wiki variables) for the mobile navigation we want to use a mix:
- hubs and global links controlled by the Design System API
- local nav controlled by the old API
This is only a temporary solution until we rewrite the mobile nav to be compliant with the Design System.
@Wikia/x-wing
> XW-2013 Use DS API for mobile global navigation

- front/main/config/environment.js
It currently produces errors in console and we're waiting for NR to fix it.
```
Uncaught TypeError: Cannot read property 'type' of undefined
```
@hakubo
> Disable NewRelic Browser

- front/main/app/templates/components/discussion-user-list-wrapper.hbs
* https://wikia-inc.atlassian.net/browse/SOC-3137
Add zero state for /u.
> SOC-3137 | fix: add zero state for user with no posts

- server/app/facets/mediawiki-page.js
- server/app/facets/show-application.js
- server/app/facets/show-curated-content.js
- server/app/lib/custom-errors.js
- server/app/lib/mediawiki.js
- server/tests/acceptance/application.js
- server/tests/acceptance/curated-content.js
- server/tests/acceptance/wiki-page.js
* https://wikia-inc.atlassian.net/browse/XW-1737
While handling `wikiVariables` response we can get redirect to a HTML page instead of JSON API response. Instead of trying to display that page in mercury let's redirect user to that page so browser can render it.
@Wikia/x-wing
> XW-1737 | Handle wikiVariables non-JSON API response as a redirect

- front/main/app/styles/component/discussion/_discussion-categories-edit.scss
* https://wikia-inc.atlassian.net/browse/SOC-2830
'x' button and button to reorder categories misplaced on desktop
> SOC-2830 | fix: move remove category icon to proper place in edit mode

- front/main/app/components/discussion-inline-editor.js
- front/main/app/components/discussion-textarea-with-counter.js
- front/main/app/templates/components/discussion-inline-editor.hbs
- front/main/app/templates/components/discussion-textarea-with-counter.hbs
* https://wikia-inc.atlassian.net/browse/SOC-2911
Textareas in inline editor is readonly by default. It's editable only when editor is active.
> SOC-2911 | fix: inline editor textarea is readonly if editor isn't active

- front/auth/app/common/auth-utils.js
- front/auth/app/signup/signup-form.js
- server/app/views/_partials/first-render-time.hbs
* http://wikia-inc.atlassian.net/browse/XW-2208
Use `window.performance` instead of `performance`. This should fix `Can't find variable` issue in Safari 9.
@Wikia/x-wing
> XW-2208 | Stop using `performance` global directly

- front/common/modules/ads.js
MercuryPV key-val was not sent becasue it was added too late. Moving it three lines above fixes the issue (above `startOnLoadQueue` call)
...and it has to be a string not an int.
> ADEN | fix mercuryPV key-val not appearing for regular slots

- front/main/app/templates/components/discussion-reported-posts-wrapper.hbs
* https://wikia-inc.atlassian.net/browse/SOC-3269
Fix for /d/reported zero state.
> SOC-3269 | fix: zero state on /d/reported

- front/main/app/components/discussion-community-unit.js
- front/main/app/templates/components/discussion-community-unit.hbs
* http://wikia-inc.atlassian.net/browse/SOC-3258
Seems like the href-to helper messes up links with just "/" in them.
> SOC-3258 | Use full url instead of / for anchor

- front/main/app/mixins/discussion-forum-actions-route.js
* http://wikia-inc.atlassian.net/browse/SOC-3267
"Undefined" is actually a proper page param - it is an implicit page number for the first page. Editor was malfunctioning because we do transition from 'trending' to 'latest' before adding a post and in this case, after failing the isProperPageParam check, the transition would abort and instead refresh the whole route.
> SOC-3267 | No page param is a proper page param

- front/main/app/mixins/discussion-editor-configuration.js
* https://wikia-inc.atlassian.net/browse/SOC-3383
Show "Write a reply..." while editing reply with no text.
> SOC-3383 | fix: show Write a reply when removed text while editing reply

- front/main/app/styles/state/_full-screen.scss
* https://wikia-inc.atlassian.net/browse/SOC-3310
Remove overflow: hidden on mobile-full-screen class. 
> SOC-3310 | remove overflow: hidden on mobile-full-screen class

- front/main/app/routes/discussion/base.js
1) When there's a model loading error (4xx, 5xx from the backend etc.) it's ok to proceed with the error subroute
2) If any other kind of error has been thrown, and caught by catch() blocks, we should rethrow immediately in error() callback to improve verbosity of logs.
Now, instead of "model.set is not a function" for all the non-Ember errors we'll actually see the proper error message.
> Discussions | Improving error messages in console

- front/main/app/templates/components/image-review.hbs
https://wikia-inc.atlassian.net/browse/SER-555
Remove back button from Image-review's main page.
> Remove back button from image-review main page

- front/main/bower.json
* https://wikia-inc.atlassian.net/browse/PLATFORM-2766
* https://github.com/Wikia/vignette-js/pull/29
Bump vignette-js to v2.3.0 to support .us and .pl devbox domains.
@rogatty
> (PLATFORM-2766) Bump vignette-js to v2.3.0

- front/common/public/locales/en/discussion.json
- front/main/app/router.js
* https://wikia-inc.atlassian.net/browse/SOC-3778
change "User activity" to "Discussion Insights"
> SOC-3778 | change "User activity" to "Discussion Insights"

- front/main/app/components/curated-content-section.js
- front/main/app/templates/components/curated-content.hbs
- front/main/tests/acceptance/curated-content-test.js
- server/app/views/_partials/curated-main-page/curated-content-section.hbs
* https://wikia-inc.atlassian.net/browse/XW-2625
Having class names is easier for writing selenium tests
Ping @Wikia/x-wing
> XW-2625 | CMP sections - use class name instead of inline styles

- front/common/utils/track-perf.js
- server/config/settings.base.js
* https://wikia-inc.atlassian.net/browse/ZZZ-16699
* https://github.com/Wikia/mercury/pull/2598
These wikis were sampled at 100% because they were using an experimental Mercury instance. We should have cleaned this long time ago but apparently forgot to do that. This is skewing our RUM.
@hakubo @kvas-damian
> XW | Remove special wikis from weppy sampling

- front/main/bower.json
- server/npm-shrinkwrap.json
- server/package.json
* http://wikia-inc.atlassian.net/browse/PLATFORM-2856
Bump vignette-js version to remove client-side detection of WebP support.
/cc @Wikia/core-platform-team
> (PLATFORM-2856) Bump vignette-js version

- front/main/app/models/wikia-nav.js
- server/tests/fixtures/wiki-variables.json
* https://wikia-inc.atlassian.net/browse/XW-2575
GlobalNavigation is not used anymore as the data is coming from a separate api. 
@Wikia/x-wing
> XW-2575 | Removal of old GlobalNavigaton

- front/main/app/styles/module/_ads.scss
* https://wikia-inc.atlassian.net/browse/ADEN-4810
Close button is not correctly displayed on floor adhesion ad on mobile
> ADEN-4810 | fix: show close icon for adhesion on mobile

- tasks/jenkins/mercury-pr-checks.sh
That's how it's called now:
http://jenkins.wikia-prod:8080/view/Mercury-test/view/Mercury%20Background%20Tasks/job/mercury-update-dependencies/
@latata @kvas-damian
> Fix Jenkins workspace path

- front/auth/bower.json
- front/main/bower.json
- front/main/npm-shrinkwrap.json
- front/main/tests/acceptance/curated-content-editor-test.js
- front/main/tests/index.html
- npm-shrinkwrap.json
- server/npm-shrinkwrap.json
- server/package.json
* https://wikia-inc.atlassian.net/browse/XW-2995
i18next upgraded
in front and auth upgraded to 1.11.5
in server just to 1.10.6 as there was no 1.11.x versions available in npm
@Wikia/x-wing
> XW-2995 | i18next update from 1.7.4 to 1.11.5

- server/app/views/_partials/tracking-quantserve.hbs
ADEN-4803 Fix Quantcast tracking for consecutive page views
* https://wikia-inc.atlassian.net/browse/ADEN-4803
* https://github.com/Wikia/mobile-wiki/pull/36
* https://github.com/Wikia/mobile-wiki/pull/37
* https://github.com/Wikia/mercury/pull/3118
Fixes Quantcast tracking for consecutive page views.
@Wikia/x-wing
> ADEN-4803 Fixed Quantcast tracking for consecutive pageviews

- front/auth/app/common/auth-tracker.js
- server/app/facets/auth/auth-view.js
When HAPI gets context it injects all the variables in the <script> tag. This PR will parse forceLogin (which caused the P2), so only boolean values will be returned. Just to be on the safe side the parentOrigin will additionally get escaped.
* http://wikia-inc.atlassian.net/browse/IRIS-4179
> IRIS-4179 | Escape the query params

- front/main/bower.json
- server/npm-shrinkwrap.json
- server/package.json
* https://wikia-inc.atlassian.net/browse/PLATFORM-2786
Bump vignette-js version to generate HTTPS vignette URLs.
/cc @Wikia/core-platform-team
> (PLATFORM-2786) Bump vignette-js version

- front/main/app/index.html
- server/app/views/_partials/apple-touch-icon.hbs
* https://wikia-inc.atlassian.net/browse/MAIN-10098
* https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
Apple browsers such as Safari and Mobile Safari issue a request to `/apple-touch-icon.png` (and its different size variants) by default. Since we are not configuring any custom icon URL via a `link` tag (as described in the second link), such requests fail with error 404 and ugly VCL hack is needed to rewrite them into URLs to Wiki.png in Vignette.
This change allows us to get rid of VCL hack by using a single source of truth for apple-touch-icon: the MediaWiki app. URL and size config is fetched from MediaWiki along with the rest of wiki variables and output in a link tag. …
> MAIN-10098: Get apple-touch-icon URL from MW and serve it

- front/main/app/styles/module/_ads.scss
It turns out that we should not override IMA's inline styles because some vpaids are styled base on those defaults. Instead of overriding IMA properties everywhere we can adjust styles for UAP units only and keep defaults for all standalone players.
Connected with: https://github.com/Wikia/app/pull/12765
* http://wikia-inc.atlassian.net/browse/ADEN-5009
> ADEN-5009 Center absolute IMA div

- front/main/app/components/discussion-editor.js
* http://wikia-inc.atlassian.net/browse/IRIS-3818
Make sure that discussion post titles contain non-whitespace characters.
> IRIS-3818 - don't allow titles that are only whitespace

- front/main/app/components/design-system/global-navigation-link-authentication.js
- front/main/app/controllers/application.js
- front/main/app/templates/application.hbs
- front/main/app/templates/components/application-wrapper.hbs
- front/main/app/templates/components/design-system/global-navigation-account-navigation.hbs
- front/main/app/templates/components/design-system/global-navigation.hbs
* http://wikia-inc.atlassian.net/browse/IRIS-4225
Includes a `redirect` query parameter back to the current page when sending users to auth pages from the global nav.
> IRIS-4225 - include redirect param in global nav auth links

- front/main/app/components/discussion-post-card-top-note.js
- front/main/app/styles/module/_discussion.scss
- front/main/app/styles/theme/_dark.scss
- front/main/app/templates/components/discussion-post-card-detail.hbs
- front/main/app/templates/components/discussion-post-card-reply.hbs
- front/main/app/templates/components/discussion-post-card-top-note.hbs
* http://wikia-inc.atlassian.net/browse/IRIS-3887
Adds an undelete button to the top note of deleted posts and replies.
> IRIS-3887 - add undelete button to deleted post top note

- front/main/app/mixins/discussion-editor-category-picker.js
* http://wikia-inc.atlassian.net/browse/IRIS-3826
Rely on the `canMove` attribute returned from discussions instead of the `threads:move` permission to decide whether a user can edit categories on a post.
> IRIS-3826 - remove dependency on threads:move permission to edit categories

- server/app/facets/operations/signout.js
* https://wikia-inc.atlassian.net/browse/PLATFORM-3075
Send access token in signout request rather than the UserId header which
will no longer be used going forward.
@Wikia/core-platform-team @slayful
> (PLATFORM-3075) Send access token in signout request

- front/auth/app/common/login.js
- front/auth/app/facebook/facebook-login.js
- front/auth/views/_partials/auth/signin.hbs
- front/auth/views/auth/desktop/register.hbs
- front/auth/views/auth/desktop/signin.hbs
- front/auth/views/auth/mobile/join-page.hbs
- server/app/app.js
- server/app/facets/auth/join.js
- server/app/facets/auth/register.js
- server/app/facets/auth/signin.js
- server/app/facets/operations/signin.js
- server/app/routes.js
- server/package.json
Use proxies for login routes in auth pages and implement crumb
for CSRF protection.
> (PLATFORM-2925) Use proxies for login routes in auth pages

- front/main/app/styles/theme/_dark.scss
* http://wikia-inc.atlassian.net/browse/MAIN-10913
Our dark theme css is defining a style which is overriding another style we use to indicate a post is followed. Specifically, it was creating a `fill` style for the selector `.dark-theme .discussion-wrapper .discussion .icon`. That selector is more specific than the one we're using to update `fill` when a post is being followed defined [here](https://github.com/Wikia/mercury/blob/999a02ab50d6b1593e3757a298452c7fa9f3eae3/front/main/app/mixins/theme.js#L124).
Additionally, the `fill` style from our dark theme css is unnecessary, as that same style is defined in our `style-themed.css` in a way which is not overly specific, allowing us to override it when the post is followed.
So I'm just removing the problem style from the dark theme css. …
> MAIN-10913 l remove icon styling from dark theme

- front/main/app/components/discussion-post-image.js
- front/main/app/templates/components/discussion-post-card-detail.hbs
- front/main/app/templates/components/discussion-post-card-reply.hbs
- front/main/app/templates/components/discussion-post-image.hbs
- front/main/app/templates/components/discussion-post-images.hbs
- front/main/app/templates/components/discussion-post.hbs
- front/main/app/templates/components/discussion-reported-posts-wrapper.hbs
- front/main/app/templates/components/discussion-user-list-wrapper.hbs
- front/main/tests/unit/components/discussion-post-image-test.js
* https://wikia-inc.atlassian.net/browse/IRIS-4934
* https://stackoverflow.com/questions/44991155/prevent-upscaling-with-scrset
Use `<img srcset>` instead of `<picture><source></picture>`. It's simpler as the browser handles pixel ratio by itself. 
@slayful
> IRIS-4934 | Fix and simplify post image thumbnailing process

- front/main/app/components/discussion-image-upload-input.js
- front/main/app/components/discussion-image-upload.js
- front/main/app/mixins/discussion-contribution-controller.js
- front/main/app/models/discussion/domain/content-images.js
- front/main/app/templates/components/discussion-feed.hbs
- front/main/app/templates/components/discussion-forum-wrapper.hbs
- front/main/app/templates/components/discussion-image-upload-input.hbs
- front/main/app/templates/components/discussion-image-upload.hbs
- front/main/app/templates/components/discussion-inline-editor.hbs
- front/main/app/templates/components/discussion-post.hbs
- front/main/app/templates/components/discussion-standalone-editor.hbs
- front/main/app/templates/discussion/follow.hbs
- front/main/app/templates/discussion/forum.hbs
- front/main/app/templates/discussion/post.hbs
- front/main/app/templates/discussion/reported-posts.hbs
- front/main/app/templates/discussion/user.hbs
* http://wikia-inc.atlassian.net/browse/IRIS-1635
Use editor errors instead of global `alert-notifications`.
Remove input reset from `discussion-image-upload` as the component is destroyed when the upload starts.
@slayful 
/cc @bkoval @kvas-damian
> IRIS-1635 | Show image upload errors inside editor

- front/main/app/components/discussion-reply-editor-entry-point.js
- front/main/app/components/user-avatar.js
- front/main/app/templates/components/discussion-contributors.hbs
- front/main/app/templates/components/discussion-inline-editor.hbs
- front/main/app/templates/components/discussion-post-card-detail.hbs
- front/main/app/templates/components/discussion-post-card-reply.hbs
- front/main/app/templates/components/discussion-reply-editor-entry-point.hbs
- front/main/app/templates/components/discussion-report-details-user-list.hbs
- front/main/app/templates/components/discussion-user-activity-list.hbs
- front/main/app/templates/components/left-rail-details.hbs
- front/main/app/templates/components/user-avatar.hbs
- front/main/app/templates/components/wds-avatar-stack.hbs
- front/main/app/templates/components/wikia-user-profile.hbs
* https://wikia-inc.atlassian.net/browse/IRIS-5013
Use thumbnails instead of full-size images. Doesn't work for default wiki avatars like http://images.wikia.com/messaging/images/e/e5/Avatar4.jpg.
I chose the sizes based on CSS.
@slayful
> IRIS-5013 | Use thumbnails for avatars

- front/main/app/components/discussion-guidelines-editor.js
- front/main/app/components/discussion-inline-editor.js
- front/main/app/components/discussion-post-card-detail.js
- front/main/app/components/discussion-standalone-editor.js
- front/main/app/mixins/discussion-editor-opengraph.js
- front/main/app/models/discussion/domain/content-images.js
- front/main/app/templates/components/discussion-inline-editor.hbs
- front/main/app/templates/components/discussion-standalone-editor.hbs
* https://wikia-inc.atlassian.net/browse/IRIS-1620
A content image has priority over an open graph. Save both to service, it's handled by mobile apps as expected.
@slayful
> IRIS-1620 | Hide open graph when there is content image

- front/main/bower.json
* https://wikia-inc.atlassian.net/browse/MAIN-11576
* https://github.com/Wikia/vignette-js/pull/35
@slayful
> Update vignette-js to fix default avatar URLs

- server/app/facets/auth/piggyback.js
- server/app/facets/auth/reset-password.js
- server/app/facets/auth/signin.js
* https://kibana5.wikia-inc.com/goto/b0f9cbca59264ff26706acbc4eca3fbd
We were passing a stringified object from server to client and then treat it as an object, see https://github.com/Wikia/mercury/blob/09935dee9800bc3e87364a5e60c6e7929e97ce6a/front/auth/app/common/login.js#L128
Because of that, we were sending request to `/user-preference/undefined/global/requested-closure-date`
@slayful
> Parse payload JSON to make sure requested-closure-date gets user id

- server/app/facets/auth/logout.js
* http://wikia-inc.atlassian.net/browse/SEC-55
The theory is that nothing is using GET request to /logout handler to log out user, since all clients have been changed to use a POST instead. Let's verify this by logging unwanted GET requests.
> SEC-55 | Log all GET /logout requests

- front/auth/app/facebook/facebook-connect.js
* http://wikia-inc.atlassian.net/browse/SEC-55
Use POST instead of GET to log out user if an error occurs during the Facebook connect phase
> SEC-55 | Use POST instead of GET for /logout on connection error
